Fix engagements filters in 'engagements by product view'
DefectDojo/django-DefectDojo pull request #10046
Opened 2024-04-26 15:52 UTC by davidhernandeze

It's the same as #9913 but with the correct branching.

sc-[5299]

## Description
The engagement filters inside the "Engagements By Product" view are not working properly. Searching by the exact name in the "Engagement name" filter returns incorrect results.

## The Problem
Building relationship filters as we currently do in `EngagementFilter` generates a query that gets _filtered products with all the related engagements, where at least one engagement satisfies the filter criteria_.  The `engagements_all` view iterates over the engagements of each product to render the table rows. As a result, we showed all product engagements that satisfied the filter criteria. For example, if two engagements fulfill the filter criteria from two different products, the rendered table will show all engagements that belong to those two products.

## Solution
When prefetching the engament_set, an additional filter will filter the engagements at the query level, so only _filtered engagements_ related to _filtered products_ will be obtained.

``` python
engagement_query = Engagement.objects.annotate(test_count=Count('test__id'))
filter_qs = products_with_engagements.prefetch_related(
   Prefetch('engagement_set', queryset=ProductEngagementsFilter(request.GET, engagement_query).qs)
)
```

Also, the paginator object had to be modified to represent the correct number of rows currently shown on the page.

``` python
prods.paginator.count = sum(len(prod.engagement_set.all()) for prod in prods)
```

2024-04-26 16:26 UTC, Maffooch approved these changes

2024-04-26 16:39 UTC, davidhernandeze commented
[sc-5299]

2024-04-27 04:22 UTC, mtesauro approved these changes
Approved

2024-04-29 16:45 UTC, grendel513 approved these changes

2024-04-30 17:14 UTC, Maffooch requested changes
Please add support for filters without object lookups as well. Here is an example of doing so https://github.com/DefectDojo/django-DefectDojo/blob/f66e6dbb07bcddfb607ab81e76cca073080a6c2b/dojo/filters.py#L1065C1-L1093C75

2024-04-30 18:11 UTC, hblankenship approved these changes

2024-04-30 22:31 UTC, Maffooch approved these changes

2024-04-30 22:32 UTC, merged