:sparkles: implement progpilot SAST parser #10044
DefectDojo/django-DefectDojo pull request #10052
Opened 2024-04-29 05:50 UTC by manuel-sommer

see issue #10044

2024-05-02 03:53 UTC, Maffooch approved these changes

2024-05-02 21:27 UTC, mtesauro approved these changes
Approved

2024-05-03 15:15 UTC, grendel513 approved these changes

2024-05-03 21:43 UTC, cneill requested changes
Just a small typo, otherwise looks good

2024-05-03 21:43 UTC, cneill commented on unittests/tools/test_progpilot_parser.py
> +    def test_crunch42parser_single_has_many_findings(self):
```suggestion
    def test_progpilotparser_single_has_many_findings(self):
```

2024-05-03 21:43 UTC, cneill commented on unittests/tools/test_progpilot_parser.py
> +    def test_crunch42parser_single_has_one_finding(self):
```suggestion
    def test_progpilotparser_single_has_one_finding(self):
```

2024-05-03 21:43 UTC, cneill commented on unittests/tools/test_progpilot_parser.py
> +    def test_crunch42parser_single_has_many_findings3(self):
```suggestion
    def test_progpilotparser_single_has_many_findings3(self):
```

2024-05-03 21:43 UTC, cneill commented on unittests/tools/test_progpilot_parser.py
> +    def test_crunch42parser_single_has_many_findings4(self):
```suggestion
    def test_progpilotparser_single_has_many_findings4(self):
```

2024-05-03 22:55 UTC, cneill approved these changes

2024-05-03 22:56 UTC, merged