Ruff: add and fix INP
DefectDojo/django-DefectDojo pull request #10089
Opened 2024-05-02 10:31 UTC by kiblik

Add and fix INP rule

https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp

2024-05-03 02:42 UTC, mtesauro approved these changes
Approved

2024-05-04 08:13 UTC, kiblik commented on docker/__init__.py
I add `noqa` to `docker/install_chrome_dependencies.py`.

2024-06-19 03:43 UTC, Maffooch requested changes

2024-06-19 03:43 UTC, Maffooch commented on dojo/importers/importer/__init__.py
This directory does not exist anymore

2024-06-19 03:43 UTC, Maffooch commented on dojo/importers/reimporter/__init__.py
This directory does not exist anymore

2024-06-19 19:40 UTC, Maffooch approved these changes

2024-06-20 18:46 UTC, blakeaowens approved these changes

2024-06-21 21:22 UTC, merged