Make social login buttons fully clickable
DefectDojo/django-DefectDojo pull request #10304
Opened 2024-05-31 09:31 UTC by WojTecH94

Fix for https://github.com/DefectDojo/django-DefectDojo/issues/10292

2024-05-31 21:07 UTC, mtesauro approved these changes
Approved

2024-05-31 21:49 UTC, grendel513 commented
> Fix for #10292

@WojTecH94 will you please update the description to show the before and after so we can fully validate the UI change and how it will be displayed?

2024-05-31 22:51 UTC, grendel513 commented
> > Fix for #10292
> 
> 
> 
> @WojTecH94 will you please update the description to show the before and after so we can fully validate the UI change and how it will be displayed?

@WojTecH94 aoilogies, I should have been more clear. Please provide screenshots of before and after

2024-06-03 10:53 UTC, WojTecH94 commented
Screenshots added...

2024-06-03 16:30 UTC, blakeaowens approved these changes

2024-06-03 16:42 UTC, blakeaowens requested changes

2024-06-03 16:46 UTC, blakeaowens approved these changes

2024-06-03 17:10 UTC, Maffooch approved these changes

2024-06-03 17:14 UTC, grendel513 approved these changes

2024-06-03 18:04 UTC, merged