feat(django): Upgrade to 5.0
DefectDojo/django-DefectDojo pull request #10409
Opened 2024-06-15 08:11 UTC by kiblik

We released 4.2 so we can start migration to 5.0

2024-07-10 17:00 UTC, Maffooch approved these changes

2024-07-10 22:28 UTC, cneill approved these changes

2024-07-12 18:07 UTC, grendel513 approved these changes

2024-07-15 14:07 UTC, mtesauro requested changes

2024-07-15 14:07 UTC, mtesauro commented on requirements.txt
> +Django==5.0.7
Hold on merging this until after the 2.37.0 (August) minor release

So, nothing really to do here - just a note to my future self.

2024-08-06 15:53 UTC, mtesauro approved these changes
Approved

2024-08-06 15:54 UTC, merged