Improved naming of discovered findings filter and add same for mitigated
DefectDojo/django-DefectDojo pull request #10429
Opened 2024-06-19 11:09 UTC by quirinziessler

This PR updates the naming of filters related to #10401 to be a bit more precise.
Also it adds the same filter options for the "mitigated" field.

2024-07-23 08:21 UTC, manuel-sommer commented
Hi @mtesauro, could you take a look here? It would be nice if we can merge this for the next release :-)

2024-08-15 16:34 UTC, Maffooch requested changes
@quirinziessler thank you for your patience here! I left a few comments for moving forward and getting these changes merged 😄

2024-08-15 16:34 UTC, Maffooch commented on dojo/filters.py
> +        self.form.fields["on"].widget = date_mitigated_input_widget
```suggestion
        self.form.fields["mitigated_on"].widget = date_input_widget
        self.form.fields["mitigated_before"].widget = date_input_widget
        self.form.fields["mitigated_after"].widget = date_input_widget        
```
The `date_input_widget` could be reused from above. No need to redefine the same thing twice

2024-08-26 11:30 UTC, quirinziessler commented
@Maffooch added your suggestions to the MR. Sorry for the late reaction. Should be good to go from now.

2024-08-27 17:04 UTC, Maffooch commented on dojo/filters.py
> +    date = DateFromToRangeFilter(field_name="date", label="Date Discovered")
```suggestion
    date = DateRangeFilter(field_name="date", label="Date Discovered")
```
This change was reverted back to `DateRangeFilter` in the #10760 to accommodate date changes that are relative (i.e. X days ago) to today

2024-08-27 17:42 UTC, Maffooch approved these changes

2024-08-27 20:58 UTC, cneill approved these changes

2024-08-28 20:58 UTC, mtesauro approved these changes
Approved

2024-08-29 21:55 UTC, blakeaowens approved these changes

2024-08-29 22:50 UTC, merged