feat(docker): Use Python 3.12 in docker images
DefectDojo/django-DefectDojo pull request #10473
Opened 2024-06-28 18:53 UTC by kiblik

Next try for #10333

2025-01-29 21:10 UTC, Maffooch commented
Hey @kiblik I'm closing this one out for now until are ready to make this move

2025-07-31 15:26 UTC, valentijnscholten commented
reopening this as the final hurdle should be resolved by pygithub was updated.

2025-08-20 17:38 UTC, kiblik commented
Looks like we are finally ready 🎉

2025-08-24 07:35 UTC, valentijnscholten requested changes
can you update https://github.com/DefectDojo/django-DefectDojo/blob/bugfix/readme-docs/CONTRIBUTING.md#python3-version as well?

I am also wondering if we should add another line somewhere to explicitly indicate Defect Dojo requires Python 3.12+?

2025-08-24 10:14 UTC, kiblik commented
> can you update https://github.com/DefectDojo/django-DefectDojo/blob/bugfix/readme-docs/CONTRIBUTING.md#python3-version as well?
> 

done (btw, I found one more)

> I am also wondering if we should add another line somewhere to explicitly indicate Defect Dojo requires Python 3.12+?

Not sure if it is explicitly necessary. As soon as you start collaborating, you will notice which `ruff` rules will fail and what is not working. And it is quite easy to notice the version in Docker images. How often is DefectDojo running outside of Docker?
I'm not against this idea. I just do not see it as necessary. But if you have some explicit proposal, I'm happy to add it.

2025-08-25 16:58 UTC, valentijnscholten approved these changes

2025-08-27 13:06 UTC, kiblik commented
@mtesauro, @Maffooch 🙏

2025-08-27 17:04 UTC, kiblik commented
@valentijnscholten, can we target this PR to `2.50.0` as well?

2025-08-27 17:04 UTC, mtesauro commented
We have a bunch of changes landing in 2.50.0 so I wonder if it makes sense to hold off till 2.51.0 for this change.

2025-09-05 13:40 UTC, kiblik commented
I believe, this might be reviewed and merged.

2025-09-10 20:56 UTC, merged