Checkmarx one SCA parser fix
DefectDojo/django-DefectDojo pull request #10770
Opened 2024-08-16 10:50 UTC by adamtimmins

**Description**

Describe the feature / bug fix implemented by this PR.
Fixing the way the parser handles findings with CWE string value from Checkmarx One JSON report.

**Test results**

Added new data in `many_findings.json` for the unit test to show the varied CWE results in the reports. 

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [x] Bugfixes should be submitted against the `bugfix` branch.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [x] If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR.
- [x] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [x] Add applicable tests to the unit tests.
- [x] Add the proper label to categorize your PR.

**Extra information**

The current implementation of the parser could not handle CWE findings in the string format. Parser would raise an exception when the CWE was not an int.

2024-08-16 16:35 UTC, Maffooch requested changes

2024-08-16 16:35 UTC, Maffooch commented on unittests/scans/checkmarx_one/many_findings.json
It would be preferable to upload a new report rather than modifying an existing one. That would also help ensure that old and new versions are supported. Please add a new unit test for this new file as well

2024-08-16 22:06 UTC, mtesauro commented on unittests/scans/checkmarx_one/many_findings.json
+1 on :point_up:

2024-08-19 10:10 UTC, adamtimmins commented on unittests/scans/checkmarx_one/many_findings.json
Requested changes made. I'm unsure what to name the file / function since I don't think the reports are much different from what already exists in the unit tests.

2024-08-19 15:06 UTC, mtesauro commented on unittests/scans/checkmarx_one/many_findings.json
@adamtimmins  Frequently contributors who are fixing an issue with a parser and including a new output file to test that name it after the PR - something like `checkmarx-sca-10770.json` so it's clear why it was added.

HTH

2024-08-19 15:20 UTC, adamtimmins commented on unittests/scans/checkmarx_one/many_findings.json
@mtesauro file name changed to recommended

2024-08-28 22:28 UTC, Maffooch approved these changes

2024-08-29 16:17 UTC, cneill approved these changes

2024-08-29 21:32 UTC, mtesauro approved these changes
Approved

2024-08-29 21:56 UTC, blakeaowens approved these changes

2024-08-29 22:50 UTC, merged