SLA Config: Add new config that does not enforce SLA
DefectDojo/django-DefectDojo pull request #11086
Opened 2024-10-16 20:57 UTC by Maffooch

It would be nice ship dojo with an SLA config that easily omits SLA configs on a per product basis

[sc-7952]

2024-10-16 22:38 UTC, mtesauro approved these changes
Approved

2024-10-17 20:48 UTC, cneill approved these changes

2024-10-18 06:03 UTC, blakeaowens requested changes

2024-10-18 06:03 UTC, blakeaowens commented on dojo/fixtures/sla_configurations.json
> +        "pk": 100,
I think you can leave this out and Django will automatically assign the next available ID when the fixture is loaded.

Hopefully `100` is safe if we decide to keep it... ;)

2024-10-18 22:06 UTC, grendel513 approved these changes

2024-10-20 20:13 UTC, blakeaowens approved these changes

2024-10-21 14:18 UTC, merged