correct broken documentation links
DefectDojo/django-DefectDojo pull request #11178
Opened 2024-11-01 20:35 UTC by paulOsinski

Updating broken links in documentation

2024-11-01 20:50 UTC, cneill requested changes

2024-11-01 20:50 UTC, cneill commented on docs/content/en/getting_started/architecture.md
> +for asynchronous execution. [RabbitMQ](https://www.rabbitmq.com/) is a well established choice.
We're no longer supporting RabbitMQ and now prefer Redis, as noted [here](https://documentation.defectdojo.com/getting_started/architecture/#message-broker). We can copy that same language here or just leave it out.

```suggestion
for asynchronous execution.
```

2024-11-01 21:00 UTC, grendel513 approved these changes

2024-11-01 21:34 UTC, Maffooch approved these changes
Your fork is a little old. A given branch on your fork can be quickly synced with the "sync" button
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/cba88030-adc4-458f-985e-6452a9769aea">

I wish this was a thing when I was learning git 😅

2024-11-02 01:29 UTC, mtesauro approved these changes
Approved

2024-11-04 16:14 UTC, rossops approved these changes

2024-11-04 16:19 UTC, merged