Mitigated On/Before/After now use DateTimeFilter
DefectDojo/django-DefectDojo pull request #11472
Opened 2024-12-26 13:01 UTC by hblankenship

Fixes filtering for  mitigation for the on/before/after fields

[sc-7759]

2025-01-02 17:03 UTC, Maffooch commented on dojo/filters.py
> +    mitigated_after = DateTimeFilter(field_name="mitigated", lookup_expr="gt")
If a user were to be reliant on passing a date to this filter, would the API accept the absence of the timestamp? For example, if the query was `mitigated_on=2025-01-02` would a validation error be thrown?

2025-01-02 17:42 UTC, hblankenship commented on dojo/filters.py
> +    mitigated_after = DateTimeFilter(field_name="mitigated", lookup_expr="gt")
A validation error does not get thrown if you use 2025-01-02 without the timestamp. Should it?

2025-01-02 21:30 UTC, Maffooch commented on dojo/filters.py
> +    mitigated_after = DateTimeFilter(field_name="mitigated", lookup_expr="gt")
No, a validation error should not be raised. I was asking to make sure that this change would not cause any issues for users that were currently using dates

2025-01-03 19:08 UTC, Maffooch approved these changes

2025-01-03 19:10 UTC, mtesauro approved these changes
Approved

2025-01-10 18:51 UTC, blakeaowens approved these changes

2025-01-13 18:29 UTC, cneill requested changes
This doesn't seem to be operating how I would expect... I spun up a test instance, created some findings, and marked them mitigated. The UI uses a date-picker widget that won't allow you to enter a timestamp, so I couldn't test that.

With the API, I have 3 mitigated findings with these `mitigated` values:

```
❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/" | jq '.results[] | select(.mitigated != null) | .mitigated'

"2025-01-13T18:08:05.911321Z"
"2025-01-13T18:08:05.922679Z"
"2025-01-13T18:08:05.930498Z"
```

Testing `mitigated_on` with a simple date:
```
❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_on=2025-01-13"
{"count":0,"next":null,"previous":null,"results":[],"prefetch":{}}%
```

It wants an exact timestamp:
```
❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_on=2025-01-13T18:08:05.911321Z"
{"count":1,"next":null,"previous":null,"results":[{"id":1, ... }]}
```

The `mitigated_after` and `mitigated_before` filters *sort of* work as expected with simple dates, but I assume it is just plugging in a `00:00:00` for the time, so for example this returns my 3 findings that were mitigated today, 2025-01-13, where  `mitigated_after` would only have included things *after* today (23:59:59) in the past.

```
❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_after=2025-01-13"
{"count":3,"next":null,"previous":null,"results":[{"id":1, ... }]}
```

I think this needs some additional tweaking, and could really use some unit tests.

2025-01-14 13:29 UTC, hblankenship commented
> This doesn't seem to be operating how I would expect... I spun up a test instance, created some findings, and marked them mitigated. The UI uses a date-picker widget that won't allow you to enter a timestamp, so I couldn't test that.
> 
> With the API, I have 3 mitigated findings with these `mitigated` values:
> 
> ```
> ❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/" | jq '.results[] | select(.mitigated != null) | .mitigated'
> 
> "2025-01-13T18:08:05.911321Z"
> "2025-01-13T18:08:05.922679Z"
> "2025-01-13T18:08:05.930498Z"
> ```
> 
> Testing `mitigated_on` with a simple date:
> 
> ```
> ❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_on=2025-01-13"
> {"count":0,"next":null,"previous":null,"results":[],"prefetch":{}}%
> ```
> 
> It wants an exact timestamp:
> 
> ```
> ❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_on=2025-01-13T18:08:05.911321Z"
> {"count":1,"next":null,"previous":null,"results":[{"id":1, ... }]}
> ```
> 
> The `mitigated_after` and `mitigated_before` filters _sort of_ work as expected with simple dates, but I assume it is just plugging in a `00:00:00` for the time, so for example this returns my 3 findings that were mitigated today, 2025-01-13, where `mitigated_after` would only have included things _after_ today (23:59:59) in the past.
> 
> ```
> ❯ curl -H "Authorization: Token ${DD_API_KEY}"  "http://localhost:8080/api/v2/findings/?mitigated_after=2025-01-13"
> {"count":3,"next":null,"previous":null,"results":[{"id":1, ... }]}
> ```
> 
> I think this needs some additional tweaking, and could really use some unit tests.

With simple dates being given, it does indeed use 00:00:00 as the time. The request was to make it use DateTimeFilter which means it expects a full datetime. Per the Story: 

```The UI and API use a date filter for the mitigated field rather than a datetime filter. The datetime filter should be used instead

So when you said 'after' and gave 2025-01-13, the assumption is that you meant 2025-01-13T00:00:00. That said, I think we can alter the after to add a 23:59:59 timestamp if it is not added instead of the 00:00:00.
In a similar manner, mitigated_on will NOT work without a specific time. DateTimeFilters being what they are. Happy to entertain thoughts on this one.

2025-01-16 01:04 UTC, cneill commented on dojo/filters.py
> +            value = value.replace(hour=23, minute=59, second=59)
This logic is a little trickier when it comes to the API, because the user *could* intentionally query for "after 2025-01-01 00:00:00"... But I think this approach strikes the right balance - it seems much more likely that we'll receive dates without timestamps than dates with explicit 00:00:00 timestamps, and this would mirror the UI's behavior as well. In any case, the user can always search for "after 2024-12-31" to achieve the same thing if that's truly what they want.

2025-01-16 01:09 UTC, cneill commented on dojo/filters.py
> +    mitigated_on = DateTimeFilter(field_name="mitigated", lookup_expr="exact")
It seems very unlikely to me that a user will ever actually want to list Findings mitigated on an exact timestamp down to the microsecond, even if this would theoretically give them that option. I think searching the range `[ <date> 00:00:00, <date+1> 00:00:00 )` is the right approach here too, regardless of whether the user specified a timestamp.

2025-01-16 17:39 UTC, cneill approved these changes
Looks good! 😄

2025-01-16 19:33 UTC, merged