K8s helm extending configs
DefectDojo/django-DefectDojo pull request #2819
Opened 2020-09-01 08:12 UTC by dsever

@ptrovatelli 

Related to https://github.com/DefectDojo/django-DefectDojo/pull/2584 

Additional to previous PR test for pqsql replicas  and test for extra configs have been added

Old PR can can be closed.

2020-09-02 09:35 UTC, ptrovatelli approved these changes

2020-09-03 11:49 UTC, madchap commented
fyi @ccojocar

2020-09-03 12:18 UTC, dsever commented
@madchap,  after we did two days ado some changes inside of travis files i need to reflect the same into this PR `or tests will fail :/

2020-09-03 13:15 UTC, dsever commented
> @madchap, after we did two days ado some changes inside of travis files i need to reflect the same into this PR `or tests will fail :/

Fixed

2020-09-03 13:26 UTC, ptrovatelli requested changes

2020-09-03 13:26 UTC, ptrovatelli commented on helm/defectdojo/templates/django-deployment.yaml
> +<<<<<<< HEAD
this file seems part of an unfinished merge and will break the deployment

2020-09-03 13:44 UTC, ptrovatelli commented
@dsever sorry to insist, but are those commits on dev branch? if yes, you should rebase rather than picking commits. It makes the review much easier 
as per the PULL_REQUEST_TEMPLATE.md, you only need to: 

this first part is just to "erase" the commits you just picked/merged (assuming your clone is the remote `myOrigin` and the main github remote is `origin`;  check the remotes aliases with `git remote -v` )
```
git checkout k8s-helm-extending-configs
git rebase -i origin/dev
```
a file should open, replace in it "pick" by "drop" to erase the commits

Check the result with `git log`. You should be in the same state as yesterday

Then follow the PULL_REQUEST_TEMPLATE.md  :
`
git rebase dev k8s-helm-extending-configs
`

In case of conflict: 
```
 git mergetool
 git rebase --continue
 ```

Check the result with `git log`: again you should see the exact same commits as yesterday, just now they are placed after dev (except if you resolved conflicts)

When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```

To cancel everything: 
```
git rebase --abort
```

thanks!

2020-09-04 14:50 UTC, ccojocar approved these changes
LGTM

2020-09-04 15:37 UTC, madchap approved these changes

2020-09-04 15:39 UTC, madchap commented
lgtm too. Squash and merge anyways. @ptrovatelli you want to have a last look? @alles-klar ?

2020-09-07 12:27 UTC, dsever commented
Please take a look https://github.com/DefectDojo/django-DefectDojo/pull/2847

It is squashed

2020-09-07 14:29 UTC, ptrovatelli commented
https://github.com/DefectDojo/django-DefectDojo/pull/2847 is easier to review; closing this one

2020-09-07 14:29 UTC, closed without merging