add datetime to logformat (use verbose)
DefectDojo/django-DefectDojo pull request #3133
Opened 2020-10-30 14:26 UTC by valentijnscholten

By default the log output from DD is not displaying any date or time. Personally I prefer to have the default to use the `verbose` logformat which basically only adds a datetimestamp at the beginning of the line.

2020-11-01 17:22 UTC, Maffooch approved these changes

2020-11-07 21:03 UTC, madchap approved these changes
Useful for bash deployments at least ;-)

2020-11-07 21:03 UTC, madchap requested changes
Are you sure you want to merge to `master` or not `dev`?

2020-11-07 21:14 UTC, valentijnscholten commented
> Are you sure you want to merge to `master` or not `dev`?

good point. I think this explains why my other PR few days ago was still pointing to dev. must have had them mixed up. not a surprise with these helpful branchnames...

2020-11-11 19:26 UTC, Maffooch commented
Merging because Fred approved when it was on `master`

2020-11-11 19:26 UTC, merged