Use serializers instead of direct access to fields of model instance
DefectDojo/django-DefectDojo pull request #3141
Opened 2020-11-02 13:55 UTC by RomainJufer

Fix the issue raised in #3100. 

Introduce serializers for the related fields instead of accessing the fields directly from the model. While this follows the design principles of django it also changes a bit the structure of the returned object. More specifically, we don't have all the referred fields as direct children of the parent JSON object `related_fields`. Instead, we have an object with the same structure as defined in the models.

This fix also adds the swagger documentation for the response as it was missing from the current implementation.

Note : I kept the name `related_fields`, however, we might want to rename it ?

2020-11-02 17:35 UTC, valentijnscholten requested changes
Thanks. Two observations:
- This PR removes branch and display_status
- This PR removes the need to provide a value for the related_fields parameter (true)

2020-11-03 07:07 UTC, RomainJufer commented
Nice catch, thanks ! Sorry. I've corrected both points, should be fine now

2020-11-03 08:28 UTC, valentijnscholten commented
We named the status field `display_status` as it is a field meant for displaying and not really a real status field that can be used to make comparisons or implement logic in it. Could name it as that?

What we did wrong in the previous PR is add this field to `related_fields`. I think it should be just a field on the finding? Maybe you could move it into the right spot now that the serializer is already there?

2020-11-03 09:58 UTC, RomainJufer commented
It is now named `display_status` and I it isn't related to the `related_fields` parameters. Is it fine like that ?

2020-11-03 10:12 UTC, valentijnscholten approved these changes

2020-11-03 10:12 UTC, valentijnscholten commented
yes, thanks.

2020-11-06 23:30 UTC, madchap approved these changes
Neat, thanks.

2020-11-06 23:30 UTC, merged