Jira webhook: fixed bug for jira-in-subdir instances (error 500)
DefectDojo/django-DefectDojo pull request #3217
Opened 2020-11-09 13:15 UTC by reinier-vegter

Tested on Jira cloud.

This PR solves the issue when someone has Jira installed in a subfolder, instead of on `/` (like Jira cloud) (results in error 500).
The old code just parses the 'self' link and makes assumptions, which is now replaced by using the proper field in the JSON body.

Possibly related to 
https://github.com/DefectDojo/django-DefectDojo/issues/2976 and
https://github.com/DefectDojo/django-DefectDojo/issues/2784 .

According to https://developer.atlassian.com/cloud/jira/service-desk/webhooks/ (section `Comment shape` at the bottom) 
`.issue.id` is available, which appears to be true (tested) in the case of Jira cloud and our own instance.

2020-11-10 16:42 UTC, valentijnscholten approved these changes

2020-11-10 23:19 UTC, Maffooch commented
Would this change still work for the server versions of JIRA? It would be better to support both ways of getting the `jid` just in case.

2020-11-11 18:09 UTC, valentijnscholten commented
this is what can see incoming from JIRA for `comment_created`:

```
    {
    "timestamp":1605117321425,
    "webhookEvent":"comment_created",
    "comment":{
        "self":"https://jira.onpremise.org/rest/api/2/issue/89820/comment/456843",
        "id":"456843",
        "author":{
            "self":"https://jira.onpremise.org/rest/api/2/user?username=valentijn",
            "name":"valentijn",
            "key":"valentijn",
            "avatarUrls":{
                "48x48":"https://jira.onpremise.org/secure/useravatar?ownerId=valentijn&avatarId=11101",
                "24x24":"https://jira.onpremise.org/secure/useravatar?size=small&ownerId=valentijn&avatarId=11101",
                "16x16":"https://jira.onpremise.org/secure/useravatar?size=x small&ownerId=valentijn&avatarId=11101",
                "32x32":"https://jira.onpremise.org/secure/useravatar?size=medium&ownerId=valentijn&avatarId=11101"
            },
            "displ ayName":"Valentijn Scholten",
            "active":true,
            "timeZone":"Europe/Amsterdam"
        },
        "body":"test2",
        "updateAuthor":{
            "self":"https://jira.onpremise.org/rest/ap i/2/user?username=valentijn",
            "name":"valentijn",
            "key":"valentijn",
            "avatarUrls":{
                "48x48":"https://jira.onpremise.org/secure/useravatar?ownerId=valentijn&avatarId=11101",
                "24x24":"https://jira.onpremise.org/secure/useravatar?size=small&ownerId=valentijn&avatarId=11101",
                "16x16":"https://jira.onpremise.org/secure/useravatar?size=xsmall&ownerId=valentijn&avatarId=11101",
                "32x32":"https://jira.onpremise.org/secure/useravatar?size=medium&ownerId=valen tijn&avatarId=11101"
            },
            "displayName":"Valentijn Scholten",
            "active":true,
            "timeZone":"Europe/Amsterdam"
        },
        "created":"2020-11-11T18:55:21.425+0100",
        "updated":"2020-11-11T18:55:21.425+0100"
    }
    }
```

    comment created incoming json format
    {
    "timestamp":1605117321425,
    "webhookEvent":"comment_created",
    "comment":{
        "self":"https://jira.onpremise.org/rest/api/2/issue/89820/comment/456843",
        "id":"456843",
        "author":{
            "self":"https://jira.onpremise.org/rest/api/2/user?username=valentijn",
            "name":"valentijn",
            "key":"valentijn",
            "avatarUrls":{
                "48x48":"https://jira.onpremise.org/secure/useravatar?ownerId=valentijn&avatarId=11101",
                "24x24":"https://jira.onpremise.org/secure/useravatar?size=small&ownerId=valentijn&avatarId=11101",
                "16x16":"https://jira.onpremise.org/secure/useravatar?size=x small&ownerId=valentijn&avatarId=11101",
                "32x32":"https://jira.onpremise.org/secure/useravatar?size=medium&ownerId=valentijn&avatarId=11101"
            },
            "displ ayName":"Valentijn Scholten",
            "active":true,
            "timeZone":"Europe/Amsterdam"
        },
        "body":"test2",
        "updateAuthor":{
            "self":"https://jira.onpremise.org/rest/ap i/2/user?username=valentijn",
            "name":"valentijn",
            "key":"valentijn",
            "avatarUrls":{
                "48x48":"https://jira.onpremise.org/secure/useravatar?ownerId=valentijn&avatarId=11101",
                "24x24":"https://jira.onpremise.org/secure/useravatar?size=small&ownerId=valentijn&avatarId=11101",
                "16x16":"https://jira.onpremise.org/secure/useravatar?size=xsmall&ownerId=valentijn&avatarId=11101",
                "32x32":"https://jira.onpremise.org/secure/useravatar?size=medium&ownerId=valen tijn&avatarId=11101"
            },
            "displayName":"Valentijn Scholten",
            "active":true,
            "timeZone":"Europe/Amsterdam"
        },
        "created":"2020-11-11T18:55:21.425+0100",
        "updated":"2020-11-11T18:55:21.425+0100"
    }
    }
```

So the most reliable way would be to do a call to JIRA to retrieve the comment and find out which issue it belongs too.
Funny thing is, for each comment, I am getting *two* webhook events incoming. `comment_created` AND `issue_upated`.

issue updated incoming json
{
   "timestamp":1605117321475,
   "webhookEvent":"jira:issue_updated",
   "issue_event_type_name":"issue_commented",
   "user":{
      "self":"https://jira.onpremise.org/rest/api/2/user?username=valentijn",
      "name":"valentijn",
      "key":"valentijn",
      "emailAddress ":"valentijn.scholten@isaac.nl",
      "avatarUrls":{
         "48x48":"https://jira.onpremise.org/secure/useravatar?ownerId=valentijn&avatarId=11101",
         "24x24":"http s://jira.onpremise.org/secure/useravatar?size=small&ownerId=valentijn&avatarId=11101",
         "16x16":"https://jira.onpremise.org/secure/useravatar?size=xsmall& ownerId=valentijn&avatarId=11101",
         "32x32":"https://jira.onpremise.org/secure/useravatar?size=medium&ownerId=valentijn&avatarId=11101"
      },
      "displayName ":"Valentijn Scholten",
      "active":true,
      "timeZone":"Europe/Amsterdam"
   },
   "issue":{
      "id":"89820",
      "self":"https://jira.onpremise.org/rest/api/2/issue/89820 ",
      "key":"ISEC-277",
      "fields":{
         "issuetype":{
            "self":"https://jira.onpremise.org/rest/api/2/issuetype/3",
            "id":"3",
            "description":"A task is some piece o f work that can be assigned to a user. This does not always result in a quotation/estimate, as it is often some task that needs to be performe d in the context of an existing contract. ",
            "iconUrl":"https://jira.onpremise.org/secure/viewavatar?size=xsmall&avatarId=16681&avatarType=issuetype",
            "name":"Task",
            "subtask":false,
            "avatarId":16681
         },
         "timespent":null,
         "customfield_10195":null,
         "project":{
            "self":"https://jira.onpremise.org/rest/api/2/project/13532",
            "id":"13532",
            "key":"ISEC",
            "name":"ISAAC security",
            "projectTypeKey":"software",
            "avatarUrls":{
               "48x48":"https://jira.onpremise.org/secure/projectavatar?avatarId=14803",
               "24x24":"https://jira.onpremise.org/secure/projectavatar?size=small&avatarId=14803",
               "16x16":"https://jira.onpremise.org/secure/projectavatar?size=xsmall&avatarId=14803",
               "32x32":"https://jira.onpremise.org/secure/projectavatar?size=medium&avatarId=14803"
            },
            "projectCategory":{
               "self":"https://jira.onpremise.org/rest/api/2/projectCategory/10032",
               "id":"10032",
               "description":"All internal isaac projects.",
               "name":"isaac internal"
            }
         },
         "customfield_10230":null,
         "fixVersions":[
            
         ],
         "customfield_11440":"0|y02wb8:",
         "aggregatetimespent":null,
         "customfield_11640":null,
         "resolution":null,
         "resolutiondate":null,
         "workratio":-1,
         "lastViewed":"2020-11-11T18:54:32.489+0100",
         "watches":{
            "self":"https://jira.onpremise.org/rest/api/2/issue/ISEC-277/watchers",
            "watchCount":1,
            "isWatching":true
         },
         "customfield_10060":[
            "defect.dojo(defect.dojo)",
            "valentijn(valentijn)"
         ],
         "customfield_10182":null,
         "created":"2019-04-04T15:38:21.248+0200",
         "customfield_12043":null,
         "customfield_10340":null,
         "customfield_10341":null,
         "customfield_12045":null,
         "customfield_10100":null,
         "priority":{
            "self":"https://jira.onpremise.org/rest/api/2/priority/5",
            "iconUrl":"https://jira.onpremise.org/images/icons/priorities/trivial.svg",
            "name":"Trivial (Sev5)",
            "id":"5"
         },
         "customfield_10740":null,
         "labels" [...]

2020-11-11 18:13 UTC, valentijnscholten commented
and we have the option to include issue id / key in the webhook url:

```
![image](https://user-images.githubusercontent.com/4426050/98848381-f073bd80-2451-11eb-98a4-ff50e7df9f60.png)
```

https://developer.atlassian.com/server/jira/platform/webhooks/

2020-11-11 18:15 UTC, valentijnscholten commented
@reinier-vegter quickfix for now could be to just make the logic correctly handle the `self` url of the comment that was created: 
`https://jira.isaac.nl/rest/api/2/issue/89820/comment/456843`. i.e. do a regex match on `issue/($1)/comment` or something.

2020-11-12 08:09 UTC, valentijnscholten requested changes
@reinier-vegter quickfix for now could be to just make the logic correctly handle the self url of the comment that was created:
https://jira.isaac.nl/rest/api/2/issue/89820/comment/456843. i.e. do a regex match on issue/($1)/comment or something.

2020-11-17 12:55 UTC, reinier-vegter commented
We were implementing it yesterday against an on-prem instance and I found out it doesn't work indeed, so I just went back here to warn, but saw you already came to the same conclusion @valentijnscholten, so, good that you tested it.

I want to spend a bit of time soon to find out why on-prem and cloud seem to give a different JSON body, because the docs aren't very clear on this (or I missed something earlier).

But yeah, perhaps the best approach is to change the defectdojo doc on Jira integration / use the issue-ID substitution in the URL, and add `.issue.id` and URL-parsing as fallbacks (in that order of preference).

On the other hand, fetching the information from Jira based on the comment-ID in the webhook also solves the fact that the webhook endpoint is a public one, hence vulnerable without additional proxy/ingress filtering.
But in turn it is less performant.

What do you think ?

2020-11-17 13:01 UTC, valentijnscholten commented
i'm tempted to say "just change the way it gets the id". A call to JIRA is an interesting way to "secure" the endpoint, but maybe a bit overkill and might introduce possbilities to let DD perform lots of queries for unrelated issues?
And you would need to update the new unit tests to mock that extra call.
We just merged a big JIRA related PR, so rebasing would be smart anyway. There now also is the possibility to configure a secret on the webhook.

2020-11-21 18:42 UTC, madchap commented
Superseded by https://github.com/DefectDojo/django-DefectDojo/pull/3321

2020-11-21 18:42 UTC, closed without merging