Only mitigate finding if previous active
DefectDojo/django-DefectDojo pull request #3523
Opened 2020-12-22 09:57 UTC by madchap

Fixes https://github.com/DefectDojo/django-DefectDojo/issues/3522

2020-12-22 11:17 UTC, valentijnscholten commented
Should the same check be applied in the API (haven't checked what's there now).
Also it looks like finding is set as mitigated when marked as false positive? (existing code)

2020-12-22 11:29 UTC, madchap commented
> Should the same check be applied in the API (haven't checked what's there now).
> Also it looks like finding is set as mitigated when marked as false positive? (existing code)

I'll take a look in the API.

Right, when FP, it's currently mitigated :man_shrugging: I didn't want to change it at first, but maybe this can be something to do now.

2020-12-22 12:37 UTC, valentijnscholten commented
not sure. it might have some benefits to mark the finding as mitigated when marked as false_p. SLA counter stops etc.
but in that case it should be the same for out_of_scope

2020-12-22 13:37 UTC, madchap commented
Tested the API, it seems it never had that behavior actually. It's not trying to assume anything.

2020-12-22 13:57 UTC, valentijnscholten commented
There is something around mitigated but it's about keeping the is_Mitigated in sync with mitigated. Maybe we should add the same logic there for false poistive and out of scope.

2020-12-22 17:35 UTC, valentijnscholten requested changes
there are some other places that need to use the new logic: 
![image](https://user-images.githubusercontent.com/4426050/102916823-7852db80-4484-11eb-8fcd-c0431063d39a.png)

2020-12-22 17:35 UTC, valentijnscholten commented on dojo/finding/helper.py
> +    logger.info("Finding status after update: {}".format(new_state_finding.status()))
lower log level or remove?

2020-12-23 09:07 UTC, madchap commented on dojo/finding/helper.py
> +    logger.info("Finding status after update: {}".format(new_state_finding.status()))
It was supposed to be debug definitely.

2020-12-28 17:13 UTC, valentijnscholten approved these changes

2020-12-29 08:29 UTC, merged