Parameter confidence is otional in GitLab SAST
DefectDojo/django-DefectDojo pull request #3567
Opened 2020-12-30 09:36 UTC by StefanFl

GitLab SAST doesn't always set the parameter ``confidence`` for a vulnerability, leading to an exception when importing the vulnerabilities.

2020-12-30 10:42 UTC, damiencarol commented
I just reviewed your modification and I have 2 comments here:
1) as the file is loaded with `json.load()` you have dictionaries for the items.
It means that you should use something like that to manage optional attributes:

```Python
scanner_confidence = vuln.get('confidence'], 'Unknown')
```

It seems that the default value is `Unknown`
2) the current code doesn't make any sense.

```Python
scanner_confidence = Finding.get_number_severity(vuln['confidence'])
```
[see here](https://github.com/DefectDojo/django-DefectDojo/pull/3567/files#diff-b50bc2a09a1d04194c4525846f3635f10820bca1ef2ad5acb0ddbd3e430e2248L93)
the function `get_number_severity` has no link to the confidence. **For me it is a bug.**

2020-12-30 10:45 UTC, damiencarol commented
Also, @StefanFl could you add another report and keep the old one? Could be good to have the report that makes you exceptions.
If you are ok to provide your report, keep in mind that it's an open-source project so remove the personal details in the report.
Thanks in advance.

2020-12-30 10:47 UTC, damiencarol requested changes
See my previous comments. Some modifications could be different.

2020-12-30 10:47 UTC, damiencarol commented on dojo/tools/gitlab_sast/parser.py
> +        scanner_confidence = Finding.get_number_severity(vuln['confidence'])
```suggestion
        scanner_confidence = vuln.get('confidence', 'Unknown')
```

2020-12-30 10:59 UTC, damiencarol commented
@StefanFl does this issue is linked to #3534?

2020-12-30 17:37 UTC, StefanFl commented
@damiencarol GitLab has 2 different scanners. GitLab SAST is static code analysis (the parser of this PR), while the PR you have referenced parses the results of the GitLab Dependency Scanner. File format for these 2 scanners seems to be pretty similar.

Thank you for the review, will change the files according to your suggestions.

2020-12-30 21:04 UTC, StefanFl commented
Interesting one, it was definitely a bug. GitLab SAST can produce a confidence, but the values (search for confidence in https://docs.gitlab.com/ce/development/integrations/secure.html) need to be mapped to the values understood by DefectDojo (see ``Finding.get_scanner_confidence_text()``).

The new report is an amended excerpt from findings for the OWASP Juice Shop, I think this should be allowed.

2020-12-31 07:40 UTC, StefanFl commented
Please wait with the review, I think there is another problem with these reports

2020-12-31 09:23 UTC, damiencarol commented
Take your time and happy new year!
For the record:
[https://docs.gitlab.com/ce/development/integrations/secure.html#severity-and-confidence](https://docs.gitlab.com/ce/development/integrations/secure.html#severity-and-confidence)

> The confidence ranges from Low to Confirmed, but it can also be Unknown, Experimental or even Ignore if the vulnerability is to be ignored. Valid values are: Ignore, Unknown, Experimental, Low, Medium, High, or Confirmed
>
> Unknown values means that data is unavailable to determine it’s actual value. Therefore, it may be high, medium, or low, and needs to be investigated. We have provided a chart of the available SAST Analyzers and what data is currently available.

2020-12-31 09:36 UTC, StefanFl commented
All values are mapped apart from `

-  ``Unkown`` where the confidence is set to ``None`` 
- ``Ignore`` where the confidence is set to ``None`` as well, because there is no respective value in DefectDojo

For the others see the method ``get_confidence_numeric(argument)`` in the parser

2020-12-31 09:44 UTC, StefanFl commented
A further test showed, that GitLab sometimes writes non-numerical CWE's which can not be stored in the database. There is a fix for it as well know including a new test case. 

Please re-review the whole PR, thank you.

2020-12-31 11:48 UTC, damiencarol approved these changes
LGTM, high quality modification, this will make Gitlab SAST parser more robust!

One minor feedback, you could have used the feature of subtests to check the items in the unit tests: [https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests](https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests)

2020-12-31 11:49 UTC, damiencarol commented
@valentijnscholten @madchap it's ready for review.

2020-12-31 20:33 UTC, valentijnscholten approved these changes

2021-01-06 18:18 UTC, damiencarol commented
@StefanFl why did you closed this PR ?

2021-01-06 18:37 UTC, StefanFl commented
Oops, that wasn't intended, thanks @damiencarol for notifying me.

2021-01-06 18:42 UTC, valentijnscholten approved these changes

2021-01-06 19:45 UTC, damiencarol approved these changes

2021-01-09 18:22 UTC, madchap approved these changes
good job @StefanFl and thanks for the tight review @damiencarol :)

2021-01-09 18:22 UTC, merged