Revert findings list to display jira key instead of jira bug icon
DefectDojo/django-DefectDojo pull request #3605
Opened 2021-01-09 18:38 UTC by madchap

When wanting to look at a glance or eventually take a screenshot, seeing the jira bug does not help much.

This PR reverts to the old display we used to have.

2021-01-09 19:53 UTC, valentijnscholten requested changes
Good idea. `view_test.html` needs the same change.

2021-01-10 10:34 UTC, damiencarol commented
@valentijnscholten @madchap is it possible to "test" this UI changes? Test the template or something?

2021-01-17 22:50 UTC, valentijnscholten approved these changes

2021-01-20 07:06 UTC, damiencarol approved these changes

2021-01-20 07:07 UTC, damiencarol commented
We have selenium in some integration tests. it is possible to check if some HTML element are in the page generated.

2021-01-20 09:39 UTC, merged