Snyk parser enhancements
DefectDojo/django-DefectDojo pull request #3616
Opened 2021-01-12 15:14 UTC by rmoldesc

This PR addresses the following features:

* Support for Snyk JSON reports generated with the --all-projects (e.g: Maven multi module projects). 

* Added the following missing fields for each Finding generated from a report:
  * CVSS3
  * Severity justification 
  * Mitigation
  * References
 
* Minor visual changes:
  * Added link to the Snyk Vulnerability Database for the referenced Snyk IDs.
  * Added bold format to the details section within the issue description.

2021-01-12 15:56 UTC, valentijnscholten commented
Hi, Can you provide sample scans for these new features? Can you set `component_name` and `component_version` fields?

2021-01-12 17:20 UTC, rmoldesc commented
> 
> 
> Hi, Can you provide sample scans for these new features? Can you set `component_name` and `component_version` fields?

Hi @valentijnscholten , I have generated two sample files you can find it [here](https://github.com/rmoldesc/snyk-sample-reports/tree/develop/baeldung)

What do you mean by set `component_name` and `component_version` fields? 
I think the value that is currently being assigned may be correct.

Regards.

2021-01-12 17:29 UTC, valentijnscholten commented
I meant can you extend the unit tests to use samples with the new features.

And sorry, didn't notice that component_name/version are already set correctly :-)

2021-01-13 17:10 UTC, valentijnscholten approved these changes

2021-01-13 18:46 UTC, damiencarol requested changes
Avoid adding HTML formatting in Finding attributes. If you want to have some formatting use Markdown syntax.

2021-01-13 18:46 UTC, damiencarol commented on dojo/tools/snyk/parser.py
> +        references = "<b>Custom SNYK ID</b>: https://app.snyk.io/vuln/{}\n\n".format(vulnerability['id'])
Avoid adding HTML formatting in `references` attribute. If you want to have some formatting use Markdown syntax
```suggestion
        references = "**Custom SNYK ID**: <https://app.snyk.io/vuln/{}>\n\n".format(vulnerability['id'])
```

2021-01-13 18:46 UTC, damiencarol commented on dojo/tools/snyk/parser.py
> +        references += "<b>" + item['title'] + "</b>: " + item['url'] + "\n"
Avoid adding HTML formatting in `references` attribute. If you want to have some formatting use Markdown syntax
```suggestion
        references += "**" + item['title'] + "**: <" + item['url'] + ">\n"
```

2021-01-13 18:46 UTC, damiencarol commented on dojo/tools/snyk/parser.py
> +        severity_justification="Issue severity of: <b>" + severity + "</b> from a base " +
Avoid adding HTML formatting in Finding attributes. If you want to have some formatting use Markdown syntax

2021-01-13 18:46 UTC, damiencarol commented on dojo/tools/snyk/parser.py
> +        description="<h2>Details</h2><p><li><b>Vulnerable Package</b>: " +
Avoid adding HTML formatting in Finding attributes. If you want to have some formatting use Markdown syntax

2021-01-14 09:55 UTC, damiencarol requested changes
There is one last thing that could be done.
cwe attribute of findings are integer. depending on the data the parser return an integer or a string.

Could you improve a little bit your pull request to manage this?

Some conversion in integer is required in this part I think:
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/snyk/parser.py#L65-L73

2021-01-14 09:55 UTC, damiencarol commented on dojo/unittests/test_snyk_parser.py
> +            "611",
cwe attributes is an integer if you check the model
```suggestion
            611,
```

2021-01-14 15:33 UTC, rmoldesc commented
> 
> 
> There is one last thing that could be done.
> cwe attribute of findings are integer. depending on the data the parser return an integer or a string.
> 
> Could you improve a little bit your pull request to manage this?
> 
> Some conversion in integer is required in this part I think:
> https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/snyk/parser.py#L65-L73

Hi @damiencarol , 

Made a refactor for the CWE parsing addressing the following points:
* Parse CWE as an integer
* Change JSON property checks, as the report will always contain an "identifiers" object. "CVE" and "CWE" will be lists even if they are empty.
  
Regards

2021-01-16 09:26 UTC, damiencarol approved these changes

2021-01-16 09:56 UTC, merged