Increase alert field size to 200
DefectDojo/django-DefectDojo pull request #3682
Opened 2021-01-22 12:37 UTC by madchap

When engagement name get a little too long, the alert title size goes over 100 characters, which provokes an error upon import such as

```
fail to import scan into engagement "xxxxx/ph-blablabla-value-beep-test:1.272.1", http status: 400, resp: {"detail":"{'title': ['Ensure this value has at most 100 characters (it has 111).']}"}]
```

2021-01-22 12:44 UTC, valentijnscholten commented
I already increased it locally in the past and found out 250 is about a good value. I also added a [:250] where the title for the alerts is being set to that it just truncates and doesn't prevent the import from completing.

2021-01-24 10:15 UTC, valentijnscholten commented
where did you get that error from? because in dev it is already truncating to 100:

![image](https://user-images.githubusercontent.com/4426050/105627161-5eb30400-5e35-11eb-92b0-b637af9dd99f.png)

that should be adjusted then to 250. 

and if this was causing an error where the title was over 100 there might another place where Alert objects are created?

2021-01-24 10:15 UTC, valentijnscholten requested changes
^^

2021-01-24 11:18 UTC, valentijnscholten commented
I see where you got the error, there is a second place where Alerts are being created and it truncates the `url` fields instead of `title`.

![image](https://user-images.githubusercontent.com/4426050/105628616-3976c380-5e3e-11eb-97b5-761854e57ef2.png)

2021-01-24 22:42 UTC, valentijnscholten commented
Can you remove the incorrect truncation of url?

2021-01-25 07:01 UTC, valentijnscholten approved these changes

2021-01-26 16:48 UTC, damiencarol approved these changes

2021-01-26 16:48 UTC, damiencarol commented on dojo/notifications/helper.py
> +            url=kwargs.get('url', reverse('alerts')),
this is a good catch!

2021-01-26 17:09 UTC, merged