remove s_finding_severity_naming
DefectDojo/django-DefectDojo pull request #3754
Opened 2021-01-30 23:49 UTC by manuel-sommer

https://github.com/DefectDojo/django-DefectDojo/issues/3707

2021-01-31 10:56 UTC, damiencarol requested changes

2021-01-31 17:41 UTC, manuel-sommer commented on dojo/templatetags/display_tags.py
>      return value
@damiencarol thanks, good catch. is it fine like this?

2021-02-05 19:13 UTC, manuel-sommer commented
@damiencarol Could you review it?

2021-02-07 20:26 UTC, valentijnscholten approved these changes
approved, but the migration needs a rename and dependency update after some recent other merges into dev.

2021-02-07 21:53 UTC, damiencarol requested changes

2021-02-07 21:53 UTC, damiencarol commented on dojo/db_migrations/0072_remove_system_settings_s_finding_severity_naming.py
> +        ('dojo', '0071_product_type_enhancement'),
there is a need to change that as we merged some PR with migration (see the current number in dev branch)

2021-03-07 10:59 UTC, valentijnscholten commented
@manuel-sommer we have decided to go ahead with this removal from the UI parts. Could you rebase to the latest dev or merge latest dev into your branch? And rename/update your migration accordingly? We will merge soon afterwards.

2021-05-01 16:57 UTC, valentijnscholten commented
superseded by #4415 due to lack of response and no access for maintainers to update the PR

2021-05-01 16:57 UTC, closed without merging