Helm mount ca volume, ingress spec
DefectDojo/django-DefectDojo pull request #3912
Opened 2021-02-22 20:39 UTC by dsever

This PR contains:
-  option to mount CA cert as volume
-  updated values.yaml
- updates ingress to networking.k8s.io/v1 spec
- Updates postgres helm (to respect: postgresql.shmVolume.enabled=false)

2021-02-23 08:18 UTC, madchap commented on helm/defectdojo/values.yaml
> +      configName: defect-dojo-ca-certs
maybe keep `defectdojo` as 1 word?

2021-02-23 08:24 UTC, madchap requested changes
Please bump up the chart number as well.

2021-02-23 10:08 UTC, dsever commented on helm/defectdojo/values.yaml
> +      configName: defect-dojo-ca-certs
Fixed

2021-02-24 12:31 UTC, madchap approved these changes

2021-02-24 16:35 UTC, alles-klar approved these changes

2021-02-24 16:37 UTC, merged