docs: migrate to github pages
DefectDojo/django-DefectDojo pull request #3977
Opened 2021-03-02 21:04 UTC by alles-klar

Migrates all links from readthedocs to github pages.

2021-03-03 08:12 UTC, valentijnscholten commented
thanks, big PR!

2021-03-03 08:13 UTC, valentijnscholten requested changes
you don't need a migration to only change a help text. it would save some migrations and the need for others to keep rebasing their migrations. wdyt? (just change the existing migration(s) for this field)

2021-03-03 08:47 UTC, alles-klar commented
Changing existing migrations usually not a good idea and can have a lot of side effects. I prefer to use our proved approach, also for small changes.

2021-03-03 08:48 UTC, valentijnscholten commented
There are no side affects if it doesn't affect the sql schema.

2021-03-03 13:33 UTC, damiencarol commented
I agree, we should remove this hard coded link to the documentation.

2021-03-03 19:15 UTC, valentijnscholten approved these changes

2021-03-03 21:25 UTC, madchap commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] If this is a new feature and not a bug fix, you've included the proper documentation in the documentation folder. https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs or provide featur
I'd go with just `If this is a new feature and not a bug fix, you've included the proper documentation in the docs at https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs as part of this PR`.
`

2021-03-03 21:25 UTC, madchap approved these changes
Thanks @alles-klar !

2021-03-03 21:26 UTC, madchap commented
Removing the `New Migration` label since there is no new migration file.

2021-03-04 08:23 UTC, damiencarol commented on dojo/db_migrations/0001_initial.py
> +                ('url', models.URLField(help_text='For more information how to configuring Jira, read the DefectDojo documentation.', max_length=2000, verbose_name='JIRA URL')),
```suggestion
                ('url', models.URLField(help_text='For more information how to configure Jira, read the DefectDojo documentation.', max_length=2000, verbose_name='JIRA URL')),
```

2021-03-04 18:07 UTC, merged