add new parsers - pmd, tfsec
DefectDojo/django-DefectDojo pull request #4003
Opened 2021-03-04 22:13 UTC by jis0324

Added new parsers - pmd, tfsec

2021-03-05 09:43 UTC, damiencarol commented
@jis0324 why closing this PR? your PR was good. There is some code to add but nothing hard.

2021-03-05 09:47 UTC, jis0324 commented
Hi, @damiencarol 
Actually, I was working with the forked repository.
Then I sent pull request to here, I think it was my fault.
Btw, Could you allow my request?

2021-03-05 09:50 UTC, jis0324 commented
If possible, I think I can open this request again.
Btw, How did you find my requests? actually, I deleted it soon since I requested it wrong.
lol..

2021-03-05 14:52 UTC, damiencarol requested changes
- split the 2 parsers in 2 PR
 - don't need to modify dojo/fixtures/test_type.json anymore
 - please get ride of meta attribute like `__author__`
 - address flake8 errors

2021-03-05 15:21 UTC, jis0324 commented
About : `split the 2 parsers in 2 PR`
Should I create two PR?
Or should I commit twice times in same PR?

2021-03-05 15:30 UTC, jis0324 commented
I seem to address your requirements.

2021-03-06 08:28 UTC, damiencarol commented
@jis0324 better to create 2 PR for 2 different parsers. I'm sorry to ask you more work :D

2021-03-06 08:39 UTC, damiencarol requested changes

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/__init__.py
> +__author__ = 'jis0324'
```suggestion
```
This is useless. We track authorship with our VCS.

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/parser.py
> +                priority = row["Priority"]
priority will be a number like "1" here.
```suggestion
                priority = "Info"
```

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/parser.py
> +            if finding is not None:
this test is useless because you assign an object at 31

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/parser.py
> +                if finding.title is None:
this test is useless because you assign a value at 32

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/parser.py
> +                if finding.description is None:
this test is useless because you assign a value at 50

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/pmd/parser.py
> +                key = hashlib.md5((finding.title + '|' + finding.description).encode("utf-8")).hexdigest()
Don't use MD5, it's flawed
```suggestion
                key = hashlib.sha256((finding.title + '|' + finding.description).encode("utf-8")).hexdigest()
```

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/tfsec/__init__.py
> +__author__ = 'jis0324'
```suggestion
```
This is useless. We track authorship with our VCS.

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/tfsec/parser.py
> +            elif row["severity"] == "WARNING":
This warning seems out of context.

2021-03-06 08:39 UTC, damiencarol commented on dojo/tools/tfsec/parser.py
> +            if finding is not None:
same comment as for the other parser.

2021-03-06 08:39 UTC, damiencarol commented on dojo/unittests/tools/test_pmd_parser.py
> +
Add more test on attributes like:
```suggestion
        self.assertEqual("Medium", findings[0].severity)

```

2021-03-06 08:39 UTC, damiencarol commented on dojo/unittests/tools/test_tfsec_parser.py
> +
Add more tests on attributes

2021-03-07 00:15 UTC, Maffooch commented
@jis0324 Whenever you do split this into two PR's please base them from them `dev` branch and then submit the PR against the `dev` branch so you don't get any funky conflicts or extra commits. Thanks!

2021-03-07 19:09 UTC, jis0324 commented
> @jis0324 better to create 2 PR for 2 different parsers. I'm sorry to ask you more work :D

No, It's okay, I am not familiar with GitHub's works.
This is my first PR. lol...

2021-03-07 19:21 UTC, jis0324 commented
Btw, I don't know how I can re-create PRs.
Could you give me any help or idea?

2021-03-07 21:53 UTC, damiencarol commented
@jis0324 you can create more than one branch in your fork. you can create on PR for each branch.
but if it's more easy, you can finish this one by keeping only one parser and after create a new one with the second parser.

2021-03-08 07:40 UTC, jis0324 commented
@damiencarol
Make sense what you mean.
So Should I close this PR?
Then I will creat new PR to dev branch. right?

2021-03-08 07:42 UTC, jis0324 commented
Which branch should I start from?
I mean which branch I will clone and update.

Clone `dev` branch, and then Request PR to `dev` branch.
Is right?

2021-03-08 08:13 UTC, damiencarol commented
yes. exactly

2021-03-08 18:12 UTC, closed without merging