[anchore parser] add cvssv3_score when available
DefectDojo/django-DefectDojo pull request #4182
Opened 2021-03-31 15:35 UTC by madchap

2021-04-01 15:43 UTC, madchap commented
Seems error come from somewhere else:
```
2021-04-01T14:59:23.2926238Z [36muwsgi_1         |[0m ======================================================================
2021-04-01T14:59:23.2927457Z [36muwsgi_1         |[0m FAIL: test_multiple2 (dojo.unittests.tools.test_safety_parser.TestSafetyParser)
2021-04-01T14:59:23.2928835Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-04-01T14:59:23.2929728Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-04-01T14:59:23.2930807Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_safety_parser.py", line 49, in test_multiple2
2021-04-01T14:59:23.2931896Z [36muwsgi_1         |[0m     self.assertIsNone(finding.cve)
2021-04-01T14:59:23.2932870Z [36muwsgi_1         |[0m AssertionError: 'CVE-2020-28493' is not None
2021-04-01T14:59:23.2933576Z [36muwsgi_1         |[0m 
2021-04-01T14:59:23.2934233Z [36muwsgi_1         |[0m ======================================================================
2021-04-01T14:59:23.2935659Z [36muwsgi_1         |[0m FAIL: test_multiple_cves (dojo.unittests.tools.test_safety_parser.TestSafetyParser)
2021-04-01T14:59:23.2940576Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-04-01T14:59:23.2941617Z [36muwsgi_1         |[0m Traceback (most recent call last):
2021-04-01T14:59:23.2942706Z [36muwsgi_1         |[0m   File "/app/dojo/unittests/tools/test_safety_parser.py", line 36, in test_multiple_cves
2021-04-01T14:59:23.2943812Z [36muwsgi_1         |[0m     self.assertIsNone(finding.cve)
2021-04-01T14:59:23.2944775Z [36muwsgi_1         |[0m AssertionError: 'CVE-2019-12385' is not None
2021-04-01T14:59:23.2945512Z [36muwsgi_1         |[0m 
2021-04-01T14:59:23.2946312Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2021-04-01T14:59:23.2947133Z [36muwsgi_1         |[0m Ran 1070 tests in 331.075s
2021-04-01T14:59:23.2947721Z [36muwsgi_1         |[0m 
2021-04-01T14:59:23.2948421Z [36muwsgi_1         |[0m FAILED (failures=2, skipped=82)
2021-04-01T14:59:23.2949422Z [36muwsgi_1         |[0m Destroying test database for alias 'default' ('test_defectdojo')...
```

Tests pass fine locally:

![image](https://user-images.githubusercontent.com/5468769/113319513-c8f29400-9311-11eb-9e26-3f87bdbcc058.png)

2021-04-01 17:35 UTC, valentijnscholten commented
tests are failing due to #4191

2021-04-01 17:36 UTC, valentijnscholten approved these changes

2021-04-05 19:18 UTC, Maffooch approved these changes

2021-04-06 12:41 UTC, damiencarol requested changes
@madchap could you add more checks on the score attributes in the unit tests?
And maybe rebase on last dev branch as the bug with Safety parser is fixed now

2021-04-07 10:55 UTC, damiencarol approved these changes

2021-04-07 10:55 UTC, damiencarol commented
@madchap added more checks in unit tests and removed modifications on test data as we already have reports with CVSS v3 score data

2021-04-07 11:14 UTC, merged