Grype - Align name and change default dedupe algo
DefectDojo/django-DefectDojo pull request #4264
Opened 2021-04-12 22:05 UTC by madchap

The name was off compared to all other scanners, showing `anchore_grype` instead of `Anchore Grype`.

Also, the dedupe was not working at all. The cve is not a unique ID for any tool. Changed the default dedupe algo to be closer to the ones from anchore-cli.

2021-04-12 22:06 UTC, madchap commented
OK, I am good to revoke my key..

2021-04-13 09:46 UTC, damiencarol commented
@madchap you said
> Also, the dedupe was not working at all. The cve is not a unique ID for any tool. Changed the default dedupe algo to be closer to the ones from anchore-cli.

1) But for this scanner it is. Take a look at the data:

```JSON
{
      "vulnerability": {
        "id": "CVE-2020-36221",
```

Also in the pull request you are remove implementation of `unique_id_from_tool`.

2) CVE is a unique ID in our current model. You can only have one and only one CVE for a Finding.
> The cve is not a unique ID for any tool. 

Strongly disagree with this assertion. CVE *are* uniq IDs. We should be able to de-duplicate between tools with CVEs. 

3) I need to understand better your pb. Did you saw some Ids from the tool that where not CVE ? If it's the pb, you're right there is some modifications needed.

2021-04-13 10:15 UTC, damiencarol requested changes
Putting on hold as there is some discussions around the de-duplication

2021-04-14 09:14 UTC, valentijnscholten approved these changes

2021-04-14 09:21 UTC, valentijnscholten requested changes
I think this will cause a new Test_Type to be created and creating a disconnect between existing tests and new tests for Anchore Grype. i.e. a data migration might be needed.

2021-04-14 09:38 UTC, valentijnscholten commented
In https://github.com/DefectDojo/django-DefectDojo/pull/4182/files#diff-7fb4443091c77732d3a550092087171effe27b6eafaafadaf97110db0789c812R88 the CVE was set as unique_id_from tool for the main anchore scanner

2021-04-29 21:40 UTC, madchap commented
> I think this will cause a new Test_Type to be created and creating a disconnect between existing tests and new tests for Anchore Grype. i.e. a data migration might be needed.

I thought that with @damiencarol 's refactor, this was a thing of the past? Like right now, there is no mention of grype in `test_type.json`.

2021-04-29 21:44 UTC, madchap commented
Adding `vuln_id_from_tool` per discussion in https://owasp.slack.com/archives/C014H3ZV9U6/p1619635577100800

2021-04-30 06:35 UTC, damiencarol commented
@madchap test type is still saved in DB by upper layers. so we need a DB migration for this one.

2021-04-30 17:57 UTC, valentijnscholten approved these changes
first() is fine because name is unique for Test_Type.

2021-05-03 06:15 UTC, damiencarol approved these changes

2021-05-03 06:15 UTC, damiencarol commented on docs/content/en/integrations/import.md
> +-------------
```suggestion
### Anchore Grype
```

2021-05-03 06:16 UTC, damiencarol commented
@madchap approved but the doc have a syntax difference

2021-05-03 06:49 UTC, merged