add new parser - cargo audit
DefectDojo/django-DefectDojo pull request #4531
Opened 2021-05-20 07:04 UTC by ansidorov

Audit Cargo.lock files for crates with security vulnerabilities reported to the RustSec Advisory Database.

It could be found at: https://crates.io/crates/cargo-audit

Resolve #4521

2021-05-20 17:02 UTC, valentijnscholten approved these changes
Can you check if we need to set dedupe algorithm to HASH_CODE in settings? And if we need a hash code field config or can use the default? (Might be good to check the same for the previous parsers by you which we already merged)

2021-05-20 18:01 UTC, ansidorov commented
> Can you check if we need to set dedupe algorithm to HASH_CODE in settings? And if we need a hash code field config or can use the default? (Might be good to check the same for the previous parsers by you which we already merged)

If I have understood correctly, I have defined a deduplication algorithm for cargo audit.

2021-05-20 18:33 UTC, valentijnscholten commented
Thanks. The downside of using `title` in the hashcode is that any change in the title will result in a new finding being created (and the old one closed depending on the settings). Same for `severity`. Looking at the `id` of the advisory, which is stored in the `vuln_id_from_tool`, this looks pretty unique if combined with `component_name`? You could add `component_version`, but that in that case if the component is updated to a new version, but still has the vulnerability, again you will get a new finding. 
There are other parsers using `component_version`, but we may review those in the future. What do you think?

2021-05-21 08:42 UTC, ansidorov commented
> Same for severity. Looking at the id of the advisory, which is stored in the vuln_id_from_tool, this looks pretty unique if combined with component_name? You could add component_version, but that in that case if the component is updated to a new version, but still has the vulnerability, again you will get a new finding.

Yes, I'm pretty sure it should for reasons like this:
- severity might change if the criticality score was initially low, but if someone produces a new exploit that changes the exploitation path, the criticality of that problem might increase.
- In my opinion, if the developer has updated the package, but the vulnerability is still there, then it is a new flaw that needs a separate task and should be handled differently. For example in the first case he just needs to update the dependency, in the second case he has to replace the library which uses the vulnerability and which cannot work with the new version of the dependency.

> The downside of using title in the hashcode is that any change in the title will result in a new finding being created (and the old one closed depending on the settings)

I'll remove the `title'. Thank you

2021-05-21 10:04 UTC, damiencarol requested changes
It's almost good. I just made some comment about the attribute `url`
You can remove this attribute. This attribute is not used in the UI, it could be removed in the future release.

2021-05-21 10:04 UTC, damiencarol commented on dojo/tools/cargo_audit/parser.py
> +                        url=url,
```suggestion
```
You can remove this attribute. This attribute is not used in the UI, it could be removed in the future.

2021-05-21 10:25 UTC, ansidorov commented on dojo/unittests/tools/test_cargo_audit_parser.py
> +            self.assertEqual("https://github.com/servo/rust-smallvec/issues/252", finding.url)
Done. Add URL to description

2021-05-21 11:58 UTC, ansidorov commented
> It's almost good. I just made some comment about the attribute `url`
> You can remove this attribute. This attribute is not used in the UI, it could be removed in the future release.

Done

2021-05-22 23:19 UTC, mtesauro commented
@damiencarol LGTM but wanted to let you review the most recent changes since you made comments recently

2021-05-23 13:23 UTC, damiencarol approved these changes

2021-05-23 13:29 UTC, damiencarol commented
@mtesauro reviewed and accepted as it's good as-is.

@ansidorov I think you have a pretty good one now. You could improve it by supporting more features, like the tags.
I saw one attribute `keyword` that is a good candidate for tags:
```JSON
...
         "keywords": [
            "http",
            "request-smuggling"
          ],
...
```

2021-05-23 13:55 UTC, ansidorov commented
> @mtesauro reviewed and accepted as it's good as-is.
> 
> @ansidorov I think you have a pretty good one now. You could improve it by supporting more features, like the tags.
> I saw one attribute `keyword` that is a good candidate for tags:
> 
> ```json
> ...
>          "keywords": [
>             "http",
>             "request-smuggling"
>           ],
> ...
> ```

Done

2021-05-23 15:56 UTC, merged

2021-05-24 22:52 UTC, damiencarol commented
Awesome work @ansidorov . The final result is good.

2021-07-23 10:37 UTC, zakrush commented
@ansidorov do you can modify parser? You should add this:
```
                if len(advisory.get('aliases')) != 0:
                    cve = advisory.get('aliases')[0]
                else:
                    cve = None
```
instead 33 line. I describe here is problem. For my instance it resolve problem.

2021-07-23 11:19 UTC, zakrush commented
Created new pull request: https://github.com/DefectDojo/django-DefectDojo/pull/4858

2021-07-23 12:59 UTC, zakrush commented
@ansidorov 
Why you did CargoAudit as Dynamic type? it's static type. 
Also, I see that you don't parse the package name, and resolve patch version. 
Here is uploaded finding: 
![image](https://user-images.githubusercontent.com/33844164/126784820-3bbdc24d-8165-4166-8fba-1a8ebe862b86.png)
From this reviewer can't understand what package is vulnerable, and how to patch it. It's not good case.