Added Nessus WAS Scanner
DefectDojo/django-DefectDojo pull request #4548
Opened 2021-05-21 21:51 UTC by blakeaowens

Added Nessus WAS scanner which accepts .csv and .nessus/.xml reports.

2021-05-22 03:39 UTC, damiencarol requested changes

2021-05-22 03:39 UTC, damiencarol commented on dojo/tools/nessus_was/__init__.py
> +__author__ = 'Blake Owens'
```suggestion
```
We rely on the VCS to track authorship.

2021-05-22 03:54 UTC, damiencarol commented on dojo/tools/nessus_was/parser.py
> +                               'formatted using the NessusClientData_v2 schema.')
```suggestion
            raise ValueError('This version of Nessus report is not supported. Please make sure the export is '
                               'formatted using the NessusClientData_v2 schema.')
```

2021-05-24 18:22 UTC, devGregA approved these changes

2021-05-24 22:57 UTC, damiencarol approved these changes

2021-05-24 22:57 UTC, merged