feat: added GitLab container scanning report parser
DefectDojo/django-DefectDojo pull request #4594
Opened 2021-06-02 05:05 UTC by natebwangsut

Adding GitLab container

- https://docs.gitlab.com/ee/user/application_security/container_scanning

2021-06-03 10:49 UTC, natebwangsut commented
@madchap @damiencarol

2021-06-04 06:58 UTC, damiencarol requested changes

2021-06-04 06:58 UTC, damiencarol commented on dojo/tools/gitlab_container_scan/parser.py
> +                    find.description += "\n" + finding.description
You could use the syntax `"\n\n-----\n\n" it produces horizontal lines.

2021-06-04 07:55 UTC, natebwangsut commented
@damiencarol I've commited the changes per your request, please let me know if you've got anything to add

2021-06-04 08:16 UTC, damiencarol requested changes

2021-06-04 08:16 UTC, damiencarol commented on dojo/tools/gitlab_container_scan/parser.py
> +                )
For this kind of shortening task, you can use `textwrap.shorten` see https://docs.python.org/3/library/textwrap.html#textwrap.shorten

2021-06-04 08:16 UTC, damiencarol commented on dojo/tools/gitlab_container_scan/parser.py
> +                        cwe = id["value"]
move this block to line 68, it will be clearer to read.

2021-06-04 09:25 UTC, natebwangsut commented
I've update the code per formatting

2021-06-06 16:14 UTC, Maffooch approved these changes

2021-06-24 05:29 UTC, natebwangsut commented
@damiencarol should I apply `unique_id_from_tool` here as well ?

2021-06-24 21:01 UTC, damiencarol commented
@natebwangsut yes for this parser.

2021-06-28 11:47 UTC, natebwangsut commented
@Maffooch @damiencarol I've added unique ID for parsing + rebased ontop of latest dev as well, kindly review the PR

2021-06-28 21:59 UTC, damiencarol approved these changes

2021-06-28 22:00 UTC, merged