APIv2: Add missing methods + tests
DefectDojo/django-DefectDojo pull request #4637
Opened 2021-06-09 21:08 UTC by kiblik

2021-06-11 18:35 UTC, valentijnscholten requested changes

2021-06-11 18:35 UTC, valentijnscholten commented on dojo/unittests/test_apiv2_methods.py
> +from drf_yasg.openapi import Info
could you change it to use https://github.com/tfranzel/drf-spectacular introduced in https://github.com/DefectDojo/django-DefectDojo/pull/4541 as drf-yasg will be deprecated in 2.0.0

2021-06-13 13:19 UTC, kiblik commented
@valentijnscholten, I hope using `get_open_api3_json_schema` is enough

2021-06-26 08:41 UTC, valentijnscholten approved these changes

2021-06-26 08:42 UTC, merged

2021-06-26 14:08 UTC, kiblik commented
Late merge broke new things (like https://github.com/DefectDojo/django-DefectDojo/pull/4711#issuecomment-869002126)

Fixed in #4721