added CSV support for Qualys Scan and added updated related documenta…
DefectDojo/django-DefectDojo pull request #4648
Opened 2021-06-11 15:12 UTC by 37b

added CSV support for Qualys Scan and added updated related documentation

2021-06-12 08:30 UTC, damiencarol commented on docs/content/en/integrations/import.md
> +###IntSights Report
```suggestion
### IntSights Report
```

2021-06-12 08:39 UTC, damiencarol requested changes

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +    severity_lookup = {'1': 'Informational', '2': 'Low', '3': 'Medium', '4': 'High', '5': 'Critical'}
```suggestion
    severity_lookup = {'1': 'Info', '2': 'Low', '3': 'Medium', '4': 'High', '5': 'Critical'}
```
`Informationnal` is not a possible value

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +            severity=severity_lookup.get(report_finding['Severity'], 'Informational'),
```suggestion
            severity=severity_lookup.get(report_finding['Severity'], 'Info'),
```
`Informational` is not a valid value

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +            finding.mitigated = datetime.strptime(report_finding['Date Last Fixed'], "%m/%d/%Y %H:%M:%S").date()
```suggestion
            finding.mitigated = datetime.strptime(report_finding['Date Last Fixed'], "%m/%d/%Y %H:%M:%S")
```
I think you can keep the original value, let the upper layers convert it.

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +            date=datetime.strptime(report_finding['Last Detected'], "%m/%d/%Y %H:%M:%S").date(),
```suggestion
            date=datetime.strptime(report_finding['Last Detected'], "%m/%d/%Y %H:%M:%S"),
```
Let's keep the original value

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +    return report_findings
It seems that the method exists only to get ride of the header. But we don't want that.
We want that the parser detect and use header line and is able to read the good column even if there is more column or the order of columns is different.

2021-06-12 08:39 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +                    'Associated Tags']
Why forcing the name of columns?

2021-06-29 13:04 UTC, 37b commented on dojo/tools/qualys/csv_parser.py
> +    return report_findings
The CSV files generated by Qualys have an unknown (variable) number of lines of metadata before the CSV values begin. These include summary information, address, date the report was generated, etc. Since this is unusable and not part of the CSV itself I was removing it. Are you saying there's a better way?

Here is an example:

```
"ReportNameGoesHere - 20210608 - 20210608","06/08/2021 at 16:35:49 (GMT+0000)"
"Company Name Goes Here","1234 Fake St",,"Oxford","California","United States of America","90210"
"Chris Fort","chrisfortusername","RoleName"

"IP","Network","DNS","NetBIOS","Tracking Method","OS","IP Status","QID","Title","Vuln Status","Type","Severity","Port","Protocol","FQDN","SSL","First Detected","Last Detected","Times Detected","Date Last Fixed","First Reopened","Last Reopened","Times Reopened","CVE ID","Vendor Reference","Bugtraq ID","CVSS3","CVSS3 Base","CVSS3 Temporal","Threat","Impact","Solution","Exploitability","Associated Malware","Results","PCI Vuln","Ticket State","Instance","OS CPE","Category","Associated Tags"
"1.1.1.1","Global Default Network","machine.dns.name.net","HOSTNAME123","QAGENT","Windows Server 2016 Standard 64 bit Edition Version 1607","host scanned, found vuln","105837","EOL/Obsolete Software: Microsoft SQL Server 2016 Service Pack 1 (SP1) Detected","Active","Vuln","5",,,,,"03/29/2021 23:53:05","06/08/2021 10:46:39","367",,,,,,,,"9.1","10.0 (AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H)","9.1 (E:U/RL:U/RC:C)","Microsoft SQL Server is a data management system that delivers a fixed set of features, data protection, and performance for embedded applications, lightweight Web Sites and applications, and local data stores.
.....
```

2021-06-29 20:12 UTC, damiencarol commented on dojo/tools/qualys/csv_parser.py
> +    return report_findings
Ok, didn't know that Qualys reports were not really CSV.
Good to know. I will change my review.

2021-08-31 15:00 UTC, damiencarol requested changes

2021-09-10 03:35 UTC, Maffooch requested changes

2021-09-10 03:35 UTC, Maffooch commented on dojo/fixtures/initial_surveys.json
> +      "polymorphic_ctype": 77
Please remove changes to this file

2022-04-27 22:26 UTC, closed without merging