Update how-to-write-a-parser.md to include advice for CVSS data
DefectDojo/django-DefectDojo pull request #4685
Opened 2021-06-19 09:27 UTC by damiencarol

* explain what to do
* talk about `cvss` module
* explain how we use `cvss` module

2021-06-19 09:29 UTC, valentijnscholten commented on docs/content/en/contributing/how-to-write-a-parser.md
> +### Do not parser CVSS by hand (vector, score or severity)
```suggestion
### Do not parse CVSS by hand (vector, score or severity)
```

2021-06-19 09:29 UTC, valentijnscholten commented on docs/content/en/contributing/how-to-write-a-parser.md
> +Data can have `CVSS` vectors or scores. Don't try to right again your own CVSS score algorythm.
```suggestion
Data can have `CVSS` vectors or scores. Don't try to write your own CVSS score algorithm.
```

2021-06-19 09:29 UTC, valentijnscholten commented on docs/content/en/contributing/how-to-write-a-parser.md
> +For parser, we rely in module `cvss`.
```suggestion
For parser, we rely on module `cvss`.
```

2021-06-19 09:30 UTC, valentijnscholten requested changes
made suggestions on typo's

2021-06-19 17:24 UTC, damiencarol commented
@valentijnscholten committed your suggestions.

2021-06-19 17:47 UTC, valentijnscholten approved these changes

2021-06-20 12:38 UTC, madchap approved these changes

2021-06-20 12:38 UTC, merged