Add Rate Limiting to Login Page
DefectDojo/django-DefectDojo pull request #4784
Opened 2021-07-07 08:22 UTC by Maffooch

Dependent on #4783

Add the ability to rate limit the login page. 

Uses https://github.com/jsocol/django-ratelimit

2021-07-07 08:28 UTC, valentijnscholten commented
Did you look into if / how this would work if you have multiple django containers/pods or when using multiple uwsgi processes? I think we need to explain in the docs what works and doesn't work.

2021-07-07 08:31 UTC, Maffooch commented
Didn't know that was even possible. How can I go about setting up an environment to test that?

2021-07-07 08:36 UTC, valentijnscholten commented
The docker compose in release mode already has 2 processes: https://github.com/valentijnscholten/django-DefectDojo/blob/d30234cba2278b73848c8f1f85362a0adbd24c21/docker/entrypoint-uwsgi.sh#L36
I _think_ the default cache used by the ratelimiter is not cross-process, typically people use some external cache like memcached or redis for that.

2021-07-08 02:58 UTC, Maffooch commented
It appears to block requests on a per process basis (guessing based on the 500 followed by 2 200's)
<img width="820" alt="image" src="https://user-images.githubusercontent.com/46459665/124854060-7f4ac280-df6c-11eb-8e90-20cc2adc7c29.png">

Here is what the documentation has to say about caching
```
After activating django-ratelimit, you should ensure that your cache backend is setup to be both persistent and work across multiple deployment worker instances (for instance UWSGI workers). Read more in the Django docs on caching.
```

Does dojo use any sort of caching method out of the box?

2021-07-08 07:18 UTC, valentijnscholten commented
No, it only uses the `default` cache, which is in memory and local to a process/worker. That's also the reason why we can't easily add query caching for example or other forms of global caching. If we were to switch to `redis` as default celery broker, we could also use `redis` as a cross worker/process cache. I think for it's best to just make the limitation very clear in our docs.
Maybe something could be achieved by doing sticky sessions in `nginx`.

2021-07-08 17:57 UTC, valentijnscholten requested changes

2021-07-08 17:57 UTC, valentijnscholten commented on docs/content/en/integrations/rate_limiting.md
> +#### Multi-Process Behvaior
```suggestion
#### Multi-Process Behavior
```

2021-07-13 00:38 UTC, devGregA approved these changes

2021-07-13 00:41 UTC, mtesauro approved these changes
Approved.

2021-07-13 02:53 UTC, merged