Enable import history by default
DefectDojo/django-DefectDojo pull request #4794
Opened 2021-07-09 17:57 UTC by valentijnscholten

Was implemented 3-4 months ago, got some bugfixes so should be good to enable by default now.

2021-07-09 18:57 UTC, damiencarol requested changes
your base seems not up-to-date

2021-07-09 20:26 UTC, valentijnscholten commented
yeah I messed up, fixed now @damiencarol

2021-07-09 22:11 UTC, Maffooch approved these changes

2021-07-10 05:27 UTC, damiencarol approved these changes

2021-07-10 05:27 UTC, merged