add new parser - Mobsfscan
DefectDojo/django-DefectDojo pull request #4845
Opened 2021-07-20 14:58 UTC by ansidorov

mobsfscan is a static analysis tool that can find insecure code patterns in your Android and iOS source code. Supports Java, Kotlin, Swift, and Objective C Code. 

It could be found at: https://github.com/MobSF/mobsfscan

2021-07-20 20:16 UTC, Maffooch submitted a review, later dismissed
Is this different from 

https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/tools/mobsf

2021-07-20 20:32 UTC, ansidorov commented
> Is this different from
> 
> https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/tools/mobsf

Yes, mobsf (https://github.com/MobSF/Mobile-Security-Framework-MobSF) more complex tool with different features.

2021-07-20 20:47 UTC, Maffooch reviewed
@damiencarol this one looks good to me, do you agree?

2021-07-20 21:57 UTC, damiencarol commented
@Maffooch wait, I want to confirm that it's the new scanner of MOBSF

2021-07-20 21:58 UTC, damiencarol requested changes
Want to take time to review this one

2021-07-26 11:14 UTC, damiencarol requested changes

2021-07-26 11:14 UTC, damiencarol commented on dojo/unittests/tools/test_mobsfscan_parser.py
> +            self.assertEqual('200', finding.cwe)
```suggestion
            self.assertEqual(200, finding.cwe)
```
cwe attribute is an integer in the current model.

2021-07-26 11:15 UTC, damiencarol commented
@ansidorov found a minor thing.

2021-07-26 11:39 UTC, ansidorov commented
> @ansidorov found a minor thing.

Fixed

2021-07-26 15:00 UTC, damiencarol approved these changes

2021-07-26 15:01 UTC, damiencarol commented
> 
> 
> @damiencarol this one looks good to me, do you agree?

Yes, made a minor comment but it's ok for me.

2021-07-29 21:38 UTC, Maffooch approved these changes

2021-07-29 21:38 UTC, merged