AWS Prowler Scan parser FIX, Upgrade and Enhancements
DefectDojo/django-DefectDojo pull request #4876
Opened 2021-07-27 13:32 UTC by dkade

PR was approved but it was against the incorrect branch, now against `dev` .

Same as: [#4851](https://github.com/DefectDojo/django-DefectDojo/pull/4851)

2021-07-28 09:35 UTC, damiencarol approved these changes

2021-07-29 04:59 UTC, StefanFl requested changes
You have started your branch based on the `master` branch instead of the `dev` branch. This is why there are files in the PR you haven't changed. If you rebase your branch against `dev`, the problems should be gone.

2021-07-29 08:38 UTC, dkade commented
Yeah makes sense. Let me fix this.

2021-08-06 05:37 UTC, StefanFl commented
Hi @dkade, have you done a rebase against dev? There are still changes in `README.md` in your PR that don't belong there.

2021-08-06 07:42 UTC, closed without merging