Feature/veracode pipeline import
DefectDojo/django-DefectDojo pull request #5044
Opened 2021-09-06 18:43 UTC by jpbowie

Added import for Veracode Pipeline JSON file output.
Found an example of the result file for testing here:
https://github.com/veracode/veracode-pipeline-scan-results-to-sarif/blob/master/test_resource/resultsToSarif.json

2021-09-07 08:22 UTC, damiencarol requested changes
As Veracode pipeline support SARIF format conversion, it will be better to leverage the existing SARIF parser.

https://github.com/veracode/veracode-pipeline-scan-results-to-sarif#output-results-sarif

```
- name: Convert pipeline scan output to SARIF format
  id: convert
  uses: Veracode/veracode-pipeline-scan-results-to-sarif@v0.1.2
  with:
    pipeline-results-json: results.json
    output-results-sarif: veracode-results.sarif
    source-base-path-1: "^com/veracode:src/main/java/com/veracode"
    source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
    finding-rule-level: "3:1:0"
```

2021-09-08 00:46 UTC, jpbowie commented
The SARIF conversion support is only for a specific Github action provided by Veracode.  There isn't native SARIF support from the Pipeline Scanner.

2021-09-08 11:00 UTC, damiencarol commented
As explained in my previous comment andnaccording to the Veracode documentation, the best way to do scan is to use the Veracode tools and actions (see https://help.veracode.com/r/Github_Pipeline_Scan_Examples):

```YAML
name: pipeline-scan

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: gradle clean build
  pipeline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - name: Run Pipeline Scanner
        run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "example.jar" --fail_on_severity="Very High, High"

```

This steps will produce a JSON file that you can convert in SARIF format with a specific Github action maintained by the Veracode team.

```YAML
...
- name: Convert pipeline scan output to SARIF format
  id: convert
  uses: Veracode/veracode-pipeline-scan-results-to-sarif@v0.1.2
  with:
    pipeline-results-json: results.json
    output-results-sarif: veracode-results.sarif
    source-base-path-1: "^com/veracode:src/main/java/com/veracode"
    source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
    finding-rule-level: "3:1:0"

- name: upload sarif file to repository
  uses: github/codeql-action/upload-sarif@v1
  with: # Path to SARIF file relative to the root of the repository
    sarif_file: veracode-results.sarif
```
Ref here : https://github.com/veracode/veracode-pipeline-scan-results-to-sarif#output-results-sarif

It's better to use the tools and actions created and maintained by Veracode team instead of creating new code maintained by us.

PS: You can also customize the name of the output file with this option:
```
  -jf JSON_OUTPUT_FILE, --json_output_file JSON_OUTPUT_FILE
                         Filename (in the current directory) to save results JSON. (default: results.json)
 ```

2021-09-10 01:32 UTC, Maffooch commented
I agree with @damiencarol here. Maybe a good compromise could be to add a subsection to the [SARIF parser in the docs](https://defectdojo.github.io/django-DefectDojo/integrations/import/#sarif) outlining which tools (just Veracode pipeline for now) are compatible and can be used with dojo?

2021-09-13 17:25 UTC, valentijnscholten commented
What if you run the Veracode pipeline elsewhere, not in GitHub. i.e. manually, from their saas product or in gitlab. I think the sarif converter is only available as a GitHub action is what @jpbowie states?

2021-09-13 23:44 UTC, jpbowie commented
That was my understanding from the documentation, it is a GitHub Action.  If you are not using GitHub, you'll need to find another solution to convert the native pipeline scanner JSON output to SARIF.

2021-09-14 17:44 UTC, damiencarol requested changes

2021-09-14 17:44 UTC, damiencarol commented on dojo/tools/veracode_pipeline/parser.py
> +            return
Generate a `ValueError` and create a unit tests that check that

2021-09-14 17:44 UTC, damiencarol commented on dojo/tools/veracode_pipeline/parser.py
> +            return
```suggestion
```
It will silently swallow an error (filename is never null for this parser)

2021-09-14 17:44 UTC, damiencarol commented on dojo/tools/veracode_pipeline/parser.py
> +        finding.impact = ''
```suggestion
```
Better no data instead of fake broken ones. These attributes are not mandatory.

2021-09-14 17:44 UTC, damiencarol commented on dojo/tools/veracode_pipeline/parser.py
> +        finding.mitigated = None
```suggestion
```
Same comment

2021-09-14 17:44 UTC, damiencarol commented on dojo/unittests/tools/test_veracode_pipeline_parser.py
> +        self.assertEqual('different_filename', finding.sourcefile)
Most of the parsers use `file_path` and `sast_source_file_path`
`sourcefilepath` is deprecated.

2021-09-14 17:44 UTC, damiencarol commented on dojo/tools/veracode_pipeline/parser.py
> +            finding.hash_code = flaw['flaw_match']['flaw_hash']
Parser never set `hash_code`. it is an internal attribute that is managed entirely outside of the parser code.
You must not set it.
if your value `flaw['flaw_match']['flaw_hash']` is some kind of identifier, you should consider using `vuln_id_from_tool` and/or `unique_id_from_tool`

2021-09-14 17:46 UTC, damiencarol commented
> What if you run the Veracode pipeline elsewhere, not in GitHub. i.e. manually, from their saas product or in gitlab. I think the sarif converter is only available as a GitHub action is what @jpbowie states?

Ok. Yes you're right.

@jpbowie  Is it your use case? If so yes this parser will only be useful for you. Please take also into account that we already have another parser dedicated to the more common Veracode tool (not the pipeline)

2021-10-08 01:58 UTC, Maffooch commented
@jpbowie what are your thoughts on this?

2022-01-10 12:17 UTC, damiencarol commented
@jpbowie any progress on this one?

2022-01-11 01:51 UTC, jpbowie commented
Is there something specific I should be working on?

2022-01-11 16:13 UTC, damiencarol commented
@jpbowie don't you see my feedback on your PR? Do you want to close it?

2022-04-27 22:26 UTC, closed without merging