APIv2: Allow to set the first password when the user is created through API
DefectDojo/django-DefectDojo pull request #5224
Opened 2021-10-05 19:10 UTC by kiblik

Allow to set the first password when the user is created through API

2021-10-05 20:02 UTC, valentijnscholten requested changes
I think this will expose all users passwords via the API, can you make it a write_only field and add a testcase that verifies the password (or its hash) is not exposed?

2021-10-05 22:17 UTC, kiblik commented
> I think this will expose all users passwords via the API, can you make it a write_only field and add a testcase that verifies the password (or its hash) is not exposed?

it was "write_only" from the beginning so it works correctly. I'm happy to add more tests.

2021-10-06 08:09 UTC, valentijnscholten commented
> it was "write_only" from the beginning so it works correctly. I'm happy to add more tests.

Oh, missed that. The test I was looking for is to make sure the password is not returned when retrieving users, thanks for that.

2021-10-29 19:06 UTC, valentijnscholten approved these changes

2021-10-30 05:45 UTC, StefanFl approved these changes

2021-10-30 05:47 UTC, merged