Add support for files in generic parser
DefectDojo/django-DefectDojo pull request #5508
Opened 2021-11-26 19:30 UTC by damiencarol

2021-11-26 19:37 UTC, valentijnscholten commented
Any thoughts on what happens with lots of (big) files?

2021-11-26 20:03 UTC, damiencarol commented
@valentijnscholten no idea. I only touched the generic parser. 🤔 
is it only in this PR?

2021-11-26 20:13 UTC, valentijnscholten commented
I think this is the first parser doin it, or at least unsaved_files is new loading all files in memory. Not easy to avoid with our current parser contact, just wondering what would happen if somebody uploads 500M of screenshots.

2021-11-26 20:15 UTC, damiencarol commented
oh. I see.
I thing today we limit to 3 files.
And most of the screenshots I saw used by InfoSec teams where PNG or BMP of few hundreds bytes.

2021-11-26 20:29 UTC, StefanFl commented
Please adjust the example in https://defectdojo.github.io/django-DefectDojo/integrations/import/#generic-findings-import, so that we have a documentation.

Do we have an overall limit for the size of a file to upload?

2021-11-26 20:39 UTC, damiencarol commented
mmhh I think it will be the limit of the size of the report. Django limit the upload anyway.
I don't think more checks are needed in the parser or (re)importer

2021-11-28 07:57 UTC, valentijnscholten commented
Some docs would be nice, otherwise good to go.

2021-12-02 08:07 UTC, StefanFl requested changes

2021-12-02 08:07 UTC, StefanFl commented on docs/content/en/integrations/import.md
> +Ex:
```suggestion
Example:
```

2021-12-02 08:07 UTC, StefanFl commented on docs/content/en/integrations/import.md
> +    "title": "My wonderfull report",
```suggestion
    "title": "My wonderful report",
```

2021-12-02 08:07 UTC, StefanFl commented on docs/content/en/integrations/import.md
> +This parser support an attributes that accept files as Base64 strings. These files will be created as `UploadFile`
Where does the term `UploadFile` come from? In the UI they are referenced as "Files". 

Suggestion:

```suggestion
This parser support an attributes that accept files as Base64 strings. These files are attached to the respective findings.
```

2021-12-02 15:13 UTC, mtesauro commented
I know @Maffooch updated/re-vamped file uploads a while ago (maybe a year ago) - just wondering if this uses the same location & process to save the files.

One of the clean-up things Cody did was to unify how files were saved.  Prior to that, uploaded finding images were stored differently than threat model uploads so it would be good to avoid introducing a new file saving mechanism as part of this PR.

2021-12-02 16:14 UTC, damiencarol commented
@mtesauro I used the new data structure

2021-12-02 16:20 UTC, StefanFl approved these changes

2021-12-04 05:24 UTC, Maffooch approved these changes
Cool feature

2021-12-05 08:08 UTC, merged