Give readers the permission to add notes
DefectDojo/django-DefectDojo pull request #5593
Opened 2021-12-12 09:26 UTC by StefanFl

solves #5581

There is no harm in letting users with a `Reader` role adding notes. Includes a missing permission check, which doesn't change a lot because a user need a `Reader` role anyway to call this view method. Nevertheless it shall be there for completeness.

2021-12-12 10:39 UTC, valentijnscholten commented
Small update to the docs needed?

2021-12-12 12:11 UTC, StefanFl commented
> Small update to the docs needed?

True, done. And thanks for your changes.

2021-12-12 17:40 UTC, valentijnscholten requested changes
the suggestion might be more accurate?

2021-12-12 17:40 UTC, valentijnscholten commented on docs/content/en/usage/permissions.md
>  | Delete Note                 |        | (x) <sup>2)</sub> | x          | x     |              |
```suggestion
| Edit Note                   | (x) <sup>2)</sub>       | x      | x          | x     |              |
| Delete Note                 | (x) <sup>2)</sub>       | (x) <sup>2)</sub> | x          | x     |              |
```

2021-12-12 17:50 UTC, StefanFl commented on docs/content/en/usage/permissions.md
>  | Delete Note                 |        | (x) <sup>2)</sub> | x          | x     |              |
Well spotted, done

2021-12-29 10:31 UTC, valentijnscholten approved these changes

2021-12-29 23:20 UTC, devGregA approved these changes

2021-12-30 05:49 UTC, merged