Support version 8 of gitleaks
DefectDojo/django-DefectDojo pull request #5625
Opened 2021-12-20 17:49 UTC by StefanFl

As @SPoint42 mentioned on Slack (https://owasp.slack.com/archives/C014H3ZV9U6/p1638360087060900), gitleaks changed its JSON format in version 8. With this PR the parser supports both the old and the new format.

2021-12-20 21:29 UTC, mtesauro approved these changes
Nice to support both formats!

Approved.

2021-12-20 23:44 UTC, damiencarol requested changes

2021-12-20 23:44 UTC, damiencarol commented on dojo/tools/gitleaks/parser.py
> +                raise Exception('Format is not recognized for Trufflehog3')
`Trufflehog3` seems wrong.

2021-12-21 05:35 UTC, StefanFl commented on dojo/tools/gitleaks/parser.py
> +                raise Exception('Format is not recognized for Trufflehog3')
Classical copy and paste error, fixed.

2021-12-22 11:44 UTC, damiencarol approved these changes

2021-12-22 11:44 UTC, merged