added asynchronous deletion for engagements, tests, and products.
DefectDojo/django-DefectDojo pull request #5744
Opened 2022-01-14 02:51 UTC by nobletrout

This can take a long time to process depending on database size and
scoping and this makes it much less painless with the tradeoff that you
might see data disappear over time. Ideally a "pending deletion" flag
would be set in the top level engagement, product, or test..

2022-01-14 08:35 UTC, valentijnscholten commented on dojo/engagement/views.py
> +                else:
Will this work if the checkbox is not ticked? I remember unticked checkboxes not being sent?
Probably a message should still be added saying the deletion was succesfully queued?
Please update the unit tests to reflect these changes.

2022-01-14 08:35 UTC, valentijnscholten requested changes
see comments

2022-01-14 15:12 UTC, Maffooch commented
I love this idea, but I wonder if making this a System Setting would be better. My biggest gripe with the delete page is how long the GET request takes to render with larger datasets. Waiting to click the async button until after the page is full rendered does not save the user much time.

2022-01-14 15:21 UTC, valentijnscholten commented
And the api would need to support async deletes too.

2022-01-14 16:20 UTC, nobletrout commented
I can work on that. The get taking forever is also my biggest gripe but I
was going to see what this reception was like first.

How about two system settings:
1. No dangerzone
2. Asynchronous deletes default ?

I’d like to have a “I know what I am doing here and I don’t want you tell
me about all the findings related to things just delete the stuff please
thank you”


On Fri, Jan 14, 2022 at 10:21 AM valentijnscholten ***@***.***>
wrote:

> And the api would need to support async deletes too.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DefectDojo/django-DefectDojo/pull/5744#issuecomment-1013218557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD6TYSCCTQQ7RAGXVLNCDCDUWA5P3ANCNFSM5L5S63QQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-18 03:56 UTC, nobletrout commented
making some notes:

It appears I'm not the only person and this is not the only project that suffers from this issue:

https://code.djangoproject.com/ticket/10919

Looks like Django is now supporting something called ASGI or planning it? I'm not a django expert
https://docs.djangoproject.com/en/4.0/howto/deployment/asgi/

2022-01-19 18:26 UTC, Maffooch commented
Im nervous about the no danger zone setting. A simple misclick could totally ruin somebodies day. Another approach that would could incorporate the async delete would be to display the danger zone, but do not query the DB for the objects that are about to be deleted. That would allow for a fast danger zone, and scheduled delete that could take a while.

I have no idea if that is possible, but could be worth exploring

2022-01-19 19:15 UTC, valentijnscholten commented
> Looks like Django is now supporting something called ASGI or planning it? I'm not a django expert https://docs.djangoproject.com/en/4.0/howto/deployment/asgi/

That is about non-blocking IO which is not the same as doing something async.

> Another approach that would could incorporate the async delete would be to display the danger zone, but do not query the DB for the objects that are about to be deleted. That would allow for a fast danger zone, and scheduled delete that could take a while.

The danger zone could be 2 steps. 

1) Display the danger zone page with only text. Two buttons: a) display related items to be deleted b) yolo, just delete all the things
2) optional page which displays the related items similar to what we have currently -> confirm -> delete all the things

2022-01-19 20:26 UTC, mtesauro commented
I think @valentijnscholten 's 2 step approach is the best I've seen so far on this thread.  Allows for confirmation and YOLO if you want or details if that's more your thing.

2022-01-23 13:33 UTC, damiencarol commented
I agree. Sometime you really want to delete a product and everything behind (when you test, etc...) and sometime you really want to see what ill be deleted.
Maybe we could just give hint like the number of objects that the confirmation will delete.

Like `"You will destroy 56798 object(s), do you confirm this action?"` is not the same as `"You will destroy 2 object(s), do you confirm this action?"` :D

2022-01-28 04:06 UTC, nobletrout commented
Hey guys, I tried to get the integration/unit tests working on this PR. But I'm getting unrelated failures (first something about a JIRA check failing and now test_login). Can someone please help me figure out a fast track to running unit tests?
Thanks

2022-02-01 14:42 UTC, Maffooch commented
Here are some docs on running the unit tests https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#run-the-tests-with-docker

2022-05-03 18:05 UTC, closed without merging

2022-05-03 18:06 UTC, nobletrout commented
It appears that #6183 duplicates this effort and has been merged in. woohoo!