Don't show 'all alerts' and 'clear all alerts' when no notification found
DefectDojo/django-DefectDojo pull request #5898
Opened 2022-02-10 15:22 UTC by shipko

It's strange that in the absence of alerts, we suggest looking at all the alerts or clearing them. 

I suggest showing a big message instead

2022-02-12 08:03 UTC, valentijnscholten requested changes
see above

2022-02-12 14:06 UTC, shipko commented
No problem :)

2022-02-14 07:28 UTC, StefanFl commented
I like the idea, thank you @shipko. One thing: Wouldn't it look better, if you make the font for **No alerts found** the same as for the other message, so `<strong>` instead of `<h3>`?

2022-02-15 00:51 UTC, Maffooch commented
Good suggestion from Stefan ^

2022-02-16 09:01 UTC, shipko commented
This is a two different variant: 
With using <strong>
![image](https://user-images.githubusercontent.com/1519243/154230120-c4772f83-13a9-4830-bc6a-310d57b2a57f.png)

With using <h3>
![image](https://user-images.githubusercontent.com/1519243/154230185-dead2e70-d868-48a2-a083-8834ff12a5f3.png)

@StefanFl @Maffooch I think it would be better using <h3>. It's just nicely

2022-02-16 09:07 UTC, StefanFl commented
I still like the first one with `<strong>` more. Then all font sizes are the same on the start page.

2022-02-16 11:33 UTC, StefanFl approved these changes

2022-02-16 20:23 UTC, mtesauro approved these changes
Approved

2022-02-16 20:25 UTC, mtesauro commented
@valentijnscholten We good with your requested change?

2022-02-16 20:26 UTC, valentijnscholten approved these changes

2022-02-16 20:27 UTC, merged