[FIX] Issues on disconnection and connection using OAuth
DefectDojo/django-DefectDojo pull request #6066
Opened 2022-03-23 14:01 UTC by X0x1RG9f

Fix two issues:
    - When disconnecting using OAuth and "SHOW_LOGIN_FORM = False", as return URL is not /login and does not contains next parameter, an error 500 is trigerred.
    - When connecing using OAuth and "SHOW_LOGIN_FORM = False", message "You have logged out" is displayed after logging in.

2022-04-03 21:12 UTC, dsever commented
@X0x1RG9f  how to test it, to trigger error, can be it replicated using SAML auth?

2022-07-27 09:00 UTC, X0x1RG9f commented
> @X0x1RG9f how to test it, to trigger error, can be it replicated using SAML auth?

I don't know if it can be replicated with SAML. Test is easy, activating the two parameters in my first post. SOCIAL AUTH (I used Gsuite) and "SHOW_LOGIN_FORM = False". Then, when you are logged in and try to logout, you will trigger a 500 error.

2022-07-27 22:15 UTC, dsever commented
> > @X0x1RG9f how to test it, to trigger error, can be it replicated using SAML auth?
> 
> @dsever I don't know if it can be replicated with SAML. Test is easy, activating the two parameters in my first post. SOCIAL AUTH (I used Gsuite) and "SHOW_LOGIN_FORM = False". Then, when you are logged in and try to logout, you will trigger a 500 error.

Ok, I will give a try.

2022-08-19 09:34 UTC, damiencarol requested changes

2022-08-19 09:34 UTC, damiencarol commented on dojo/finding/views.py
> +                                url=request.build_absolute_uri(reverse('finding_copy', args=(finding_copy.unsaved_vulnerability_ids, ))),
`unsaved_vulnerability_ids` is an array that don't have finding id. I don't think this will work

2022-08-19 09:38 UTC, damiencarol approved these changes

2022-09-30 18:27 UTC, devGregA commented
@X0x1RG9f  thank you for the PR. Looks good. Will merge after the release for further testing.

2022-10-25 20:05 UTC, merged