Typo fix on migrate_staff_users
DefectDojo/django-DefectDojo pull request #6072
Opened 2022-03-23 15:30 UTC by TheocharisPetros

Currently there is a typo in the documentation while the migrate_staff_users is the script that needs to be executed, the underscore was missing in the current documentation.

2022-03-23 18:55 UTC, StefanFl commented
Closing and reopening to make checks run again

2022-03-23 19:16 UTC, StefanFl approved these changes
Thanks for the PR @TheocharisPetros

2022-03-23 19:43 UTC, StefanFl requested changes
Please rebase your PR against the `dev` branch. It shall not be merged into `master`

2022-03-24 00:01 UTC, TheocharisPetros commented
Done https://github.com/DefectDojo/django-DefectDojo/pull/6074

2022-03-24 05:43 UTC, StefanFl commented
Superseded by #6074

2022-03-24 05:43 UTC, closed without merging