Update settings.dist.py
DefectDojo/django-DefectDojo pull request #6093
Opened 2022-03-29 09:49 UTC by italvi

Make SSO over SAML2 possible (#6092)

2022-03-29 10:50 UTC, dsever requested changes
Please take a look at my comment

2022-03-29 10:50 UTC, dsever commented on dojo/settings/settings.dist.py
> +                'force_authn': env('DD_SAML2_FORCE_AUTH'),
Do not use env variables directly, config should support config py files as well 

Please take a look:

https://github.com/italvi/django-DefectDojo/blob/patch-1/dojo/settings/settings.dist.py#L826

2022-03-29 15:45 UTC, dsever commented on dojo/settings/settings.dist.py
> +                'force_authn': env('DD_SAML2_FORCE_AUTH'),
Actually this is my mistake :/ can you fix this as well?

2022-03-30 04:25 UTC, StefanFl approved these changes
Hi @italvi, thank you for your contribution, lgtm

2022-04-01 10:47 UTC, dsever approved these changes
Looks ok

2022-04-01 14:44 UTC, merged

2022-04-06 12:01 UTC, nobletrout commented
Is this a breaking change for existing SAML logins?

2022-04-06 12:37 UTC, dsever commented
@nobletrout  do you have some issues after the upgrade?

2022-04-06 12:49 UTC, nobletrout commented
No I haven't upgraded yet was reading release notes and raising a concern

2022-04-06 12:55 UTC, italvi commented
The default value is still True, therefore it should not have any impact on existing SAML Logins.