Parser/jfrog xray api summary artifact
DefectDojo/django-DefectDojo pull request #6181
Opened 2022-04-25 14:09 UTC by madeoninfo

2022-04-25 17:24 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    cves = vulnerability.get('cves', [])
you can now set multiple identifiers in the vulnerability references relation

2022-04-25 17:24 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        cve=cve,
I think 'No CVE' can end up here which is an invalid value

2022-04-25 17:25 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        verified=False,
this field should not be set by a parser

2022-04-25 17:25 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        hash_code=impact_path.sha,
this field should not be set by a parser

2022-04-25 17:25 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    unique_id_from_tool = title
do not set this field if there is no unique value in the actual report

2022-04-25 17:27 UTC, valentijnscholten requested changes
thanks for the PR, left some comments

2022-04-26 07:21 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    cves = vulnerability.get('cves', [])
Hi, not sure what you mean by this comment.

2022-04-26 07:22 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    unique_id_from_tool = title
Replaced with the sha for the uniqueness of the title. Is there a limit though on the length of the title?

2022-04-26 07:22 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        hash_code=impact_path.sha,
Removed

2022-04-26 07:23 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        verified=False,
Removed

2022-04-26 07:23 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        cve=cve,
Initialization of cve chenged from "No CVE" to "none"

2022-04-26 07:59 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    unique_id_from_tool = title
check models.py

2022-04-26 08:01 UTC, valentijnscholten commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    cves = vulnerability.get('cves', [])
You can add all CVEs from the report to the `vulnerability_reference_set` field of a Finding, check https://github.com/DefectDojo/django-DefectDojo/pull/5904

2022-04-26 13:40 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    cves = vulnerability.get('cves', [])
Having deployment issues at this point so I can't test this on my machine. Added a question on the [defectdojo slack channel](https://owasp.slack.com/archives/C2P5BA8MN/p1650980167639499). Could we complete this PR and I will create another one once I'm up and running again?

2022-04-27 06:03 UTC, damiencarol requested changes

2022-04-27 06:03 UTC, damiencarol commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    if len(cves) > 0:
```suggestion
    if cves:
```

2022-04-27 06:03 UTC, damiencarol commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +    cvss_v3 = "No CVSS v3 score"
```suggestion
```

2022-04-27 06:03 UTC, damiencarol commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +            cvssv3_score = CVSS3.from_rh_vector(cvss_v3).base_score
```suggestion
```
This is automatic, parser should focus on the vector if present.

2022-04-27 11:56 UTC, damiencarol commented
@madeoninfo pushing a first build but the comment of @valentijnscholten is still valid. if you can please leverage the new vulne reference attribute.

2022-04-28 07:37 UTC, madeoninfo commented
Hi @damiencarol and @valentijnscholten. I'm still having issues with DefectDojo on Windows with Docker Desktop. Got a 500 error with an empty database, even though the initializer has completed its task. I am setting up a new dev environment on Linux as Docker Desktop might be the culprit with this. I promise to supply an update on the comments and also include more parsers related to JFrog from the API that they provide.

2022-04-29 06:40 UTC, madeoninfo commented
Hi @damiencarol, without a setup localy it is difficult to test and I am relying on the unittests of the PR to verify the functionality. Could you please run them to make sure I have not broken anything?

2022-05-02 12:11 UTC, damiencarol requested changes
You have 2 times the parser defined. (see __init__.py)

2022-05-02 13:41 UTC, madeoninfo commented
> You have 2 times the parser defined. (see **init**.py)

Could you please point this out in the code?

2022-05-02 17:40 UTC, damiencarol commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        cvssv3_score=cvssv3_score,
```suggestion
```
The score is automatically calculated. Better to not set it if the tool doesn't have the data

2022-05-03 10:34 UTC, madeoninfo commented on dojo/tools/jfrog_xray_api_summary_artifact/parser.py
> +        cvssv3_score=cvssv3_score,
Removed

2022-05-03 15:37 UTC, madeoninfo commented
Making a few changes to the unique_id_from_tool and will push soon

2022-05-04 13:26 UTC, damiencarol approved these changes

2022-05-06 05:02 UTC, Maffooch approved these changes

2022-05-06 06:44 UTC, merged