Issue 6230 Fix: Snyk parser cannot handle Nonetype CVSSv3 / cvssScore
DefectDojo/django-DefectDojo pull request #6240
Opened 2022-05-03 17:31 UTC by P440Boyd

I'm unable to determine the best alternative (None or empty string) for the fields, but Severity can be pulled from the tool's assessment should a Nonetype be present. 

CVSSv3 vector is a little more complex.

2022-05-04 08:58 UTC, damiencarol requested changes

2022-05-04 08:58 UTC, damiencarol commented on dojo/tools/snyk/parser.py
>          if 'CVSSv3' in vulnerability:
Better to have this version:
```Python
if vulnerability.get("CVSSv3"):
```

2022-05-04 15:39 UTC, damiencarol reviewed
[@P](https://github.com/P440Boyd) there is files that should not be in the PR :/

2022-05-04 15:51 UTC, P440Boyd commented
> [@P](https://github.com/P440Boyd) there is files that should not be in the PR :/

Bah, which files? I amended parser.py, test_snyk...py and added some testdata JSON. Which file is added that shouldn't be there? First time here so may be a mistake.

2022-05-05 10:24 UTC, damiencarol commented
these modifications shouldn't be here 
![image](https://user-images.githubusercontent.com/1694940/166905265-68936feb-a57e-4473-84ec-cbb6d92abd26.png)

2022-05-05 10:55 UTC, P440Boyd commented
> these modifications shouldn't be here ![image](https://user-images.githubusercontent.com/1694940/166905265-68936feb-a57e-4473-84ec-cbb6d92abd26.png)

Bah - Absolutely agreed. I didn't change them manually, any idea why they'd be there from GitHub? I must have done something not quite right in the fork process.

2022-05-05 12:07 UTC, damiencarol commented
come from the merge. just revert this modifications

2022-05-06 06:40 UTC, damiencarol approved these changes

2022-05-06 08:00 UTC, P440Boyd commented
Thanks for fixing the modifications. Wasn't around yesterday. Noticed unittest was seeking 3 findings after modification, but the test scan I pushed only contains 1. That should resolve unittests.

2022-05-06 09:02 UTC, damiencarol commented
Happy to help, it should be fine now.

2022-05-07 22:53 UTC, Maffooch approved these changes

2022-05-07 22:54 UTC, merged