Qualys scan csv
DefectDojo/django-DefectDojo pull request #6282
Opened 2022-05-10 20:46 UTC by 37b

Finally updated Qualys Scan CSV importer to read CVSS from existing values (though the data has to be massaged a little first.

Also included a minor fix for #6274

2022-05-11 13:23 UTC, 37b commented
Fixing those tests >.<

2022-05-11 16:25 UTC, damiencarol approved these changes

2022-05-12 07:07 UTC, StefanFl requested changes

2022-05-12 07:07 UTC, StefanFl commented on dojo/fixtures/initial_surveys.json
> +      "polymorphic_ctype": 77
Are the changes in this file related to the PR? If not, the changes should be reverted.

2022-05-16 08:52 UTC, StefanFl requested changes
There are a lot of formatting changes in this PR. I can't see if there are any other changes hidden in these files. The PR should only contain changes that are necessary. Please revert all other changes. This might close the problems with flake8 as well.

2022-05-16 12:34 UTC, 37b commented
> There are a lot of formatting changes in this PR. I can't see if there are any other changes hidden in these files. The PR should only contain changes that are necessary. Please revert all other changes. This might close the problems with flake8 as well.

I saw that - sorry about that. I have been using autopep8 with personal projects and I think some wires got crossed.

2022-05-16 15:02 UTC, StefanFl requested changes

2022-05-16 15:02 UTC, StefanFl commented on dojo/tools/qualys/csv_parser.py
> +def get_references(cve_list):
There is a new mechanism for vulnerability ids like CVEs or GHSA's. You can fill them in a list called finding.unsaved_vulnerability_ids. They will all be showed in the UI and will all be clickable to show the content. I would prefer using this than building your own set of references.

2022-05-16 15:02 UTC, StefanFl commented on unittests/tools/test_qualys_parser.py
> +                self.assertEqual(
Why do you check the severity 2 times?

2022-05-18 05:58 UTC, StefanFl approved these changes

2022-05-18 05:58 UTC, merged