Add fixes to bugcrowd parser and endpoint uri util
DefectDojo/django-DefectDojo pull request #6321
Opened 2022-05-20 23:40 UTC by Maffooch

2022-05-21 20:14 UTC, damiencarol requested changes

2022-05-21 20:14 UTC, damiencarol commented on dojo/tools/bugcrowd/parser.py
> +            finding.severity = self.convert_severity(int(priority))
Better to have this logic moved in the `convert_severity` method

2022-05-26 07:49 UTC, kiblik commented
It is not a bug. It is a future. ;)

The original implementation was trying to follow the standard of URI. Please check https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax
It is the reason, why the function is called `from_uri`.

If your parser returns endpoints like `foo.bar:123`, please add `//` in front, as it is used in:
https://github.com/DefectDojo/django-DefectDojo/blob/d55fb295e3eae8167af320c545445b2098422737/unittests/test_endpoint_model.py#L46
https://github.com/DefectDojo/django-DefectDojo/blob/d55fb295e3eae8167af320c545445b2098422737/dojo/tools/generic/parser.py#L56-L61
https://github.com/DefectDojo/django-DefectDojo/blob/d55fb295e3eae8167af320c545445b2098422737/dojo/tools/nuclei/parser.py#L37-L40
https://github.com/DefectDojo/django-DefectDojo/blob/d55fb295e3eae8167af320c545445b2098422737/dojo/tools/openscap/parser.py#L96-L104
https://github.com/DefectDojo/django-DefectDojo/blob/d55fb295e3eae8167af320c545445b2098422737/dojo/tools/sslscan/parser.py#L68-L74

2022-05-27 00:03 UTC, Maffooch commented
Ooh learn something every day! Thanks @kiblik :)

2022-05-28 09:24 UTC, damiencarol approved these changes

2022-05-31 02:38 UTC, devGregA approved these changes

2022-05-31 02:39 UTC, merged