Set the finding date for Acunetix360 from FirstSeenDate
DefectDojo/django-DefectDojo pull request #6460
Opened 2022-06-24 08:50 UTC by coheigea

On an import from Acunetix360 the finding date is set to the import date rather than from FirstSeenDate in the report

2022-06-24 16:27 UTC, StefanFl approved these changes

2022-06-26 07:29 UTC, damiencarol requested changes

2022-06-26 07:29 UTC, damiencarol commented on dojo/tools/acunetix360/parser.py
> +            if item["FirstSeenDate"] is not None:
```suggestion
            if item.get("FirstSeenDate"):
```

2022-06-27 06:36 UTC, coheigea commented on dojo/tools/acunetix360/parser.py
> +            if item["FirstSeenDate"] is not None:
Fixed @damiencarol

2022-06-30 16:29 UTC, coheigea commented
Please review again @damiencarol

2022-07-05 13:48 UTC, Maffooch approved these changes

2022-07-05 15:16 UTC, damiencarol commented on dojo/tools/acunetix360/parser.py
> +            if item["FirstSeenDate"]:
```suggestion
            if item.get("FirstSeenDate"):
```

2022-07-14 15:09 UTC, Maffooch commented
@damiencarol are you good with this one?

2022-07-20 04:49 UTC, merged

2022-07-25 16:57 UTC, damiencarol commented
@coheigea sorry for the delay, days off  :D . **all good for me, this is a nice patch**