Parse CWE/CVSS3 from Nuclei classification
DefectDojo/django-DefectDojo pull request #6482
Opened 2022-06-29 07:18 UTC by coheigea

The Nuclei parser is not parsing the classification dictionary, and so is missing CWE/CVSS3 score etc.

2022-07-01 17:58 UTC, StefanFl requested changes

2022-07-01 17:58 UTC, StefanFl commented on unittests/tools/test_nuclei_parser.py
> +            self.assertEqual(5.3, finding.cvssv3_score)
Please add a test/assert for the vulnerability id.

2022-07-04 07:47 UTC, damiencarol submitted a review, later dismissed

2022-07-04 07:47 UTC, damiencarol commented on unittests/tools/test_nuclei_parser.py
> +            self.assertEqual('cve-2018-15473', vulnerability_ids[0])
This should be in uppercase.

2022-07-04 07:49 UTC, StefanFl requested changes

2022-07-04 07:49 UTC, StefanFl commented on unittests/tools/test_nuclei_parser.py
> +            self.assertEqual('cve-2018-15473', vulnerability_ids[0])
`cve` should be in uppercase, e.g.  `CVE-2018-15473`, otherwise the link in the UI might not work.

2022-07-04 08:50 UTC, StefanFl approved these changes

2022-07-05 14:47 UTC, merged