Add sast/sca/dast tags to Veracode findings
DefectDojo/django-DefectDojo pull request #6487
Opened 2022-06-30 07:08 UTC by coheigea

When importing findings from Veracode, it's hard to tell whether findings are SCA/SAST/DAST, so adding a tag will make it easier to both see and search for issues matching a particular type.

2022-07-01 17:53 UTC, StefanFl requested changes

2022-07-01 17:53 UTC, StefanFl commented on dojo/tools/veracode/parser.py
> +        finding.tags = ["sast"]
```suggestion
        finding.unsaved_tags = ["sast"]
```

You have to store the tag in `unsaved_tags`, they will be written to the database after the finding has been saved.

2022-07-01 17:53 UTC, StefanFl commented on dojo/tools/veracode/parser.py
> +        finding.tags = ["sca"]
```suggestion
        finding.unsaved_tags = ["sca"]
```

2022-07-04 07:12 UTC, StefanFl approved these changes

2022-07-04 07:44 UTC, damiencarol requested changes

2022-07-04 07:44 UTC, damiencarol commented on unittests/tools/test_veracode_parser.py
> +        self.assertEqual(['sast'], finding.unsaved_tags)
Please use the method `assertIn(...)`

2022-07-04 07:57 UTC, damiencarol approved these changes

2022-07-04 08:58 UTC, merged