Fix parser horusec
DefectDojo/django-DefectDojo pull request #6492
Opened 2022-07-01 17:11 UTC by srburton

**I'm doing this update because when trying to import a report from Horusec you get the following error:**

![WhatsApp Image 2022-07-01 at 14 06 30](https://user-images.githubusercontent.com/15394508/176939520-196fac6d-54d3-420b-8035-7f1a81db6385.jpeg)

**I noticed that the reports of the new version of Horusec the "line" comes empty where it ends up breaking the parser of the integer:**

![WhatsApp Image 2022-07-01 at 14 09 19](https://user-images.githubusercontent.com/15394508/176939850-c2260327-850b-4a9a-88c9-f0dda72c1150.jpeg)

![Screenshot_2](https://user-images.githubusercontent.com/15394508/176940069-c3f247bf-2c7f-4018-9391-928364ff4c3c.png)

2022-07-01 18:12 UTC, renatosazup approved these changes

2022-07-01 22:57 UTC, Maffooch approved these changes

2022-07-01 22:59 UTC, Maffooch requested changes
Just noticed the tests were failing. Please fix those

2022-07-14 22:04 UTC, closed without merging

2022-07-14 22:06 UTC, srburton commented
I opened a new PR: https://github.com/DefectDojo/django-DefectDojo/pull/6563