Add the ability to the UI to delete engagements from the engagement tab
DefectDojo/django-DefectDojo pull request #6514
Opened 2022-07-05 07:41 UTC by coheigea

The products and findings tabs have three vertical dots that allow you to edit/delete/etc., however these are missing from the engagements tab. So if you go to "All Engagements" for example you can't delete an engagement.

This PR adds the three vertical dots for "All Engagements", "Active Engagements" and "Engagements by Product"

2022-07-13 06:17 UTC, StefanFl requested changes
The menus behave differently from the others in DefectDojo. When there are only a few datasets, the menu is within the list and not completely visible:
![2022-07-13 08_14_15-Active Engagements _ DefectDojo](https://user-images.githubusercontent.com/2698502/178663713-ddc99047-cf90-4e89-b952-2a02cfe20078.png)

It should be like for example the products:
![2022-07-13 08_14_35-Product List _ DefectDojo](https://user-images.githubusercontent.com/2698502/178663802-2ff6af68-4839-4db2-90bb-3f10635fb201.png)

2022-08-15 14:05 UTC, coheigea commented
Yeah I tried and failed to find a way to display it outside of the list

2022-09-30 18:46 UTC, devGregA commented
@blakeaowens is going to try to fix the zindex issue.

2022-10-26 02:27 UTC, blakeaowens commented on dojo/templates/dojo/engagement.html
> +                                        <div class="dropdown">
```suggestion
                                        <div class="dropdown" style="position: fixed!important;">
```

2022-10-26 02:28 UTC, blakeaowens commented on dojo/templates/dojo/engagement.html
> +                                            <ul class="dropdown-menu">
```suggestion
                                            <ul class="dropdown-menu" style="position: unset!important;">
```

2022-10-26 02:29 UTC, blakeaowens commented on dojo/templates/dojo/engagements_all.html
> +                                            <div class="dropdown">
```suggestion
                                            <div class="dropdown" style="position: fixed!important;">
```

2022-10-26 02:29 UTC, blakeaowens commented on dojo/templates/dojo/engagements_all.html
> +                                                <ul class="dropdown-menu">
```suggestion
                                                <ul class="dropdown-menu"  style="position: unset!important;">
```

2022-10-26 02:31 UTC, blakeaowens requested changes
<img width="653" alt="Screen Shot 2022-10-25 at 9 31 02 PM" src="https://user-images.githubusercontent.com/76979297/197920523-d059cd77-f119-4983-9d53-c2a660644657.png">

While it is not identical to other places in DefectDojo, this seems to do the trick.

2022-10-26 11:13 UTC, coheigea commented
There's still a bug in active engagements, this time if you scroll down the page the 3 dots remain in situ:

<img width="764" alt="Screenshot 2022-10-26 at 12 13 15" src="https://user-images.githubusercontent.com/472162/198012110-8e70fde0-51a4-49bf-a943-f1e47befff9b.png">

2022-10-26 19:18 UTC, damiencarol commented
@coheigea if this PR is still in progress, you can mark it as a draft.

2022-10-26 23:14 UTC, blakeaowens commented
> There's still a bug in active engagements, this time if you scroll down the page the 3 dots remain in situ:
> 
> <img alt="Screenshot 2022-10-26 at 12 13 15" width="764" src="https://user-images.githubusercontent.com/472162/198012110-8e70fde0-51a4-49bf-a943-f1e47befff9b.png">

2022-10-26 23:14 UTC, blakeaowens commented
@coheigea I will have another look later this evening.

2022-10-28 03:27 UTC, blakeaowens commented on dojo/templates/dojo/engagement.html
> +                                        <div class="dropdown" style="position: fixed!important;">
```suggestion
                                        <div class="dropdown">
```

2022-10-28 03:27 UTC, blakeaowens commented on dojo/templates/dojo/engagement.html
> +                                            <ul class="dropdown-menu" style="position: unset!important;">
```suggestion
                                            <ul class="dropdown-menu">
```

2022-10-28 03:38 UTC, blakeaowens commented
![engagements-dropdowns](https://user-images.githubusercontent.com/76979297/198496905-035eb734-9f2b-485c-a256-0cad7b07bb82.gif)

2022-10-29 10:39 UTC, coheigea commented
LGTM thanks @blakeaowens

2022-10-31 05:23 UTC, blakeaowens approved these changes

2022-10-31 22:27 UTC, merged