Update parser of DependencyTrack
DefectDojo/django-DefectDojo pull request #6515
Opened 2022-07-05 11:37 UTC by italvi

As cve was replaced by vuln_id the filtering for cves from NVD is unnecessary

2022-07-05 14:47 UTC, damiencarol approved these changes

2022-07-05 14:55 UTC, StefanFl requested changes

2022-07-05 14:55 UTC, StefanFl commented on unittests/tools/test_dependency_track_parser.py
> +        self.assertEqual('533', findings[0].unsaved_vulnerability_ids[0])
The vulnerability id is defined as "An id of a vulnerability in a security advisory associated with this finding. Can be a Common Vulnerabilities and Exposures (CVE) or from other sources." These examples are just numbers that don't fit to this definition.

2022-07-05 15:17 UTC, damiencarol commented on unittests/tools/test_dependency_track_parser.py
> +        self.assertEqual('533', findings[0].unsaved_vulnerability_ids[0])
you mean you prefer to build "CWE-{x}" string?

2022-07-05 15:27 UTC, StefanFl commented on unittests/tools/test_dependency_track_parser.py
> +        self.assertEqual('533', findings[0].unsaved_vulnerability_ids[0])
The vulnerability ids don't store CWEs but something like GHSA-57j2-w4cx-62h2 or CVE-2020-36518. They will contain the link to the source in the UI or could be googled.

2022-08-05 08:47 UTC, damiencarol commented on unittests/tools/test_dependency_track_parser.py
> +        self.assertEqual('533', findings[0].unsaved_vulnerability_ids[0])
so we completly remove CWE from this field?

2022-10-10 19:05 UTC, Maffooch commented
@italvi apologies for the lull on this one. I agree with Stefan's point that putting in just the number does not actually do much in this case. The vulnerability ID field requires some sort of identifier to build a hyperlink with (for example CVE or GHSA)

In my test instance I manually set the vuln id to `NPM-533` and it displays the value in plain text because a hyperlink could not be created. I tried to find what this link would look like, but could not figure out were `NPM-533` is supposed to be pointing. 

The only way we could go forward with this PR is to make the dep tracker parser take the `NPM` and `533` parts into the vulnerability ID field. 

![image](https://user-images.githubusercontent.com/46459665/194935552-72c674c8-a89d-4406-bc3c-09ee54183442.png)

2022-10-11 05:33 UTC, italvi commented
@Maffooch as every NPM Advisory is stored in Github Advisories and therefore we also find a reference in the vulnerability to the GHSA, maybe it would be useful to check in the References (see in the image below) for such a link and then take the ID from there? Would I need just the last part, e.g. GHSA-qh73-qc3p-rjv2?
![image](https://user-images.githubusercontent.com/58322186/195004693-6889d52f-7df3-48c9-9ceb-bbb7d84a6a6a.png)

2022-10-26 03:14 UTC, Maffooch commented
@italvi Sorry for the delayed response. I was on vacation for a bit. 

Yes I like your idea of searching the references for potential vulnerability IDs. Would be nice to capture the NVD and GHSA through regex or somethingg

2022-11-19 21:39 UTC, closed without merging