Change deduplication logic for Veracode SCA to include library name a…
DefectDojo/django-DefectDojo pull request #6537
Opened 2022-07-11 07:11 UTC by coheigea

…nd version

A proposed fix for https://github.com/DefectDojo/django-DefectDojo/issues/6252

2022-07-11 20:17 UTC, StefanFl requested changes

2022-07-11 20:17 UTC, StefanFl commented on dojo/tools/veracode/parser.py
> +        finding.unique_id_from_tool = dupe_key
This is not a good way to use this field. The id here should come directly from the tool and shouldn't be generated. To fix deduplication we should calculate a meaningful hash_code with and use that for deduplication in `settings.dist.py`.

2022-07-11 20:17 UTC, StefanFl commented on unittests/tools/test_veracode_parser_dedup.py
> +    def enable_dedupe(self, enable=True):
You shouldn't change the settings in a unit test, it might have effects on other test cases. There must be better ways to achieve this, maybe with a @patch or a mock.

2022-07-14 13:52 UTC, Maffooch submitted a review, later dismissed

2022-07-18 15:34 UTC, coheigea commented
@StefanFl @Maffooch Thanks for the review - I updated the PR to just generate a random key for the dupes map in the Veracode parser, and removed the unique_id_from_tool to be the CVE id. This means the de-duplication logic falls back to compute_hash_code_legacy for SCA, which solves the problem.

2022-07-19 12:28 UTC, Maffooch approved these changes

2022-07-19 16:01 UTC, mtesauro approved these changes
Approved

2022-07-19 16:09 UTC, merged