Update settings.dist.py
DefectDojo/django-DefectDojo pull request #6623
Opened 2022-07-28 15:41 UTC by sjs6776

Added the requested lines for Blackduck Hub Deduplication #6161

2022-07-30 18:31 UTC, Maffooch approved these changes

2022-07-31 06:01 UTC, StefanFl requested changes

2022-07-31 06:01 UTC, StefanFl commented on dojo/settings/settings.dist.py
> +    'Blackduck Hub Scan': ['title', 'cve', 'component_name'],
`cve` is not allowed as a parameter for deduplication anymore, it has been replaced by `vulnerability_ids`.

When you use `component name` name for deduplication, you should use `component_version` as well.

2022-08-02 18:32 UTC, StefanFl approved these changes

2022-08-05 08:37 UTC, damiencarol approved these changes

2022-08-05 08:37 UTC, merged