Clean Finding Title for pwn_sast Parser
DefectDojo/django-DefectDojo pull request #6652
Opened 2022-08-03 21:52 UTC by ninp0

2022-08-04 01:12 UTC, damiencarol requested changes
Please add a unit test to show the change

2022-08-04 04:10 UTC, ninp0 commented
@damiencarol , can you expand on what you mean to add a unit test to show the change?  I'm wondering what should be added to the unit test that already exists in:
https://github.com/DefectDojo/django-DefectDojo/blob/dev/unittests/tools/test_pwn_sast_parser.py 

I'm not sure what should be added to test the change of the finding title.  Thanks in advance for your help.

2022-08-05 08:32 UTC, damiencarol commented
take a look at the unit tests in `unittests` folder. Some are dedicated to this parser.
I can't help you directly has you restricted access to your branch :/

2022-08-05 14:35 UTC, ninp0 commented
Then would you be open to approving?  I'm the original author of this parser and I simply changed the string value of finding title.  What am I missing?

2022-08-08 09:33 UTC, damiencarol commented
yes, I will approve once it's ready. the pb here is some parts are missing.
1. you are modifying title data, so you need a unit tests that check that.
2. you still have some Flake8 anomaly. you're using tabs but DefectDojo source code requires spaces.

2022-08-08 19:39 UTC, damiencarol requested changes

2022-08-08 19:39 UTC, damiencarol commented on unittests/tools/test_pwn_sast_parser.py
> +      assert findings.title is not None
Test the value please
```suggestion
      self.assertEquals("...", findings.title)
```

2022-08-08 19:40 UTC, damiencarol commented
@ninp0 you really need to configure your tool to be aligned with DD code format.

2022-08-09 17:34 UTC, ninp0 commented
@damiencarol - change introduced...let me know if there's anything else needed.  Thanks.

2022-08-09 18:27 UTC, damiencarol approved these changes

2022-08-09 20:06 UTC, Maffooch approved these changes

2022-08-09 20:06 UTC, merged