Update the text that slack notification shows
DefectDojo/django-DefectDojo pull request #6825
Opened 2022-09-08 20:39 UTC by Ruedaja

Currently, when a test is added and slack notification is enable is showed: "New test added for engagement {engament.product}" 
I suggest adding the engament name to this phrase: " New test added for engagement {{engagement.name }} in product {{ engagement.produc}}"

2022-09-09 07:28 UTC, dsever commented on dojo/templates/notifications/test_added.tpl
> +    New test added for engagement {{engagement.name }} in product {{ engagement.produc}}.
Typo `.produc`

2022-09-09 07:28 UTC, dsever requested changes
Please take a look

2022-09-09 07:33 UTC, Ruedaja commented on dojo/templates/notifications/test_added.tpl
> +    New test added for engagement {{engagement.name }} in product {{ engagement.produc}}.
corrected

2022-09-11 21:02 UTC, Maffooch approved these changes

2022-09-11 23:35 UTC, mtesauro approved these changes
Approved

2022-09-11 23:36 UTC, merged