Update parser.py
DefectDojo/django-DefectDojo pull request #7077
Opened 2022-11-05 02:09 UTC by ncrl

Error, when trying to parse appscreener report. 

[05/Nov/2022 01:41:15] ERROR [dojo.engagement.views:683] invalid literal for int() with base 10: '' Traceback (most recent call last):
  File "/app/./dojo/engagement/views.py", line 668, in import_scan_results
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
  File "/app/./dojo/importers/importer/importer.py", line 298, in import_scan
    parsed_findings = parser.get_findings(scan, test)
  File "/app/./dojo/tools/solar_appscreener/parser.py", line 50, in get_findings
    finding.line = int(finding.line)
ValueError: invalid literal for int() with base 10: ''

Because first line transfer to string after split. This fix should resolve it. I checked - all ok.

2022-11-05 10:12 UTC, damiencarol commented
@ncrl fixed some flake8 errors and improved some stuffs

2022-11-05 20:10 UTC, manuel-sommer requested changes
- Please update the PR name "Update parser.py" to a more descriptive name, e.g. "Fix appscreener parser"
- Please update the target branch from "DefectDojo:master" to "DefectDojo:dev"

2022-11-05 21:29 UTC, ncrl commented
> * Please update the PR name "Update parser.py" to a more descriptive name, e.g. "Fix appscreener parser"
> * Please update the target branch from "DefectDojo:master" to "DefectDojo:dev"

Done!

2022-11-06 14:44 UTC, ncrl commented on dojo/tools/solar_appscreener/parser.py
> +                finding.line = int(finding.line)
I think the error is still there, because after split if '-' will be on input string  got on output.  @damiencarol

2022-11-09 00:15 UTC, Maffooch approved these changes

2022-11-10 11:34 UTC, manuel-sommer approved these changes

2022-11-10 17:32 UTC, mtesauro approved these changes
Approved

2022-11-10 17:32 UTC, merged