Dev salvian dark mode
DefectDojo/django-DefectDojo pull request #7212
Opened 2022-12-01 11:02 UTC by salvianf

This PR add button in navbar that can change to dark mode using inverted filter CSS
resolve #6124. This PR is a continuation of #7155.

2022-12-01 11:04 UTC, salvianf commented
Hi @Gby56 @Maffooch @mtesauro, this is my new PR. Please review it. Thanks.

2022-12-04 08:45 UTC, damiencarol approved these changes

2022-12-05 02:08 UTC, devGregA requested changes
Sorry, will weigh in this shortly.

2023-01-04 13:24 UTC, Gby56 commented on dojo/static/dojo/css/dojo.css
> +        margin: 0 0 0 0;
Why the change in margins ? I didn't run your code locally so I can't really make sense of that, but I thought it was only a css filter so maybe that's not required ?

2023-01-04 13:28 UTC, Gby56 commented on dojo/static/dojo/css/dojo.css
> +        margin: 0 0 0 0;
Update: I realized, it might be to apply the filter properly everywhere ? otherwise you had a white line ?

2023-01-10 09:26 UTC, Gby56 approved these changes

2023-01-15 21:30 UTC, devGregA commented
Hi everyone, sorry for the delay. This PR is hard to accept, because we offer this feature in the [commercial version](https://documentation.defectdojo.com/proprietary_plugins/) of DefectDojo. In our contributing guidelines, we do [recommend reaching out for new features](https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md#submisison-pre-approval) so that people don’t waste effort. I am very open to your feedback on how we can handle this better as I truly don’t want to discourage any member of our community, but the commercial version is what makes the OS version possible.

Please let me know your thoughts and feedback.

2023-01-15 23:22 UTC, Gby56 commented
Hello,

I've been thinking about that feature for a while and couldn't explain to myself how it was not already in the community DefectDojo... now I know haha

I really think these kinds of features are nowadays a bare minimum for accessibility and quality of life improvements, sorry if I'm being a bit blunt... I don't think this should be a commercial-grade feature tbh.

To be fair, the PR is only setting the mode client side and not saving that in user preferences so it's a tiny bit less "fancy", but not by much.

2023-01-16 00:18 UTC, mtesauro commented
FWIW, I don' t really think this is PR-worthy, especially when the UI could use a general overhaul and I'd prefer to spend time on that over adding dark mode to the existing UI.

<matt's 2 cents>
I use this extension to 'dark-ify' many sites that don't include a dark mode and it has generally worked great for me.  TBH, that's a primary reason why I'd not work on a dark mode for DefectDojo's current UI.
https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj/related

Here's what the demo site looks like:
![image](https://user-images.githubusercontent.com/3422419/212575317-f427c967-c5b3-421f-a333-59bbcd05db0a.png)

If that one doesn't work well for you, there's loads of dark mode plugins to try.
<\matt's 2 cents>

2023-01-16 03:06 UTC, devGregA commented
I don't see it as an accessibility feature, but I do see it as quality of life feature. Both when we open sourced Dojo and now, our goal is for Dojo to be a force for good to make security easier and accessible to all. The app, the algorithms, and even the integrations (SSO, JIRA, etc.) all open sourced. We appreciate all contributions and the community that's developed around Dojo. The tool wouldn't be where it is today without the Dojo Community. @Gby56, you have submitted some phenomenal PRs and I truly appreciate your involvement. We've tried to be very careful to make sure there aren't any barriers to a person or organization achieving their goals with the open source version. Where we think it makes sense to draw the line is quality-of-life features and out-of-the-box automation because these features aren't essential for achieving one's goals with Dojo, but provide a means to sustain and improve the platform for both open source and commercial users.

2023-01-16 07:22 UTC, Gby56 commented
I understand your point of view much better, I had the impression that the paid DefectDojo's version was mainly attractive for customers because of the support and the deployment / maintenance taken care of, and also supporting the community, which is also an attractive choice.

But also, now that I think about it, this is a tool that handles sensitive data, and therefore, it will be deployed on-prem most of the time.

This makes it difficult to have a sustainable commercial version, and the licensed on-prem version is the best way to satisfy customer requirements, if they can't be in someone else's cloud.

So, the fine line between a community and a commercial on-prem version is super hard to navigate, because on-prem is the most used deployment model, both having the burden of running and maintenance of the system.

Therefore you really need to at least convince with features, or a cheap licensing that would mostly say "to support the project".

2023-03-02 17:54 UTC, closed without merging