Adding field CVE to GitHub dependendatbot parser
DefectDojo/django-DefectDojo pull request #7392
Opened 2023-01-10 12:42 UTC by ruedaja11

I´ve added the field CVE to the github vulnerability parser because in SCA it is one of the most important field for a vulnerable component

2023-01-10 16:26 UTC, Maffooch commented
Hi @ruedaja11 a couple things to do on this one before it cane be merged

1. Add unit tests. Add a redacted report with the CVE field. This is the file it would need to go into https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/tools/test_github_vulnerability_parser.py
2. Rebase against the bug fix branch so that this change can go into the release on Monday

2023-01-12 10:14 UTC, ruedaja11 commented
Hi @Maffooch Thank you for your feedback. I have added the unitest and I have change the branch against bugfix as you mentioned.

2023-01-12 18:04 UTC, Maffooch commented
```
2023-01-12T17:28:25.6693204Z [36muwsgi_1         |[0m ======================================================================
2023-01-12T17:28:25.6693725Z [36muwsgi_1         |[0m FAIL: test_parse_cve (unittests.tools.test_github_vulnerability_parser.TestGithubVulnerabilityParser.test_parse_cve) (i=0)
2023-01-12T17:28:25.6694068Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-12T17:28:25.6694296Z [36muwsgi_1         |[0m Traceback (most recent call last):
2023-01-12T17:28:25.6694689Z [36muwsgi_1         |[0m   File "/app/unittests/tools/test_github_vulnerability_parser.py", line 256, in test_parse_cve
2023-01-12T17:28:25.6694980Z [36muwsgi_1         |[0m     self.assertEqual(finding.cve, "CVE-2021-42392")
2023-01-12T17:28:25.6695240Z [36muwsgi_1         |[0m AssertionError: None != 'CVE-2021-42392'
2023-01-12T17:28:25.6695389Z [36muwsgi_1         |[0m 
2023-01-12T17:28:25.6695731Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-12T17:28:25.6695948Z [36muwsgi_1         |[0m Ran 2245 tests in 572.622s
2023-01-12T17:28:25.6696096Z [36muwsgi_1         |[0m 
2023-01-12T17:28:25.6696322Z [36muwsgi_1         |[0m FAILED (failures=1, skipped=364)
```

2023-01-12 18:33 UTC, ruedaja11 commented
I think it is solved now! @Maffooch

2023-01-12 19:07 UTC, Maffooch commented
```
2023-01-12T18:56:59.1681095Z [36muwsgi_1         |[0m ======================================================================
2023-01-12T18:56:59.1681698Z [36muwsgi_1         |[0m ERROR: test_parser_cve (unittests.tools.test_github_vulnerability_parser.TestGithubVulnerabilityParser.test_parser_cve) (i=0)
2023-01-12T18:56:59.1682135Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-12T18:56:59.1682464Z [36muwsgi_1         |[0m Traceback (most recent call last):
2023-01-12T18:56:59.1682949Z [36muwsgi_1         |[0m   File "/app/unittests/tools/test_github_vulnerability_parser.py", line 249, in test_parser_cve
2023-01-12T18:56:59.1683394Z [36muwsgi_1         |[0m     self.assertEqual(finding.cve_unsaved_vulnerability_ids[0], "CVE-2021-42392")
2023-01-12T18:56:59.1683737Z [36muwsgi_1         |[0m                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-12T18:56:59.1684187Z [36muwsgi_1         |[0m AttributeError: 'Finding' object has no attribute 'cve_unsaved_vulnerability_ids'
2023-01-12T18:56:59.1684421Z [36muwsgi_1         |[0m 
2023-01-12T18:56:59.1684787Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2023-01-12T18:56:59.1685100Z [36muwsgi_1         |[0m Ran 2246 tests in 581.057s
2023-01-12T18:56:59.1685276Z [36muwsgi_1         |[0m 
2023-01-12T18:56:59.1685511Z [36muwsgi_1         |[0m FAILED (errors=1, skipped=364)
```

Thi might be of help https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#run-the-tests-with-docker-compose

2023-01-13 07:51 UTC, damiencarol approved these changes

2023-01-13 16:12 UTC, Maffooch requested changes
Tests need to be passing before merge

2023-02-08 17:50 UTC, damiencarol requested changes

2023-02-08 17:50 UTC, damiencarol commented on unittests/tools/test_github_vulnerability_parser.py
> +            self.assertEqual(finding.cve_unsaved_vulnerability_ids[0], "CVE-2021-42392")
Please use `self.assertIn(` instead

2023-04-11 18:18 UTC, Maffooch commented
Closing due to inactivity

2023-04-11 18:18 UTC, closed without merging