Add support to AWS Prowler V3 json format
DefectDojo/django-DefectDojo pull request #8028
Opened 2023-04-28 21:17 UTC by anderson-slompo

**Description**
Add support to import aws prowler v3 json scan file referent to this [issue](https://github.com/DefectDojo/django-DefectDojo/issues/7348)

2023-05-02 10:53 UTC, damiencarol requested changes

2023-05-02 10:53 UTC, damiencarol commented on dojo/tools/aws_prowler_v3/__init__.py
> +__author__ = 'Anderson dos Anjos Slompo - https://github.com/anderson-slompo'
```suggestion
```

2023-05-03 15:24 UTC, Maffooch requested changes

2023-05-03 15:24 UTC, Maffooch commented on dojo/tools/aws_prowler_v3/parser.py
> +            mitigation = str(mitigation) + "\n" + str(deserialized.get('Remediation').get('Code'))
Using chained `.get()` can end poorly if the expected field is not found. For example if `Remediation` is not present, the line becomes `str(None.get("Code"))` and would throw an exception. Please update all other references of `.get()` chains
```suggestion
            mitigation = str(mitigation) + "\n" + str(deserialized.get('Remediation', {}).get('Code', ''))
```

2023-05-03 15:24 UTC, Maffooch commented on dojo/tools/aws_prowler_v3/parser.py
> +                    unique_id_from_tool=unique_id_from_tool,
Use this to update the deduplication settings
https://documentation.defectdojo.com/contributing/how-to-write-a-parser/#deduplication-algorithm

2023-05-03 19:13 UTC, anderson-slompo commented
@Maffooch can you validate deduplication settings ?

2023-05-05 21:54 UTC, Maffooch approved these changes

2023-05-06 21:41 UTC, mtesauro approved these changes
Approved

2023-05-09 19:57 UTC, Maffooch requested changes

2023-05-09 19:57 UTC, Maffooch commented on dojo/settings/settings.dist.py
> +    'AWS Prowler V3': ['severity', 'component_name', 'unique_id_from_tool'],
Adding `unique_id_from_tool` to the hash code fields will remove the possibility of having deduplication across tools. Please either remove it or replace it with another field
```suggestion
    'AWS Prowler V3': ['severity', 'component_name'],
```

2023-05-11 18:48 UTC, Maffooch submitted a review, later dismissed

2023-05-15 18:26 UTC, Maffooch approved these changes
Approved for real this time!

2023-05-16 16:23 UTC, devGregA approved these changes

2023-05-16 16:36 UTC, cneill approved these changes

2023-05-16 16:40 UTC, mtesauro commented
@damiencarol Are you good with this?

2023-05-18 20:37 UTC, mtesauro commented
@damiencarol Are you OK with this?

2023-05-21 01:39 UTC, merged

2023-06-05 16:10 UTC, finventario commented
Thanks a lot guys!