Adding pre-commit library to update code with PEP8 standards
DefectDojo/django-DefectDojo pull request #8053
Opened 2023-05-03 21:55 UTC by ajtortolero

Be informative
Add a mechanism to update code with PEP8 standars using tool [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks)

Feature Description
This feature include 6 hooks to help developers for identifying simple issues formatting with standars PEP8 before submission to code review.

Additional context
In some cases developers will require manual intervention in formating code, but this tool help to reconize what files require this intervention.

Form example
In project root folder run following command

pre-commit run --files dojo/tools/anchore_grype/*

Result of this process would be something like following

check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check json...........................................(no files to check)Skipped
python tests naming..................................(no files to check)Skipped
don't commit to branch...................................................Passed
black....................................................................Failed

hook id: black
files were modified by this hook
reformatted dojo/tools/anchore_grype/parser.py

All done! ✨ 🍰 ✨
1 file reformatted, 1 file left unchanged.

autopep8.................................................................Passed
bandit...................................................................Passed
autoflake................................................................Passed
flake8...................................................................Failed

hook id: flake8
exit code: 1
dojo/tools/anchore_grype/parser.py:21:121: E501 line too long (122 > 120 characters)

The output is indicating that the dojo/tools/anchore_grype/parser.py file has more than 120 characters on line 21.

This file was not modified by flake8 and requires manual intervention to comply with PEP8 standards.

2023-05-04 16:19 UTC, Maffooch requested changes
No actions here yet until there is a decision made for #8043

2023-05-04 16:19 UTC, Maffooch commented on .pre-commit-config.yaml
> +          - --max-line-length=79
Why is the line length here and in Black conflicting with the 120 char limit set by Flake8?

2023-05-04 17:02 UTC, ajtortolero commented on .pre-commit-config.yaml
> +          - --max-line-length=120
@Maffooch You suggest change this properties to 120?

2023-05-04 20:32 UTC, ajtortolero reviewed
Update in https://github.com/DefectDojo/django-DefectDojo/pull/8053/commits/92c5d27f8caac66b4e474b6b3b2032daec45af8a

2023-05-04 20:38 UTC, Maffooch commented on .pre-commit-config.yaml
> +          - --max-line-length=120
Just to clarify, there could be instances where the pre commit hooks will fail on some lines for pep8 and black, but not flake 8?

For example, let's say I have a line that is 100 characters. Would the pre commit hook fail  for pep8 and black,  but pass for flake8? That sounds confusing for developers trying to contribute

2023-05-04 20:49 UTC, ajtortolero commented on .pre-commit-config.yaml
> +          - --max-line-length=120
In this case, It's just to clarify that both have to have the same configuration. In this case set both to 120 characters.

2023-05-04 20:51 UTC, ajtortolero commented on .pre-commit-config.yaml
> +          - --max-line-length=120
@Maffooch It's just to clarify that both hooks should have the same configuration. In this case, set both to 120 characters.

2023-05-05 15:39 UTC, Maffooch commented on .pre-commit-config.yaml
> +          - --max-line-length=120
Black needs to be updated as well to 120 so that are not inconsistencies between standards

2023-05-05 15:44 UTC, ajtortolero commented on .pre-commit-config.yaml
> +          - --max-line-length=120
@Maffooch Ok, the update to black was commited.

2023-05-05 21:51 UTC, Maffooch commented
Dropping this comment here for the sake visibility:

> @renejal I think we are on the same page now. I think the course of action should be as follows
> - Close https://github.com/DefectDojo/django-DefectDojo/pull/8013
> - Update the code base one by one to be in compliance with Black, Pep8, and Flake8
> - Once the code base is in compliance, add the pre commit hooks and update the unit tests to ensure the code base stays in compliance.

2023-10-11 04:34 UTC, closed without merging

2023-10-11 04:34 UTC, Maffooch commented
Closing due to stale