nuclei parser and unittests improvements
DefectDojo/django-DefectDojo pull request #8057
Opened 2023-05-04 21:19 UTC by kir-b

**Description**

This PR improves Nuclei parser.

- Adds import more details from Nuclei finding, i.e. tags, request, response, curl-command, extracted-results, etc.;
- Adds a host and matcher check when merging similar Nuclei findings to one defectdojo finding

**Test results**

Unit tests have been revised and extended.

**Documentation**

No need to make changes to the documentation.

**Checklist**

This checklist is for your information.

- [x] Make sure to rebase your PR against the very latest `dev`.
- [x] Features/Changes should be submitted against the `dev`.
- [x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [x] Your code is flake8 compliant.
- [x] Your code is python 3.11 compliant.
- [x] Add applicable tests to the unit tests.
- [ ] Add the proper label to categorize your PR.

2023-05-05 21:50 UTC, Maffooch commented
@kir-b this looks more like a rewrite than an improvement. Unit test scan files look pretty different as well. Did the format of the nuclei report change? If so, is it possible to maintain both versions?

2023-05-05 22:03 UTC, damiencarol commented
@Maffooch to do what you're asking (supporting multiple version of the report) we need to not touch the old reports, exactly what this PR is doing :D 

@kir-b can you change this PR **to not touch old reports and add new ones**.

2023-05-05 22:04 UTC, damiencarol requested changes
This is a good PR that add the missing configuration part for de-duplication but you must not touch old reports.
Please create new unit tests and add new report instead of modifying old ones by hand.

2023-05-06 08:39 UTC, kir-b commented
@Maffooch Yes, parser has changed a lot. Recent versions of Nuclei produce a slightly different reports than scan examples in unittest. But parser support both versions, I have tested. I also combined the results of all versions into one file (unittests/scans/nuclei/many_findings.json), but not everything that was before.
@damiencarol I can change this PR to not touch old reports and add new ones. But in this case, I still have to change the unit tests for the old reports. The reason is that I [added additional `matcher` and `endpoint.host` keys](https://github.com/DefectDojo/django-DefectDojo/pull/8057/files#diff-45bf85c6f622b3d6a0301a654876b334925d4a1e89be29443141ba1d0762e0b4R128) when merging multiple Nuclei finds into a single DefectDojo find. This is necessary because the current parser merges too many results into one finding and some of the information may be lost. This way I can revert old scans, add new ones, and rewrite old and new unit tests. Is it ok?

2023-05-07 10:14 UTC, hvechtomov commented
I can confirm that the problem exists with new version of Nuclei #8060

2023-05-11 14:34 UTC, hvechtomov commented
@damiencarol @Maffooch re-check please. This issue is quite critical, due to `nuclei` popularity. Thanks

2023-05-11 14:36 UTC, Maffooch commented
@kir-b please make changes requested by @damiencarol

2023-05-12 20:24 UTC, kir-b commented
@Maffooch @damiencarol Done. Please review.

2023-05-13 00:18 UTC, Maffooch requested changes
Looking a lot better! Few nitpicky things

2023-05-13 00:18 UTC, Maffooch commented on dojo/tools/nuclei/parser.py
> +            if item.get('templateID'):
```suggestion
            template_id = item.get('templateID', item.get('template-id', ''))
```

2023-05-13 00:18 UTC, Maffooch commented on dojo/tools/nuclei/parser.py
> +                matched = item.get('matched-at')
```suggestion
            matched = item.get('matched', item.get('matched-at', ''))
```

2023-05-13 00:18 UTC, Maffooch commented on dojo/tools/nuclei/parser.py
> +                matcher = ''
```suggestion
            matcher = item.get('matcher-name', item.get('matcher_name'))
            if matcher:
                finding.component_name = matcher
```

2023-05-13 00:18 UTC, Maffooch commented on dojo/tools/nuclei/parser.py
> +                host = ''
```suggestion
            host = item.get('host', '')
```

2023-05-16 16:26 UTC, mtesauro approved these changes
Approved

2023-05-16 16:27 UTC, devGregA approved these changes

2023-05-16 16:40 UTC, cneill approved these changes

2023-05-16 16:42 UTC, mtesauro commented
@damiencarol Are you OK with this?

2023-05-16 21:25 UTC, damiencarol approved these changes

2023-05-16 21:26 UTC, damiencarol commented
all good  @mtesauro  !

2023-05-16 21:26 UTC, merged