helm: unit-tests affinity nodesel tolerations
DefectDojo/django-DefectDojo pull request #8194
Opened 2023-06-02 08:26 UTC by VPelmeSHko

* Add: unittests:
  - nodeSelector
  - affinity
  - tolerations

* Add: initializer:
  - tolerations

* Update:
  - templates/tests/unit-tests.yaml
  - values.yaml

2023-06-10 07:43 UTC, alles-klar approved these changes

2023-06-10 07:45 UTC, alles-klar commented
@VPelmeSHko can you use the dev branch as target branch for your PR please?

2023-07-21 09:44 UTC, alles-klar commented
@VPelmeSHko The chart version needs a version bump. The failing unit tests does not seem related to this PR for me.

2023-07-27 20:27 UTC, cneill requested changes
Thanks for catching the missing `initializer.tolerations` value. However, the modifications to `unit-tests.yaml` reference the wrong values.

2023-07-27 20:27 UTC, cneill commented on helm/defectdojo/templates/tests/unit-tests.yaml
> +      {{- with .Values.initializer.nodeSelector }}
```suggestion
      {{- with .Values.tests.unitTests.nodeSelector }}
```

2023-07-27 20:27 UTC, cneill commented on helm/defectdojo/templates/tests/unit-tests.yaml
> +      {{- with .Values.initializer.affinity }}
```suggestion
      {{- with .Values.tests.unitTests.affinity }}
```

2023-07-27 20:27 UTC, cneill commented on helm/defectdojo/templates/tests/unit-tests.yaml
> +      {{- with .Values.initializer.tolerations }}
```suggestion
      {{- with .Values.tests.unitTests.tolerations }}
```

2023-10-11 04:31 UTC, Maffooch commented
Closing due to stale

2023-10-11 04:31 UTC, closed without merging