Add signal to update Finding `found_by` column
DefectDojo/django-DefectDojo pull request #8351
Opened 2023-07-05 19:40 UTC by Maffooch

When updating the test type of a test, all of the findings under that test will now have an outdated `found_by` value. This column is shown in all of the finding lists, so it is important that it is accurate.

2023-07-05 20:31 UTC, Maffooch commented
Found By is really nice for duplicates across tools. I believe that was the main motivation for using a list for this field? That was before my time, so taking a guess

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46459665/af7191b1-0b17-43ec-a034-4cf164d8cd13)

2023-07-05 21:19 UTC, mtesauro commented
@Maffooch Your guess is correct - that was the motivation for including that.

It's also just generally useful since you have a feel for how much you trust what various tools report.

2023-07-06 21:38 UTC, damiencarol commented
Yes in theory because I think most of the users have 2 lines if they import reports from 2 different tools.

2023-07-07 19:21 UTC, grendel513 approved these changes

2023-07-07 20:03 UTC, mtesauro approved these changes
Approved

2023-07-07 20:12 UTC, devGregA approved these changes

2023-07-07 20:34 UTC, cneill requested changes
Minor typo, otherwise looks good

2023-07-07 20:34 UTC, cneill commented on dojo/test/signals.py
> +def update_found_byt_for_findings(sender, instance, **kwargs):
Should be `update_found_by_for_findings` (extra "t" in there)

2023-07-07 21:02 UTC, blakeaowens approved these changes

2023-07-07 21:25 UTC, cneill approved these changes

2023-07-07 21:25 UTC, merged