Add JSON Ingestion to Veracode Parser
DefectDojo/django-DefectDojo pull request #8414
Opened 2023-07-21 22:03 UTC by Maffooch

Adding JSON Ingestion to Veracode Parser for findings coming out of the API

2023-07-23 20:24 UTC, damiencarol requested changes

2023-07-23 20:24 UTC, damiencarol commented on dojo/tools/veracode/json_parser.py
> +        return json_findings
```suggestion
    def get_findings(self, json_output, test):
        findings = []
        if json_output:
            json_data = json.load(json_output)
            findings += self.get_items(json_data, test)
        return findings
```
`json` module do a better job than us to support UTF8/UTF16 shenanigans.

2023-07-25 08:41 UTC, damiencarol approved these changes

2023-07-25 15:09 UTC, grendel513 approved these changes

2023-07-25 15:15 UTC, mtesauro approved these changes
Approved

2023-07-25 16:27 UTC, devGregA approved these changes

2023-07-25 16:32 UTC, cneill approved these changes

2023-07-25 16:32 UTC, merged