Kube-hunter Parser
DefectDojo/django-DefectDojo pull request #8593
Opened 2023-09-01 15:57 UTC by a-ruff

**Description**

Adding a new parser for the kubernetes scanner : https://github.com/aquasecurity/kube-hunter

**Test results**

Basics parsers tests.

2023-09-01 19:09 UTC, manuel-sommer requested changes
Could you please also add the new parser to the documentation:
https://github.com/DefectDojo/django-DefectDojo/tree/master/docs/content/en/integrations/parsers/file

2023-09-03 21:22 UTC, kiblik commented on dojo/tools/kubehunter/parser.py
> +                references = ''
If I remember correctly, empty `mitigation` and `references` should be `None`, not `''`

2023-09-04 15:40 UTC, a-ruff commented
Thanks for your feedback, I've made the appropriate changes.

2023-09-04 20:04 UTC, mtesauro commented
@a-ruff Just merged Celery 5.3.4 which reverts breaking changes in 5.3.2 and 5.3.3

Can you please rebase? Thanks!

2023-09-05 07:23 UTC, a-ruff commented
I rebased on dev branch by following [DefectDojo documentation](https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/3ef065728d85358f254b56375179494861d8c3be/.github/pull_request_template.md) . Please let me know if I need to do anything else.

2023-09-11 16:36 UTC, Maffooch approved these changes

2023-09-13 22:46 UTC, mtesauro approved these changes
Approved

2023-09-19 12:50 UTC, grendel513 approved these changes

2023-09-20 00:29 UTC, cneill approved these changes

2023-09-20 00:36 UTC, merged