Fixing Helm Ingress Capabilities Check
DefectDojo/django-DefectDojo pull request #8711
Opened 2023-09-21 19:20 UTC by bdun1013

Fixing what was attempted to be fixed in https://github.com/DefectDojo/django-DefectDojo/pull/6759

The original attempted fix checked for the API version plus the resource, when it should have only checked for the API version.

2023-09-22 17:08 UTC, cneill approved these changes

2023-09-22 17:12 UTC, cneill commented
Could you please bump the chart version for this change? Thanks

https://github.com/DefectDojo/django-DefectDojo/blob/b3d3c426deefc74e05795f2d1f30599417d7a96c/helm/defectdojo/Chart.yaml#L5

2023-09-26 14:15 UTC, bdun1013 commented
> Could you please bump the chart version for this change? Thanks
> 
> https://github.com/DefectDojo/django-DefectDojo/blob/b3d3c426deefc74e05795f2d1f30599417d7a96c/helm/defectdojo/Chart.yaml#L5

Bumped to `1.6.89`

2023-09-27 14:43 UTC, Maffooch requested changes
Please base your PR towards `dev` instead of `master`

2023-09-27 14:43 UTC, Maffooch commented on helm/defectdojo/Chart.yaml
>  maintainers:
The versioning here is managed by the release pipeline. Please do not update it here

2023-09-27 15:09 UTC, dsever commented
> Fixing what was attempted to be fixed in #6759
> 
> The original attempted fix checked for the API version plus the resource, when it should have only checked for the API version.

Can you elaborate?
Idea was was to check if resource is in beta specification or in stable to support older clusters. If you remove exact resource type then whole thing makes no sense. 

Do you some issues?

2023-10-06 17:09 UTC, bdun1013 commented
@dsever Sorry for the late reply. I think the Helm documentation is misleading. The `Capabilities.APIVersions.Has` function appears to only work properly with API versions (networking.k8s.io/v1) and not Resources (networking.k8s.io/v1/Ingress).

```
$ kubectl version       
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

```
$ helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.21.1"}
```

I have the `networking.k8s.io/v1` API version available, but not the `networking.k8s.io/v1beta1` API version:
```
$ kubectl api-versions | grep networking                                                                                                
networking.k8s.io/v1
```

With the latest version of the chart, I get an Ingress resource with the `networking.k8s.io/v1beta1` API version:
```
$ helm template defectdojo/defectdojo --version 1.6.89 -s templates/django-ingress.yaml
---
# Source: defectdojo/templates/django-ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: release-name-defectdojo
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.89
spec:
  tls:
  - hosts:
    - defectdojo.default.minikube.local
    secretName: defectdojo-tls
  rules:
  - host: defectdojo.default.minikube.local
    http:
      paths:
        - path: /
          backend:
            serviceName: release-name-defectdojo-django
            servicePort: http
```

With my change, I get the correct Ingress resource:
```
# fixing_helm_ingress_capabilities_check branch
$ helm template helm/defectdojo -s templates/django-ingress.yaml
---
# Source: defectdojo/templates/django-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-defectdojo
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.90-dev
spec:
  tls:
  - hosts:
    - defectdojo.default.minikube.local
    secretName: defectdojo-tls
  rules:
  - host: defectdojo.default.minikube.local
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: release-name-defectdojo-django
              port:
                name: http
```

2023-10-06 17:11 UTC, bdun1013 commented
> Please base your PR towards `dev` instead of `master`

@Maffooch I based the PR towards `dev`

2023-10-23 12:21 UTC, dsever commented
> $ helm template defectdojo/defectdojo --version 1.6.89 -s templates/django-ingress.yaml
> ---
> # Source: defectdojo/templates/django-ingress.yaml
> apiVersion: networking.k8s.io/v1beta1
> kind: Ingress
> metadata:
>   name: release-name-defectdojo
>   labels:
>     defectdojo.org/component: django
>     app.kubernetes.io/name: defectdojo
>     app.kubernetes.io/instance: release-name
>     app.kubernetes.io/managed-by: Helm
>     helm.sh/chart: defectdojo-1.6.89
> spec:
>   tls:
>   - hosts:
>     - defectdojo.default.minikube.local
>     secretName: defectdojo-tls
>   rules:
>   - host: defectdojo.default.minikube.local
>     http:
>       paths:
>         - path: /
>           backend:
>             serviceName: release-name-defectdojo-django
>             servicePort: http
> ```
> 
> With my change, I get the correct Ingress resource:
> 
> ```
> # fixing_helm_ingress_capabilities_check branch
> $ helm template helm/defectdojo -s templates/django-ingress.yaml
> ---
> # Source: defectdojo/templates/django-ingress.yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: release-name-defectdojo
>   labels:
>     defectdojo.org/component: django
>     app.kubernetes.io/name: defectdojo
>     app.kubernetes.io/instance: release-name
>     app.kubernetes.io/managed-by: Helm
>     helm.sh/chart: defectdojo-1.6.90-dev
> spec:
>   tls:
>   - hosts:
>     - defectdojo.default.minikube.local
>     secretName: defectdojo-tls
>   rules:
>   - host: defectdojo.default.minikube.local
>     http:
>       paths:
>         - pathType: Prefix
>           path: "/"
>           backend:
>             service:
>               name: release-name-defectdojo-django
>               port:
>                 name: http
> ```

Sorry for my late response, you can't validate `Capabilities` by using template, because it never reaches the k8s API, try with --dry-run  
Another concern I'm seeing, from version 1.7 it will be always true, because networking.k8s.io/v1 is there from version 1.7 when network policies have graduated

2023-12-29 17:46 UTC, mtesauro commented
Closed as stale

2023-12-29 17:46 UTC, closed without merging