Excel Export throws 500 error code
DefectDojo/django-DefectDojo pull request #8735
Opened 2023-09-26 23:21 UTC by FelixHernandez

## Excel Export throws 500 error code
[sc-2338]

**Description**
This fix allows the user export to excel and csv the findings properly. The error is now wrapped in a `try...catch` statement and the exception is being logged for visibility.

2023-09-27 00:15 UTC, grendel513 approved these changes

2023-09-27 14:15 UTC, Maffooch requested changes
The same fix will need to be applied when inserting values into each row:

CSV: https://github.com/DefectDojo/django-DefectDojo/blob/f3e590453bfc5dc719b5f2f1d82196dfdb7beab4/dojo/reports/views.py#L870-L882
Excel: https://github.com/DefectDojo/django-DefectDojo/blob/f3e590453bfc5dc719b5f2f1d82196dfdb7beab4/dojo/reports/views.py#L968-L981

2023-09-27 15:57 UTC, Maffooch approved these changes

2023-09-27 16:05 UTC, cneill approved these changes

2023-09-28 00:01 UTC, mtesauro approved these changes
Approved

2023-09-28 00:01 UTC, merged