Update ASFF parser to create endpoints
DefectDojo/django-DefectDojo pull request #8742
Opened 2023-09-27 19:22 UTC by vd0n

## Modified ASFF Parser: Create endpoints based on EC2 private IPv4 address.

### Description
In this update to the ASFF parser, endpoints are now created based solely on the EC2 instance's private IP address. I've implemented a check to ensure each IP address is private, thereby disregarding any public IPs present in the data. This provides a more accurate representation of the internal infrastructure and prevents potential data leaks by not exposing public IPs.

### Test Results
- [x] The updated parser has been tested with ASFF data containing a mix of private and public IP addresses.
- [ ] Comprehensive tests have been added to the test suite in `tests/` to cover these changes. (Only check if you've added tests.)

### Documentation
- [ ] I've updated the relevant sections in the [documentation folder](https://github.com/DefectDojo/django-DefectDojo/tree/dev/docs) to reflect these parser changes. (Only check if you've updated the documentation.)

### Checklist
- [x] I have rebased my PR against the latest `dev` branch.
- [x] This feature has been submitted against the `dev` branch.
- [x] The PR has been given a meaningful name.
- [x] My code is flake8 compliant.
- [x] My code is compatible with python 3.11.
- [x] Applicable tests have been added to the unit tests suite.
- [x] I have categorized the PR with the proper label.

### Additional Notes
This modification ensures that DefectDojo users get an accurate representation of their infrastructure without exposing potential security risks associated with public IP addresses.

For moderators:
Please review and let me know if any further changes are needed. Given the sensitive nature of IP addresses, I believe this is a crucial update to the parser.

**Labels:** enhancement, Import Scans

2023-09-29 14:19 UTC, Maffooch requested changes
Please add some unit tests that successfully import endpoints in the way that you are expecting them to be added

2023-09-29 14:19 UTC, Maffooch commented on dojo/tools/asff/parser.py
> -    # The issue must be remediated immediately to avoid it escalating.
Please don't remove comments that are adding context to the parser

2023-09-29 14:19 UTC, Maffooch commented on dojo/tools/asff/parser.py
> +                            if is_private_ipv4(ip):
Why are only private IPs allowed to be added?

2023-09-30 20:38 UTC, kiblik requested changes

2023-09-30 20:38 UTC, kiblik commented on dojo/tools/asff/parser.py
> +                        for ip in details.get("IpV4Addresses", []):
Can you process IPv6 as well? Not show stopper. Just idea.

2023-10-04 13:35 UTC, kiblik commented on dojo/tools/asff/parser.py
> +                                endpoints.append(Endpoint(host=ip))
If the rest of the community will accept it, okay.

Can you use use different "private address checker"? More standard and easier to maintain.
```suggestion
                            from netaddr import IPAddress
                            if IPAddress(ip).is_private():
                                endpoints.append(Endpoint(host=ip))
```

2023-10-11 03:38 UTC, Maffooch commented
There was some hoakey issues with the unit tests for a minute. Please pull the latest dev branch with the updated changes

2023-12-29 17:51 UTC, mtesauro commented
@vd0n Can you fix the failing tests  and reviews so this can be merged?

2024-01-10 07:29 UTC, manuel-sommer commented
@vd0n will you finish the PR or shaal I create a New one @mtesauro ?

2024-01-10 14:54 UTC, mtesauro commented
@manuel-sommer It's been long enough that I'm fine with closing this as stale and having you work on it if you're willing.

2024-01-16 22:30 UTC, mtesauro commented
@manuel-sommer I'm going to close this one - feel free to take it up if you have the bandwidth.

2024-01-16 22:30 UTC, closed without merging

2024-01-16 22:47 UTC, manuel-sommer commented
Yes, see linked PR above