Add sshaudit parser #8837
DefectDojo/django-DefectDojo pull request #8838
Opened 2023-10-17 11:47 UTC by manuel-sommer

Adds new parser, see #8837

2023-10-17 11:48 UTC, manuel-sommer commented
@quirinziessler fyi

2023-10-17 11:52 UTC, quirinziessler approved these changes
nice job done 👍

2023-10-17 12:35 UTC, manuel-sommer commented
@cneill, @Maffooch, @madchap, @mtesauro and @blakeaowens ready to review.

2023-10-19 20:27 UTC, cneill requested changes
Looks good, but the unit tests could use some additional validation. See e.g. the [SonarQube unit tests](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/tools/test_sonarqube_parser.py) or others in the [`tools` unit tests directory](https://github.com/DefectDojo/django-DefectDojo/tree/master/unittests/tools).

2023-10-19 20:27 UTC, cneill commented on unittests/tools/test_ssh_audit_parser.py
> +        self.assertEqual(20, len(findings))
It would be good to have some additional assertions here to further validate the parsing logic

2023-10-19 20:27 UTC, cneill commented on unittests/tools/test_ssh_audit_parser.py
> +        self.assertEqual(12, len(findings))
Same as comment above

2023-10-20 20:37 UTC, cneill approved these changes
Thanks!

2023-10-21 02:04 UTC, mtesauro approved these changes
Approved

2023-10-21 13:44 UTC, manuel-sommer commented
@Maffooch and @blakeaowens ready to review.

2023-10-21 17:34 UTC, blakeaowens approved these changes

2023-10-23 09:37 UTC, manuel-sommer commented
@Maffooch could you please review this PR?

2023-10-25 11:24 UTC, manuel-sommer commented
@grendel513 could you please review this PR?

2023-10-25 18:07 UTC, grendel513 approved these changes

2023-10-25 22:07 UTC, merged