add new guidelines for parser documentation
DefectDojo/django-DefectDojo pull request #8910
Opened 2023-10-30 19:45 UTC by paulOsinski

Adding new guidelines for Parser Documentation as part of the 'writing a new parser' process

2023-10-30 20:08 UTC, Maffooch approved these changes

2023-10-31 07:26 UTC, manuel-sommer requested changes

2023-10-31 07:26 UTC, manuel-sommer commented on docs/content/en/contributing/how-to-write-a-parser.md
> +
* A link to the scanner itself (e.g. github or vendor link)

2023-11-01 10:03 UTC, manuel-sommer commented on docs/content/en/contributing/how-to-write-a-parser.md
> +
Maybe it could be helpful if you also add a default predefined template which can be copied easily, then the format is mostly the same?

2023-11-01 12:11 UTC, mtesauro approved these changes
Approved

2023-11-04 22:13 UTC, grendel513 approved these changes

2023-11-06 15:34 UTC, Maffooch requested changes
@paulOsinski this is good feedback @manuel-sommer. Please take a look

2023-11-08 17:16 UTC, manuel-sommer commented
Something is wrong here with your commits, maybe rebase?

2023-11-08 17:56 UTC, paulOsinski commented
I broke this PR so I am going to recommit elsewhere.

2023-11-08 17:56 UTC, closed without merging

2023-11-08 21:39 UTC, paulOsinski commented
new PR here: https://github.com/DefectDojo/django-DefectDojo/pull/8910