:tada: added humble #8988
DefectDojo/django-DefectDojo pull request #8989
Opened 2023-11-13 21:35 UTC by manuel-sommer

See #8988

2023-11-13 22:01 UTC, manuel-sommer commented
Waiting for https://github.com/rfc-st/humble/issues/13

2023-11-15 09:45 UTC, kiblik commented
Please follow
- https://documentation.defectdojo.com/contributing/how-to-write-a-parser/#endpoint-validation
- `url != host` https://documentation.defectdojo.com/contributing/how-to-write-a-parser/#do-not-parse-urls-by-hand

2023-11-17 03:31 UTC, mtesauro approved these changes
Approved

2023-11-17 03:57 UTC, blakeaowens approved these changes

2023-11-17 12:49 UTC, kiblik requested changes
First sorry, I forgot to come back to this PR

Not that sure that _Do not parse URLs by hand_ means
```python
            import re
            host = re.compile(r"https?://(www\.)?")
            host = host.sub('', url).strip().strip('/')
```

Some notes:
The original idea with endpoints (and how most of the parsers are implemented right now) is that: If multiple endpoints have the same `Finding`, let's define it as one finding and use `Endpoint_Status` to identify, which `Endpoint`s are affected. Yes, it is not possible in all cases (especially if there are some different metadata for each endpoint - but it is not the case here).
It means that information about the endpoint should not be presented in the `Finding.title` or `Finding.description` (if it is possible). It is also the reason why `Finding.url`: https://github.com/DefectDojo/django-DefectDojo/blob/393f4606ba4f04c3f450dbd133d42b5734564a6d/dojo/models.py#L2157-L2161 is not used anywhere anymore (and should be removed).

Next, information about protocol (`http` vs `https`) is valuable. So we should not avoid it. Also path (different paths might have different results for scanning). And `www.` should not be removed from the host as well.

So if it is not necessary because of some specific metadata (which is not in this case), please:
- Avoid adding the name of the endpoint/host to the content of the finding
- Use endpoint in the full form (including protocol and path)

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +            host = host.sub('', url).strip().strip('/')
```suggestion
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding = Finding(title=host + "_missing_" + str(content),
```suggestion
                    finding = Finding(title="Missing header: " + str(content),
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding.unsaved_endpoints.append(endpoint)
```suggestion
                    finding.unsaved_endpoints = [Endpoint.from_uri(url)]
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding.unsaved_endpoints.append(endpoint)
```suggestion
                    finding.unsaved_endpoints = [Endpoint.from_uri(url)]
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding = Finding(title=host + "_fingerprint_" + str(content),
```suggestion
                    finding = Finding("Available fingerprint: " + str(content),
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                        test=test,
Adding the `test` is not necessary. It will be done in the (re)importer
```suggestion
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                        test=test,
```suggestion
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding.unsaved_endpoints.append(endpoint)
```suggestion
                    finding.unsaved_endpoints = [Endpoint.from_uri(url)]
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding.unsaved_endpoints.append(endpoint)
```suggestion
                    finding.unsaved_endpoints = [Endpoint.from_uri(url)]
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                        test=test,
```suggestion
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding = Finding(title=host + "_emptyhttpresponse_" + str(content),
```suggestion
                    finding = Finding(title="Empty HTTP response header: " + str(content),
```

2023-11-17 12:49 UTC, kiblik commented on dojo/tools/humble/parser.py
> +                    finding = Finding(title=host + "_deprecatedheader_" + str(content),
```suggestion
                    finding = Finding(title="Deprecated header: " + str(content),
```

2023-11-17 14:18 UTC, grendel513 approved these changes

2023-11-17 23:26 UTC, manuel-sommer commented
@kiblik, I accepted your review, but is the finding title now not too general? I would rather make it more unique. Maybe we now need deduplication settings?

2023-11-20 14:41 UTC, Maffooch commented
>Maybe we now need deduplication settings?

This would be ideal. Even if they happen to match the default dedupe settings, it affords other users to override the fields used without a code change being required

2023-11-28 07:54 UTC, manuel-sommer commented
@Maffooch ready to review and then merge

2023-11-28 08:30 UTC, kiblik commented on dojo/settings/settings.dist.py
> +    'Humble Json Importer': ['title', 'description'],
```suggestion
    'Humble Json Importer': ['title'],
```
I would like to ask, why is `'description'` needed for deduplication?

2023-11-28 09:45 UTC, kiblik approved these changes

2023-11-29 19:49 UTC, manuel-sommer commented
@cneill ready to review and merge

2023-11-30 00:17 UTC, cneill approved these changes

2023-11-30 10:30 UTC, manuel-sommer commented
Could you also please merge :-)

2023-11-30 17:36 UTC, merged