fix button color in risk acceptance bug
DefectDojo/django-DefectDojo pull request #9008
Opened 2023-11-16 08:25 UTC by FelixHernandez

## fix button color in risk acceptance bug
[sc-3141]

**Description**

This bugfix shows the Add selected Findings button in a visible color  in /engagement/id/risk_acceptance/id/edit url

**Test results**

now it shows like the following.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/7889626/e67452e3-bebe-4263-b0a5-0c6913cc840f)

2023-11-16 14:51 UTC, grendel513 approved these changes

2023-11-17 03:43 UTC, blakeaowens requested changes
Removing the `background-color: transparent!important` attribute from these classes will affect lots of other areas in DefectDojo.

It may be best to just modify the template to look something like this:
```
            <form method="post" class="form-horizontal">{% csrf_token %}
                <div class="show_add_findings_form">
                    {% include "dojo/form_fields.html" with form=add_findings_form %}
                </div>
                <div class="panel-body">
                    {% include "dojo/paging_snippet.html" with page=add_findings prefix="apage" %}
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input class="btn" name="add_findings" type="submit" value="Add Selected Findings"/>
                    </div>
                </div>
            </form>
```

Which would produce a result like this (similar to the _Add Note_ button):
<img width="1020" alt="Screenshot 2023-11-16 at 9 43 17 PM" src="https://github.com/DefectDojo/django-DefectDojo/assets/76979297/9e232522-456b-4ac5-be7d-acefa348e4ce">

2023-11-17 18:07 UTC, cneill approved these changes

2023-11-17 19:54 UTC, grendel513 approved these changes

2023-11-20 19:33 UTC, blakeaowens commented on dojo/static/dojo/css/dojo.css
> +.btn-in-footer{
Since this is no longer used, please remove, then this looks good!

2023-11-21 18:18 UTC, blakeaowens approved these changes

2023-11-22 02:46 UTC, mtesauro approved these changes
Approved

2023-11-22 02:47 UTC, merged