:bug: fix issue #9170
DefectDojo/django-DefectDojo pull request #9215
Opened 2023-12-22 20:27 UTC by manuel-sommer

Fix Issue #9170

2023-12-22 20:30 UTC, manuel-sommer commented
@dsever could you take a look please?

2023-12-22 21:06 UTC, manuel-sommer commented
@Maffooch, @cneill, @madchap and @grendel513 maybe you also have time to approve this before the next release?

2023-12-22 22:38 UTC, cneill requested changes
Just a suggestion on the example findings file

2023-12-22 22:38 UTC, cneill commented on unittests/scans/trivy/issue_9170.json
We probably don't need a 6.5MB file for this unit test, since the test doesn't really check the details of most of these findings anyway. I'd recommend cutting it down to something closer to ~25 findings.

2023-12-22 23:22 UTC, manuel-sommer commented
Done @cneill

2023-12-22 23:43 UTC, cneill approved these changes

2023-12-23 02:00 UTC, mtesauro approved these changes
Approved

2023-12-26 17:33 UTC, Maffooch approved these changes

2023-12-28 20:29 UTC, manuel-sommer commented
Could you take a look and merge @grendel513 ?

2023-12-29 15:57 UTC, grendel513 approved these changes

2023-12-29 16:25 UTC, devGregA approved these changes

2023-12-29 16:26 UTC, merged