Fix Clair Report Parser
DefectDojo/django-DefectDojo pull request #9216
Opened 2023-12-23 06:34 UTC by u-ahmedofficial

## :warning: Update in reporting format in New clair versions :warning:

**Description**

The new versions of clair have different formatting of reports which is incompatible with the existing *keys* being parsed and the way those are parsed.

**Test results**

I have tested the modification in my own project workflow as well as locally, i was able to parse the latest reports and sync results in the engagements.

I have tried following versions of Clair:

* v4.7.2 - 2023-10-09
* v4.4.4 - 2022-06-09
* v4.6.1 - 2023-04-13

**Report for v4.6.1**

[report-april.json](https://github.com/DefectDojo/django-DefectDojo/files/13758232/report-april.json)

[Uploading report-april-1.json…]()

**Report for v4.7.1**

[Uploading report.json…]()

2023-12-23 07:56 UTC, manuel-sommer requested changes
You have to branch this fix against bugfix or dev from a different branch. 
As an example see at other PRs, e.g. https://github.com/DefectDojo/django-DefectDojo/pull/9215.

2023-12-23 07:56 UTC, manuel-sommer commented on dojo/tools/clair/parser.py
> +        item_node["severity"] == "unimportant"
Can you please add a unittest for Clair?

2023-12-23 07:56 UTC, manuel-sommer commented on helm/defectdojo/Chart.yaml
> +appVersion: "2.30.0-dev"
Why do you change the appVersion?

2023-12-23 07:56 UTC, manuel-sommer commented on components/package.json
> +  "version": "2.30.0-dev",
Why do you change package.json?

2023-12-26 17:48 UTC, Maffooch requested changes
These changes look like a hard cut over from an older version of Clair to this newer version you are using. Please make your change backwards compatible such that existing unit tests will pass as well as the new unit tests you add as part of this change

2024-01-30 23:30 UTC, Maffooch commented
Closing for now as Clair and Clair Klar have been merged into on parser. Conflicts will likely be dicey when those changes reach the bugfix branch next release

2024-01-30 23:30 UTC, closed without merging