Fix nikto issue 9274
DefectDojo/django-DefectDojo pull request #9275
Opened 2024-01-04 10:49 UTC by manuel-sommer

see issue #9274

2024-01-04 16:50 UTC, mtesauro commented
@manuel-sommer Hmm. I think it's better to report at info and let people move it up to Low (or whatever) based on how they rate issues internally. That's probably better then potentially inflating the severity of a finding.

2024-01-04 16:54 UTC, mtesauro approved these changes
Approved.

I'm a fan of making the parser smarter so it handles multiple formats from a tool so thanks for doing that. Much better than YASTP (Yet Another Same Tool Parser)

2024-01-04 17:11 UTC, manuel-sommer commented
> @manuel-sommer Hmm. I think it's better to report at info and let people move it up to Low (or whatever) based on how they rate issues internally. That's probably better then potentially inflating the severity of a finding.

This could also be a usecase for this: https://github.com/DefectDojo/django-DefectDojo/issues/9250
If you give me a hint on how to advance the api and parse the value there to the finding parser, I could make a PR and advance nikto in a way to have:
- default setting = severity Info
- api setting = severity from api

2024-01-04 17:40 UTC, cneill requested changes

2024-01-04 17:40 UTC, cneill commented on dojo/tools/nikto/parser.py
> +            if vulnerability.get('OSVDB') is None:
Shouldn't this condition be flipped?
```suggestion
            if vulnerability.get('OSVDB') is not None:
```

2024-01-04 22:44 UTC, Maffooch requested changes
Reducing duplicated code

2024-01-04 22:44 UTC, Maffooch commented on dojo/tools/nikto/parser.py
> +                ])
```suggestion
            description = "\n".join([
                f"**id:** `{vulnerability.get('id')}`",
                f"**msg:** `{vulnerability.get('msg')}`",
                f"**HTTP Method:** `{vulnerability.get('method')}`",
            ])
            if vulnerability.get('OSVDB') is not None:
                description += "\n" + f"**OSVDB:** `{vulnerability.get('OSVDB')}`"
```

2024-01-04 23:05 UTC, Maffooch approved these changes
Thanks @manuel-sommer :)

2024-01-04 23:53 UTC, cneill approved these changes

2024-01-10 19:55 UTC, blakeaowens approved these changes

2024-01-10 19:55 UTC, merged