:bug: fix hcl appscan, issue #9279
DefectDojo/django-DefectDojo pull request #9282
Opened 2024-01-05 00:02 UTC by manuel-sommer

issue #9279

2024-01-16 16:23 UTC, manuel-sommer commented
Could you take a look and review this also please @mtesauro ?

2024-01-16 16:34 UTC, mtesauro approved these changes
Approved

2024-01-17 17:57 UTC, Maffooch approved these changes

2024-01-17 22:09 UTC, cneill requested changes

2024-01-17 22:09 UTC, cneill commented on dojo/tools/hcl_appscan/parser.py
> +                            title += "_" + domain
I don't see much benefit to introducing spaces into the title in this way, given that the individual parts are already separated by `_`. A `.strip()` seems appropriate here

```suggestion
                            title += "_" + domain.strip()
```

2024-01-17 22:09 UTC, cneill commented on dojo/tools/hcl_appscan/parser.py
> +                            title += "_" + causeid
Same comment as above

```suggestion
                            title += "_" + causeid.strip()
```

2024-01-17 22:09 UTC, cneill commented on dojo/tools/hcl_appscan/parser.py
> +                            title += "_" + entity
Same comment as above

```suggestion
                            title += "_" + entity.strip()
```

2024-01-17 22:09 UTC, cneill commented on dojo/tools/hcl_appscan/parser.py
> +                            title += "_" + urlname
Same comment as above

```suggestion
                            title += "_" + urlname.strip()
```

2024-01-17 22:09 UTC, cneill commented on dojo/tools/hcl_appscan/parser.py
> +                            title += "_" + path
Same comment as above

```suggestion
                            title += "_" + path.strip()
```

2024-01-17 22:09 UTC, cneill commented on unittests/tools/test_hcl_appscan_parser.py
> +        self.assertEqual(findings[1].title, " Unencrypted Login Request_ mani-virtual-machine_ /dvja-1.0-SNAPSHOT/login.action;jsessionid=AD12F9CF7835CC92885A381859462BAC")
```suggestion
        self.assertEqual(findings[0].title, " Unencrypted Login Request_mani-virtual-machine_/dvja-1.0-SNAPSHOT/register.action")
        self.assertEqual(findings[1].title, " Unencrypted Login Request_mani-virtual-machine_/dvja-1.0-SNAPSHOT/login.action;jsessionid=AD12F9CF7835CC92885A381859462BAC")
```

2024-01-17 22:09 UTC, cneill commented on unittests/tools/test_hcl_appscan_parser.py
> +        self.assertEqual(findings[1].title, " attHttpsToHttp_ 7089695691196187648_ sensitiveDataNotSSL")
```suggestion
        self.assertEqual(findings[0].title, " attUnnecessaryResponseHeaders_7089695691196187648_insecureWebAppConfiguration")
        self.assertEqual(findings[1].title, " attHttpsToHttp_7089695691196187648_sensitiveDataNotSSL")
```

2024-01-18 18:02 UTC, cneill approved these changes

2024-01-25 18:56 UTC, grendel513 approved these changes

2024-01-25 22:42 UTC, merged