Changing name of Whitestone to Mend
DefectDojo/django-DefectDojo pull request #9359
Opened 2024-01-18 16:47 UTC by grendel513

Updating name if Whitestone to Mend - this does not touch documentation as there is another pull request for that specifically already.

2024-01-19 16:51 UTC, Maffooch commented
Also would be good to add a breaking change section to the upgrade notes for folks that could be using Whitesource in an API based import. [Here is an example from when the Nessus -> Tenable conversion was made](https://documentation.defectdojo.com/getting_started/upgrading/2.23/)

2024-01-19 17:04 UTC, grendel513 commented
Thanks @Maffooch - Migration has been added

2024-01-19 17:16 UTC, grendel513 commented
Thanks @Maffooch - documentation added in upgrade notes

2024-01-19 17:17 UTC, grendel513 commented
> * unit test scan files that are not related to whitesource/mend should probably not be updated here

I updated those references from whitesource to mend to better align with new name.  functionality is not affected

2024-01-19 17:52 UTC, kiblik requested changes

2024-01-19 17:52 UTC, kiblik commented on docs/content/en/getting_started/upgrading/2.31.0.md
> +title: "Upgrading to DefectDojo Version 2.31.0"
Please update the existing `2.31.md`. This will create duplicity.

2024-01-19 18:13 UTC, mtesauro approved these changes
Approved

2024-01-31 20:10 UTC, Maffooch commented
Failing test is accommodated in #9348 
```
2024-01-31T19:46:48.0088609Z [36muwsgi_1         |[0m ======================================================================
2024-01-31T19:46:48.0089177Z [36muwsgi_1         |[0m FAIL: test_file_existence (unittests.test_parsers.TestParsers.test_file_existence) (parser='mend', category='docs')
2024-01-31T19:46:48.0089469Z [36muwsgi_1         |[0m ----------------------------------------------------------------------
2024-01-31T19:46:48.0089818Z [36muwsgi_1         |[0m Traceback (most recent call last):
2024-01-31T19:46:48.0090196Z [36muwsgi_1         |[0m   File "/app/unittests/test_parsers.py", line 27, in test_file_existence
2024-01-31T19:46:48.0090371Z [36muwsgi_1         |[0m     self.assertTrue(
2024-01-31T19:46:48.0091186Z [36muwsgi_1         |[0m AssertionError: False is not true : Documentation file '/app/unittests/../docs/content/en/integrations/parsers/file/mend.md' is missing or using 
```

2024-01-31 20:11 UTC, Maffooch approved these changes

2024-01-31 21:06 UTC, blakeaowens approved these changes

2024-01-31 21:06 UTC, merged

2024-02-07 14:12 UTC, devopscodeck commented
In my tests the functionality is not working... also for Whitesource naming, Mend's json reports are not acceptable for defectdojo, even the json format.

The versions that i tested: defectdojo  3.31.0 && 2.27.4
Somebody else?

2024-02-07 14:16 UTC, kiblik commented
There was some issue with "WhiteSource vs Mend" reported in Slack as well https://owasp.slack.com/archives/C2P5BA8MN/p1707244117982809

2024-02-07 21:12 UTC, mtesauro commented
@devopscodeck Can you provide a sanitized Mend json file? Having samples is really the only way for us to test scanner output especially for commercial offerings.

Happy to look at the parser code and add unit tests but we'll need an example first.