Override default Django APPEND_SLASH
DefectDojo/django-DefectDojo pull request #9385
Opened 2024-01-22 14:59 UTC by kiblik

Avoid situations like https://owasp.slack.com/archives/C2P5BA8MN/p1705702146187379

Better context description: https://learndjango.com/tutorials/trailing-url-slashes-django

Documentation: https://docs.djangoproject.com/en/4.2/ref/settings/#append-slash

2024-01-30 22:24 UTC, Maffooch requested changes

2024-01-30 22:24 UTC, Maffooch commented on dojo/settings/settings.dist.py
> +    DD_APPEND_SLASH=(bool, False),
We should default to True here to match what it has always been for folks as well as the default set by Django

2024-01-30 22:28 UTC, kiblik commented on dojo/settings/settings.dist.py
> +    DD_APPEND_SLASH=(bool, False),
```suggestion
    DD_APPEND_SLASH=(bool, True),
```

2024-01-30 22:56 UTC, Maffooch approved these changes

2024-01-30 23:20 UTC, mtesauro approved these changes
Approved

2024-02-06 09:34 UTC, kiblik commented
Hi @grendel513 / @devGregA / @cneill / @blakeaowens. I would like to ask for a review.

2024-02-06 20:21 UTC, grendel513 approved these changes

2024-02-06 21:38 UTC, blakeaowens approved these changes

2024-02-06 23:10 UTC, merged