Trivy Operator additionalVulnerabilityReportFields
DefectDojo/django-DefectDojo pull request #9398
Opened 2024-01-23 15:06 UTC by raouf-haddada

This feature allows adding Target, Class, PackagePath and PackageType already managed in trivy reports

related to:
**trivy-operator** [additionalVulnerabilityReportFields](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L315C1-L317C42)
```
  # -- additionalVulnerabilityReportFields is a comma separated list of additional fields which
  # can be added to the VulnerabilityReport. Supported parameters: Description, Links, CVSS, Target, Class, PackagePath and PackageType
  additionalVulnerabilityReportFields: ""
```

2024-01-23 15:13 UTC, manuel-sommer requested changes

2024-01-23 15:13 UTC, manuel-sommer commented on dojo/tools/trivy_operator/parser.py
> +                package_path = None
Could you please extend the unittests?

2024-01-23 21:13 UTC, raouf-haddada commented on dojo/tools/trivy_operator/parser.py
> +                package_path = None
Done

2024-01-24 09:21 UTC, manuel-sommer approved these changes

2024-01-25 18:50 UTC, grendel513 approved these changes

2024-01-30 22:22 UTC, Maffooch commented
Will be good too approve when all tests are passing

2024-01-31 16:07 UTC, closed without merging

2024-01-31 16:29 UTC, raouf-haddada commented
Replaced by:
https://github.com/DefectDojo/django-DefectDojo/pull/9452 
Thx