Fix anchore grype issue 9618
DefectDojo/django-DefectDojo pull request #9620
Opened 2024-02-23 09:34 UTC by manuel-sommer

see #9618

2024-02-24 05:02 UTC, mtesauro approved these changes
Approved

2024-02-25 03:08 UTC, Maffooch requested changes

2024-02-25 03:08 UTC, Maffooch commented on unittests/scans/anchore_grype/issue_9618.json
Please reduce the size of this file

2024-02-25 04:24 UTC, manuel-sommer commented
Done @Maffooch, please rereview. :-)

2024-02-26 17:40 UTC, cneill approved these changes

2024-02-26 18:32 UTC, manuel-sommer commented
@Maffooch I have shrink the file with about 50% https://github.com/DefectDojo/django-DefectDojo/pull/9620/commits/fd6197f824cc941ecb4ac001a7d7f8b05e7a22ab

2024-02-27 22:51 UTC, Maffooch commented
I apologize @manuel-sommer I should have been more specific, can you please reduce the number of findings produced to something more reasonable like 10 findings? Having 240 findings to be parsed for a single test increases the time unit tests will run, and increases the size of the repo without much gain

2024-02-27 23:03 UTC, manuel-sommer commented
Done @Maffooch. Please review again.

2024-02-28 17:27 UTC, Maffooch approved these changes

2024-03-04 04:01 UTC, devGregA approved these changes

2024-03-04 04:08 UTC, merged