Added Snyk Code Parser
DefectDojo/django-DefectDojo pull request #9647
Opened 2024-02-29 00:38 UTC by FelixHernandez

##  Added Snyk Code Parser
[sc-4509]

**Description**

A new `SnykCodeParser` was added and the deduplication is based on `ruleID` and `URI` (`file_path`).
The unittests for this parser were added as well.
https://github.com/DefectDojo/django-DefectDojo/issues/9604

2024-02-29 07:50 UTC, manuel-sommer requested changes

2024-02-29 07:50 UTC, manuel-sommer commented on docs/content/en/integrations/parsers/file/snyk_code.md
> +title: "Snyk"
Hi @FelixHernandez 
title should then be "Snyk Code"

In general I personally like it more if we don't add more and more parsers for multiple functionalities of one vendor, but maybe rather one parser which covers all functionalities of a vendor. This is why I made PRs like these two:
https://github.com/DefectDojo/django-DefectDojo/pull/9522
https://github.com/DefectDojo/django-DefectDojo/pull/9355

Furthermore: Did you check out this PR:
https://github.com/DefectDojo/django-DefectDojo/pull/9289

2024-02-29 07:50 UTC, manuel-sommer commented on dojo/tools/snyk_code/parser.py
> +        return ["Snyk Code Scan"]
if you implemented this parser to distinguish between Snyk and Snyk Code, I would rather recommend to either do it like it was done with RustyHog: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/rusty_hog/parser.py or with Checkmarx: https://github.com/DefectDojo/django-DefectDojo/blob/c5d896b2a606985f41669388962e47409f4866ba/dojo/tools/checkmarx/parser.py#L16

2024-02-29 14:59 UTC, manuel-sommer commented
Hi @grendel513,

I would like to understand why you resolved my review. Could you please comment on that?

Best Regards

2024-02-29 15:47 UTC, grendel513 commented
> Hi @grendel513,
> 
> I would like to understand why you resolved my review. Could you please comment on that?
> 
> Best Regards

My comment specifically stated why: Keeping this a separate parser is the correct implementation to allow for its own deduplication which is what we are trying to solve for. Additionally having to individual parsers is easier to troubleshoot should issues arise, and has a the benefit of not affecting other tool ingestion if there is something wrong.

Moving forward we will be asking that new parsers be single threaded in function, as having parsers that parse multiple file types creates issues with debugging, deduplication, and the ability to have a separate deduplication configuration.

2024-02-29 16:04 UTC, manuel-sommer commented
> > Hi @grendel513,
> > I would like to understand why you resolved my review. Could you please comment on that?
> > Best Regards
> 
> My comment specifically stated why: Keeping this a separate parser is the correct implementation to allow for its own deduplication which is what we are trying to solve for. Additionally having to individual parsers is easier to troubleshoot should issues arise, and has a the benefit of not affecting other tool ingestion if there is something wrong.
> 
> Moving forward we will be asking that new parsers be single threaded in function, as having parsers that parse multiple file types creates issues with debugging, deduplication, and the ability to have a separate deduplication configuration.

Thank you for clarification. 😄 I understand your logic. 
What if we advance the parser structure in a way that file stuctures are automatically recognized (e.g. look at RustyHog) and then deduplication could be implemented for the subfile types (e.g. Deduplication for GottingenHog (RustyHog) etc.)
This whole topic is pretty complicated as there are pros and cons in both directions, but for beginners it would be easier if the number of parsers to be selected within a vendor is limited and the logic within DefectDojo handles the rest. 
One way could also be which was implemented in veracode:
1. entry is a single parser for a vendor
2. parser recognizes the file type (subscanner)
3. individual deduplication and scannertype recognition (e.g. like in veracode + rustyhog)

2024-02-29 18:26 UTC, mtesauro approved these changes
Approved

2024-02-29 18:53 UTC, grendel513 approved these changes

2024-02-29 22:03 UTC, blakeaowens approved these changes

2024-03-01 01:17 UTC, cneill approved these changes

2024-03-01 16:20 UTC, merged