✨  add deepfence threatmapper
DefectDojo/django-DefectDojo pull request #9688
Opened 2024-03-06 15:08 UTC by manuel-sommer

see issue #9687

2024-03-07 09:15 UTC, shodanwashere commented
I'm checking your code here, so you wrote the parser so that it can automatically identify if it's one of the 4 report types? All findings will therefore be aggregated together?

2024-03-07 15:43 UTC, shodanwashere approved these changes
4 different reports with different formats were given, and they can all be aggregated under one single report type.
LGTM!

2024-03-07 17:12 UTC, mtesauro commented
@manuel-sommer @shodanwashere Just for awareness, there's some very new parser guidelines I wrote up at 
https://github.com/DefectDojo/django-DefectDojo/discussions/9690

In this specific case, I think this is fine because they are from the same tool (and type of tool) and have generally the same info expressed in different file format.

Would love to have you confirm that since shodanwashere appears to be a user of this tool.

2024-03-07 19:21 UTC, manuel-sommer commented
Sounds legit, thank you for the hint @mtesauro. I would be ok with both ways here: approve how it is right now or I can go with your policy and make 4 parsers out of it, depends on your review.

2024-03-08 18:58 UTC, cneill requested changes
A couple thoughts on this while we wait for a reply to [this question](https://github.com/DefectDojo/django-DefectDojo/issues/9687#issuecomment-1984922055) about how the tool actually formats its output

2024-03-08 18:58 UTC, cneill commented on dojo/tools/deepfence_threatmapper/parser.py
> +                description += "**scan_id: **" + scan_id + "\n"
Since the de-duplication hashcode includes the description, including the scan ID likely doesn't make sense if it is unique every time the tool runs.

2024-03-08 18:58 UTC, cneill commented on dojo/tools/deepfence_threatmapper/parser.py
> +                description += "**cloud_account_id: **" + cloud_account_id + "\n"
The spacing here seems to mess up the Markdown parser when there's no value included after the `**`. I think all of these properties should be reworked like so:
```suggestion
                description += "**cloud_account_id:** " + cloud_account_id + "\n"
```

![Screenshot 2024-03-08 at 12 53 13](https://github.com/DefectDojo/django-DefectDojo/assets/1749665/4b06692d-aa72-4a54-b0fb-aef3708857d9)

![Screenshot 2024-03-08 at 12 56 04](https://github.com/DefectDojo/django-DefectDojo/assets/1749665/ee991972-07d1-4e46-9b90-528994b8ca74)

2024-03-11 19:16 UTC, cneill submitted a review, later dismissed

2024-03-28 10:15 UTC, manuel-sommer commented
Closed because of the failed unittest, reopening now.

2024-03-28 10:16 UTC, manuel-sommer commented on dojo/tools/deepfence_threatmapper/parser.py
> +                if Name is not None and Severity is not None:
@cneill: I have no clue here why I need this check, but otherwise, two additional findings will be added with all values "None".

2024-04-20 22:35 UTC, manuel-sommer commented
Reminder @cneill

2024-04-29 11:15 UTC, manuel-sommer commented
Reminder to review @cneill and @mtesauro

2024-05-02 03:55 UTC, Maffooch commented on dojo/tools/deepfence_threatmapper/parser.py
Can these elif branches be broken into functions?

2024-05-02 10:18 UTC, manuel-sommer commented on dojo/tools/deepfence_threatmapper/parser.py
done, good point @Maffooch

2024-05-06 13:07 UTC, manuel-sommer commented
Any updates on this?

2024-05-27 16:39 UTC, manuel-sommer commented
@Maffooch and @cneill can you review this please?

2024-06-07 07:22 UTC, manuel-sommer commented
Hi @mtesauro, 

it would be nice if you could review this. I just rebased this PR to also include the settings.disp sha hash sum.

2024-06-13 00:33 UTC, mtesauro approved these changes
Approved

2024-06-13 16:50 UTC, shodanwashere commented
> @manuel-sommer @shodanwashere Just for awareness, there's some very new parser guidelines I wrote up at #9690
> 
> In this specific case, I think this is fine because they are from the same tool (and type of tool) and have generally the same info expressed in different file format.
> 
> Would love to have you confirm that since shodanwashere appears to be a user of this tool.

I've read the parser guidelines and I can see where you're coming from. Thankfully, the guidelines that were written in that quarterly update make it so this multi-parser is an exception to the rule, so I don't have any comments to make on that note.

However, I'm also interested on how it would affect parsers for some other tools, like Harbor, which I use myself as well, and can encompass different scanning tools from different vendors, like AquaSec's Trivy and Quay's Clair scanners. Other than that, it seems good to me.

2024-06-17 20:43 UTC, cneill commented
Looks like this one needs a rebase to update `.settings.dist.py.sha256sum`. The code looks good to me, so if the tests pass after a rebase I'll :+1:

2024-06-17 20:52 UTC, manuel-sommer commented
Rebase done @cneill

2024-06-20 16:42 UTC, Maffooch requested changes

2024-06-20 16:42 UTC, Maffooch commented on dojo/settings/settings.dist.py
> -    'Wiz Scan': DEDUPE_ALGO_HASH_CODE,
This looks like an oops

2024-06-20 16:49 UTC, manuel-sommer commented on dojo/settings/settings.dist.py
> -    'Wiz Scan': DEDUPE_ALGO_HASH_CODE,
oh yeah, sorry for that

2024-06-20 16:51 UTC, manuel-sommer commented
Done @Maffooch, you can continue the review.

2024-06-20 16:52 UTC, Maffooch commented
Yep! Will approve once all tests are clear :)

2024-06-20 18:23 UTC, grendel513 approved these changes

2024-06-21 18:52 UTC, cneill approved these changes

2024-06-21 21:27 UTC, cneill commented
Would you mind recalculating the hash and resolving the merge conflict @manuel-sommer ?

2024-06-21 21:28 UTC, mtesauro commented
@manuel-sommer Mind one more rev on the sha256 sum for settings.dist.py? Order of PR merges put this one into merge conflict.

Thanks :pray:

2024-06-21 21:59 UTC, manuel-sommer commented
Done @mtesauro and @cneill

2024-06-21 22:34 UTC, merged