add cve values to openvas csv parser
DefectDojo/django-DefectDojo pull request #9791
Opened 2024-03-20 07:49 UTC by manuel-sommer

See https://github.com/DefectDojo/django-DefectDojo/discussions/9780

2024-03-22 20:36 UTC, mtesauro approved these changes
Approved

2024-03-25 15:08 UTC, Maffooch requested changes
The finding `cve` field will be deprecated in the near future. Please use the `vulnerability_id` field instead. It allows for having multiple CVEs on a single finding in the case of `CveColumnMappingStrategy`

2024-03-25 16:39 UTC, Maffooch requested changes

2024-03-25 16:39 UTC, Maffooch commented on dojo/tools/openvas/csv_parser.py
> +            finding.unsaved_vulnerability_ids.append(column_value.split(",")[0])
If there are multiple CVEs in this list, we should probably save more than just the first one

2024-03-25 16:39 UTC, Maffooch commented on unittests/tools/test_openvas_parser.py
> +            self.assertEqual(finding.unsaved_vulnerability_ids[0], "")
This seems like unexpected behavior. Why would we want an empty string to be here?

2024-03-27 18:43 UTC, Maffooch approved these changes

2024-03-27 22:39 UTC, blakeaowens approved these changes

2024-03-27 23:19 UTC, cneill approved these changes

2024-03-28 01:44 UTC, merged