Refactor awssecurityhub and add endpoint
DefectDojo/django-DefectDojo pull request #9814
Opened 2024-03-23 21:31 UTC by manuel-sommer

- refactor awssecurityhub
- add endpoint to Inspector

2024-03-23 21:32 UTC, manuel-sommer commented
@testaccount90009, fyi.

2024-03-25 14:36 UTC, Maffooch approved these changes

2024-03-25 21:42 UTC, mtesauro approved these changes
Approved

2024-03-27 20:21 UTC, manuel-sommer commented
close and reopen to retrigger pipeline

2024-03-27 22:17 UTC, blakeaowens commented on dojo/tools/awssecurityhub/guardduty.py
> +            print("/777777777777777777777")
```suggestion
```

2024-03-27 22:17 UTC, blakeaowens commented on dojo/tools/awssecurityhub/guardduty.py
> +                print("AFJIEOFJIOEFJOFJIO")
```suggestion
```

2024-03-27 22:18 UTC, blakeaowens requested changes
Please remove print statements.

2024-03-27 22:27 UTC, manuel-sommer commented
Done @blakeaowens

2024-03-27 22:43 UTC, blakeaowens approved these changes

2024-03-28 01:28 UTC, merged