release notes for v2.33.0
DefectDojo/django-DefectDojo pull request #9836
Opened 2024-03-27 15:21 UTC by manuel-sommer

2024-03-27 19:00 UTC, Maffooch approved these changes

2024-03-27 22:30 UTC, mtesauro approved these changes
Approved

2024-03-27 22:41 UTC, blakeaowens approved these changes

2024-03-28 16:30 UTC, cneill requested changes
Just a small typo here

2024-03-28 16:30 UTC, cneill commented on docs/content/en/getting_started/upgrading/2.33.md
> +- Acunetix and Acunetix360 were merged to Acunetix. There is a migration process built into the upgrade that will automatically convert exiting Acunetix360 findings into Acunetix findings.
```suggestion
- Acunetix and Acunetix360 were merged to Acunetix. There is a migration process built into the upgrade that will automatically convert existing Acunetix360 findings into Acunetix findings.
```

2024-03-28 17:44 UTC, cneill approved these changes

2024-04-02 06:01 UTC, merged