remove defusedxml in favor of lxml
DefectDojo/django-DefectDojo pull request #9840
Opened 2024-03-28 08:17 UTC by manuel-sommer

I would recommend to either go with lxml or defusedxml, but don't use a mixture of both.
https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762/19

I chose lxml as defusedxml got the last update in March 2021

2024-03-28 08:17 UTC, manuel-sommer commented
@Maffooch this is a followup of https://github.com/DefectDojo/django-DefectDojo/pull/9812

2024-03-28 08:21 UTC, manuel-sommer commented
FYI: I can do a followup PR to fix the added TRY200 regarding ruff linter, but I did prioritize this PR on migrating to lxml, but not on fixing all linter failures of previous implemented parsers.

2024-03-28 17:03 UTC, cneill commented
I believe we originally started using `defusedxml` to avoid potential security issues parsing untrusted XML with `lxml`. [bandit](https://pypi.org/project/bandit/) now reports many of these calls as vulnerable:

```
...
>> Issue: [B320:blacklist] Using lxml.etree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.parse with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./dojo/tools/zap/parser.py:28:15
27	    def get_findings(self, file, test):
28	        tree = etree.parse(file)
29	        items = list()

--------------------------------------------------
>> Issue: [B320:blacklist] Using lxml.etree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.parse with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./unittests/tools/test_vcg_parser.py:48:18
47	        single_finding = open("unittests/scans/vcg/one_finding.xml")
48	        vcgscan = etree.parse(single_finding)
49	        finding = self.parser.parse_issue(vcgscan.findall("CodeIssue")[0], Test())
...
```

The [defusedxml README](https://github.com/tiran/defusedxml) describes these various vulnerabilities in more detail and provides [some suggestions for safely using lxml](https://github.com/tiran/defusedxml?tab=readme-ov-file#defusedxmllxml). Additionally, lxml has [some suggestions](https://lxml.de/FAQ.html#how-do-i-use-lxml-safely-as-a-web-service-endpoint) on their site.

tl;dr: I think we should either do the legwork to make `lxml` safe, or convert the few cases where `lxml` is already used to `defusedxml` calls:

```
Test results:
>> Issue: [B320:blacklist] Using lxml.etree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.fromstring with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./dojo/tools/api_sonarqube/importer.py:385:18
384	        parser = etree.HTMLParser()
385	        details = etree.fromstring(vuln_details, parser)
386	

--------------------------------------------------
>> Issue: [B320:blacklist] Using lxml.etree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.parse with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./dojo/tools/burp_enterprise/parser.py:23:15
22	        parser = etree.HTMLParser()
23	        tree = etree.parse(filename, parser)
24	        if tree:

--------------------------------------------------
>> Issue: [B320:blacklist] Using lxml.etree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.parse with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./dojo/tools/sonarqube/parser.py:37:19
36	            parser = etree.HTMLParser()
37	            tree = etree.parse(filename, parser)
38	            if self.mode not in [None, "detailed"]:

--------------------------------------------------
>> Issue: [B320:blacklist] Using lxml.etree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks. Replace lxml.etree.fromstring with its defusedxml equivalent function.
   Severity: Medium   Confidence: High
   CWE: CWE-20 (https://cwe.mitre.org/data/definitions/20.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_calls.html#b313-b320-xml-bad-etree
   Location: ./dojo/tools/sonarqube/parser.py:69:38
68	                parser = etree.HTMLParser()
69	                html_desc_as_e_tree = etree.fromstring(issue_detail["htmlDesc"], parser)
70	                issue_description = self.get_description(html_desc_as_e_tree)

--------------------------------------------------
```

2024-04-20 19:22 UTC, manuel-sommer commented
@cneill, I updated how lxml is used (with resolve_entities=False)

2024-04-20 19:34 UTC, manuel-sommer commented
Could you also take a look @Maffooch if lxml is fine to be used like this?

2024-04-20 20:58 UTC, manuel-sommer commented
reopening to retrigger failed tests.

2024-04-21 00:14 UTC, mtesauro approved these changes
Approved

2024-05-02 03:56 UTC, blakeaowens approved these changes

2024-05-02 09:52 UTC, manuel-sommer commented
@mtesauro: It would be really nice if we could merge this soonish because of the high number of ruff adjustments (PRs) as I have to rebase so many files here and so frequently.

2024-05-03 17:26 UTC, cneill requested changes
I see that bandit is still reporting these uses of `lxml` as vulnerabilities. There's [an issue](https://github.com/PyCQA/bandit/issues/767) in their repo requesting that bandit update its guidance based on [the latest guidance from `defusedxml`](https://github.com/tiran/defusedxml/pull/98/files) about `lxml`, so it's not entirely clear to me if bandit's guidance is still up-to-date, or if setting `resolve_entities=False` is sufficient to make `lxml` safe. The [other default parameters](https://github.com/lxml/lxml/blob/a9f31d9ba0f6db7b0c6576b4b9014a4ea7649eca/src/lxml/parser.pxi#L1571-L1605) to `XMLParser` seem reasonable to me. Overall, I *think* this is fine, but I'm not 100% certain.

My main concern is that we will need to be vigilant with future XML-based tool parsers to ensure that `resolve_entities` is always set to `False`, as you have done here. This is beyond the scope of this PR, but In the future we might benefit from providing unified parsing utilities for handling these common formats (JSON, XML, CSV, HTML). It doesn't really make sense for everyone to use their own approach.

Finally, there are a couple uses of `open()` here that warn about not closing those files when running unit tests (this was recently addressed for other unit tests in #10055):

```
2024-05-02T11:52:15.3726570Z uwsgi-1  | Traceback (most recent call last):
2024-05-02T11:52:15.3727653Z uwsgi-1  |   File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
2024-05-02T11:52:15.3728705Z uwsgi-1  |     if method() is not None:
2024-05-02T11:52:15.3729474Z uwsgi-1  |        ^^^^^^^^
2024-05-02T11:52:15.3730796Z uwsgi-1  | ResourceWarning: unclosed file <_io.TextIOWrapper name='unittests/scans/vcg/can_parse_xml.xml' mode='r' encoding='UTF-8'>
2024-05-02T11:52:15.3732028Z uwsgi-1  | ok
2024-05-02T11:52:15.3759114Z uwsgi-1  | test_parse_duplicate_findings_dedupes (unittests.tools.test_vcg_parser.TestVCGXmlParser.test_parse_duplicate_findings_dedupes) ... Exception ignored in: <_io.FileIO name='unittests/scans/vcg/duplicate_findings_dedupes.xml' mode='rb' closefd=True>
2024-05-02T11:52:15.3761565Z uwsgi-1  | Traceback (most recent call last):
2024-05-02T11:52:15.3763393Z uwsgi-1  |   File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
2024-05-02T11:52:15.3764554Z uwsgi-1  |     if method() is not None:
2024-05-02T11:52:15.3765192Z uwsgi-1  |        ^^^^^^^^
2024-05-02T11:52:15.3766733Z uwsgi-1  | ResourceWarning: unclosed file <_io.TextIOWrapper name='unittests/scans/vcg/duplicate_findings_dedupes.xml' mode='r' encoding='UTF-8'>
2024-05-02T11:52:15.3768224Z uwsgi-1  | ok
2024-05-02T11:52:15.3773865Z uwsgi-1  | test_parse_multiple_findings (unittests.tools.test_vcg_parser.TestVCGXmlParser.test_parse_multiple_findings) ... Exception ignored in: <_io.FileIO name='unittests/scans/vcg/multiple_findings.xml' mode='rb' closefd=True>
2024-05-02T11:52:15.3776549Z uwsgi-1  | Traceback (most recent call last):
2024-05-02T11:52:15.3777642Z uwsgi-1  |   File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
2024-05-02T11:52:15.3778911Z uwsgi-1  |     if method() is not None:
2024-05-02T11:52:15.3779596Z uwsgi-1  |        ^^^^^^^^
2024-05-02T11:52:15.3781046Z uwsgi-1  | ResourceWarning: unclosed file <_io.TextIOWrapper name='unittests/scans/vcg/multiple_findings.xml' mode='r' encoding='UTF-8'>
2024-05-02T11:52:15.3782411Z uwsgi-1  | ok
2024-05-02T11:52:15.3783932Z uwsgi-1  | test_parse_no_content_no_findings (unittests.tools.test_vcg_parser.TestVCGXmlParser.test_parse_no_content_no_findings) ... ok
2024-05-02T11:52:15.3792887Z uwsgi-1  | test_parse_single_finding (unittests.tools.test_vcg_parser.TestVCGXmlParser.test_parse_single_finding) ... Exception ignored in: <_io.FileIO name='unittests/scans/vcg/single_finding.xml' mode='rb' closefd=True>
2024-05-02T11:52:15.3795244Z uwsgi-1  | Traceback (most recent call last):
2024-05-02T11:52:15.3796160Z uwsgi-1  |   File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
2024-05-02T11:52:15.3797262Z uwsgi-1  |     if method() is not None:
2024-05-02T11:52:15.3797781Z uwsgi-1  |        ^^^^^^^^
2024-05-02T11:52:15.3798745Z uwsgi-1  | ResourceWarning: unclosed file <_io.TextIOWrapper name='unittests/scans/vcg/single_finding.xml' mode='r' encoding='UTF-8'>
2024-05-02T11:52:15.3799470Z uwsgi-1  | ok
2024-05-02T11:52:15.3803865Z uwsgi-1  | test_parseissuexml_with_issue_has_finding (unittests.tools.test_vcg_parser.TestVCGXmlParser.test_parseissuexml_with_issue_has_finding) ... Exception ignored in: <_io.FileIO name='unittests/scans/vcg/one_finding.xml' mode='rb' closefd=True>
2024-05-02T11:52:15.3806535Z uwsgi-1  | Traceback (most recent call last):
2024-05-02T11:52:15.3807225Z uwsgi-1  |   File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
2024-05-02T11:52:15.3807831Z uwsgi-1  |     if method() is not None:
2024-05-02T11:52:15.3808189Z uwsgi-1  |        ^^^^^^^^
2024-05-02T11:52:15.3809587Z uwsgi-1  | ResourceWarning: unclosed file <_io.TextIOWrapper name='unittests/scans/vcg/one_finding.xml' mode='r' encoding='UTF-8'>
```

2024-05-03 17:26 UTC, cneill commented on unittests/tools/test_vcg_parser.py
> +        single_finding = open("unittests/scans/vcg/single_finding.xml")
Please wrap this in a `with` as done recently in #10055 to prevent unclosed file warnings

2024-05-03 17:26 UTC, cneill commented on unittests/tools/test_vcg_parser.py
> +        findings = open("unittests/scans/vcg/multiple_findings.xml")
Please wrap this in a `with` as done recently in #10055 to prevent unclosed file warnings

2024-05-03 17:26 UTC, cneill commented on unittests/tools/test_vcg_parser.py
> +        duplicate_finding = open("unittests/scans/vcg/duplicate_findings_dedupes.xml")
Please wrap this in a `with` as done recently in #10055 to prevent unclosed file warnings

2024-05-03 17:26 UTC, cneill commented on unittests/tools/test_vcg_parser.py
> +        single_finding = open("unittests/scans/vcg/one_finding.xml")
Please wrap this in a `with` as done recently in #10055 to prevent unclosed file warnings

2024-05-03 17:26 UTC, cneill commented on unittests/tools/test_vcg_parser.py
> +        content = open("unittests/scans/vcg/can_parse_xml.xml")
Please wrap this in a `with` as done recently in #10055 to prevent unclosed file warnings

2024-05-03 17:32 UTC, manuel-sommer commented
Thank you for the feedback.  I will fix your review before this weekend. It would be nice if we get this on the road in the next Release

2024-05-03 20:16 UTC, manuel-sommer commented
Done @cneill. You can rereview

2024-05-03 21:45 UTC, cneill approved these changes
Thanks!

2024-05-03 22:27 UTC, manuel-sommer commented
Nice, only one more to go :-)

2024-05-06 16:16 UTC, manuel-sommer commented
I resolved the merge conflict. Will we get this into release 2.34.0 @Maffooch ?

2024-05-06 16:38 UTC, Maffooch commented
@manuel-sommer Unfortunately, this PR will not make it in the 2.34.0 release. There is still some discussion happening around this change

2024-05-23 10:05 UTC, manuel-sommer commented
Do we have an update here @Maffooch ?

2024-07-02 09:02 UTC, manuel-sommer commented
Friendly reminder @Maffooch

2024-07-29 17:46 UTC, Maffooch commented
@manuel-sommer I apologize for the delay on this one, and I thank you very much for your patience. 

After much deliberation, we believe it would be the best decision to remain with defusedXML. These are the high level reasons that contributed to that decision:
- This library only warps the stdlib and does not have any dependencies. There really is not a good reason to rev versions unless it is absolutely needed
  - This is largely in response to the initial purpose of moving away from defusedXML
- Python docs [suggest using defusedXML in place of the stdlib](https://docs.python.org/3/library/xml.html#the-defusedxml-package)
- A few security tools will raise issues when using the stdlib, [such as bandit](https://bandit.readthedocs.io/en/1.6.3/blacklists/blacklist_imports.html#b405-import-xml-etree)
  - This may restrict some very compliancy strict organizations from using DefectDojo, and therefore slow adoption
- DefectDojo is viewed as a pillar in security, and by deviating away from the recommended security best practices, it could raise some eyebrows for a few folks

I agree with your intention of consolidating to a single XML parsing library, and we believe that defusedXML would be in the best interest of the project

2024-07-29 19:32 UTC, mtesauro commented
@manuel-sommer Thanks for all your hard work on this - once we did the research, it proved that defusedXML was the best path forward. We're going to update the "Writing a parser" to include instructions to use this library going forward. We'd probably not have done the research if you'd not done this PR so even though it didn't get merged, it **DID** help. :+1:

2024-07-29 20:33 UTC, manuel-sommer commented
@mtesauro and @Maffooch I added the docs here.

2024-07-29 21:41 UTC, Maffooch approved these changes

2024-07-29 21:42 UTC, merged