helm: Add subcomponent labels for celery beat and worker at deployment
DefectDojo/django-DefectDojo pull request #9865
Opened 2024-04-02 10:22 UTC by al-cheb

In scope of this https://github.com/DefectDojo/django-DefectDojo/pull/9078 PR only the deployment label was added. To use pod affinity/antiaffinity for celery components a label should be added at  `.spec.template.metadata.labels` level.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    defectdojo.org/component: celery
    defectdojo.org/subcomponent: worker
spec:
  selector:
    matchLabels:
      defectdojo.org/component: celery
      defectdojo.org/subcomponent: worker
  template:
    metadata:
      labels:
        defectdojo.org/component: celery
        defectdojo.org/subcomponent: worker
```

1, The first label is for deployment itself, it gives label for that particular deployment. 
2. The second label is selector: matchLabels which tells the resources(service etc) to match the pod according to label.
3. The third label is podTemplate labels, the template is actually podTemplate. It describe the pod that it is launched.

2024-04-03 01:31 UTC, mtesauro commented
Closing and re-opening to re-kick the tests that didn't seem to run correctly.

2024-04-03 06:12 UTC, al-cheb commented
@mtesauro, Thank you.

2024-04-04 17:44 UTC, cneill approved these changes

2024-04-06 01:25 UTC, mtesauro approved these changes
Approved

2024-04-08 13:59 UTC, Maffooch requested changes

2024-04-08 13:59 UTC, Maffooch commented on helm/defectdojo/Chart.yaml
Please do not change the chart version here

2024-04-08 13:59 UTC, Maffooch commented on helm/defectdojo/Chart.lock
please revert this change as well as we do not want to rev versions here

2024-04-08 16:20 UTC, al-cheb commented on helm/defectdojo/Chart.yaml
Thanks, updated.

2024-04-08 16:20 UTC, al-cheb commented on helm/defectdojo/Chart.lock
Thanks, updated.

2024-04-08 23:28 UTC, Maffooch approved these changes

2024-04-11 20:08 UTC, al-cheb commented
@Maffooch, could you merge,please?

2024-04-12 04:50 UTC, mtesauro commented
@al-cheb PRs require 4 approvals from the reviewers before being merged.

The only exception is library/module updates like dependabot and renovate.

2024-04-12 07:37 UTC, al-cheb commented
@dsever, hey, could you please review?

2024-04-30 14:24 UTC, hblankenship approved these changes

2024-04-30 20:35 UTC, merged