add test description for AWS SecurityHub Scan
DefectDojo/django-DefectDojo pull request #9904
Opened 2024-04-09 06:53 UTC by manuel-sommer

2024-04-13 19:49 UTC, mtesauro commented
@manuel-sommer You might want to look at @cneill 's points in #9912 - not the same thing as you're doing here but also about adding items to the description of AWS Sec Hub

2024-04-16 19:02 UTC, manuel-sommer commented
I looked at the PR @mtesauro and reviewed it.

2024-04-23 00:26 UTC, cneill requested changes
Minor change on the Test name but otherwise looks good!

2024-04-23 00:26 UTC, cneill commented on dojo/tools/awssecurityhub/parser.py
> +    ID = "AWS SecurityHub"
```suggestion
    ID = "AWS Security Hub"
```

2024-04-23 00:36 UTC, manuel-sommer commented
Done @cneill

2024-04-23 16:45 UTC, cneill approved these changes

2024-04-23 17:06 UTC, mtesauro approved these changes
Approved

2024-05-02 03:26 UTC, blakeaowens approved these changes

2024-05-02 03:50 UTC, Maffooch approved these changes

2024-05-02 03:50 UTC, merged